
export interface CodeRushChallenge {
  srNo: number;
  id: string;
  title: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  snippet: string; // e.g., "for (let i = 0; i < ___; i++)"
  answer: string; // e.g., "5"
}

export const codeRushChallenges: CodeRushChallenge[] = [
  // JavaScript Easy
  {
    srNo: 1,
    id: 'cr-js-easy-01',
    title: 'Variable Declaration',
    description: 'Declare a variable named "count".',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: '___ count = 10;',
    answer: 'let',
  },
  {
    srNo: 2,
    id: 'cr-js-easy-02',
    title: 'If Statement',
    description: 'Complete the if statement condition.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'if (x ___ 5)',
    answer: '>',
  },
  {
    srNo: 3,
    id: 'cr-js-easy-03',
    title: 'Function Keyword',
    description: 'Define a function named "myFunction".',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: '___ myFunction() { }',
    answer: 'function',
  },
  {
    srNo: 4,
    id: 'cr-js-easy-04',
    title: 'Logging to Console',
    description: 'Log a message to the console.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'console.___("Hello");',
    answer: 'log',
  },
  {
    srNo: 5,
    id: 'cr-js-easy-05',
    title: 'Strict Equality',
    description: 'Check if two values are strictly equal.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'if (a ___ b)',
    answer: '===',
  },
  {
    srNo: 6,
    id: 'cr-js-easy-06',
    title: 'Array Length',
    description: 'Get the number of items in an array.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const len = myArray.___',
    answer: 'length',
  },
  {
    srNo: 7,
    id: 'cr-js-easy-07',
    title: 'Else Clause',
    description: 'Provide the alternative for an if statement.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'if (condition) { ... } ___ { ... }',
    answer: 'else',
  },

  // JavaScript Medium
  {
    srNo: 8,
    id: 'cr-js-medium-01',
    title: 'For...of Loop',
    description: 'Iterate over an array.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'for (const item ___ myArray) { }',
    answer: 'of',
  },
  {
    srNo: 9,
    id: 'cr-js-medium-02',
    title: 'Arrow Function',
    description: 'Define a simple arrow function.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const add = (a, b) ___ a + b;',
    answer: '=>',
  },
  {
    srNo: 10,
    id: 'cr-js-medium-03',
    title: 'Array Filter',
    description: 'Filter an array for even numbers.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const evens = arr.filter(n => n % 2 ___ 0);',
    answer: '===',
  },
  {
    srNo: 11,
    id: 'cr-js-medium-04',
    title: 'Ternary Operator',
    description: 'Use a ternary operator for a simple condition.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const type = age >= 18 ___ "adult" : "minor";',
    answer: '?',
  },
  {
    srNo: 12,
    id: 'cr-js-medium-05',
    title: 'Array map',
    description: 'Create a new array by doubling each element.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const doubled = numbers.___(n => n * 2);',
    answer: 'map',
  },

  // JavaScript Hard
  {
    srNo: 13,
    id: 'cr-js-hard-01',
    title: 'Async/Await',
    description: 'Wait for a promise to resolve.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'const data = ___ response.json();',
    answer: 'await',
  },
  {
    srNo: 14,
    id: 'cr-js-hard-02',
    title: 'Array Reduce',
    description: 'Complete the reduce function to sum an array.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'arr.reduce((acc, curr) => acc + curr, ___);',
    answer: '0',
  },
  {
    srNo: 15,
    id: 'cr-js-hard-03',
    title: 'Promise.all',
    description: 'Wait for multiple promises to resolve.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: '___([promise1, promise2]);',
    answer: 'Promise.all',
  },
  {
    srNo: 16,
    id: 'cr-js-hard-04',
    title: 'Class Constructor',
    description: 'Define the constructor method for a class.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'class Player { ___(name) { this.name = name; } }',
    answer: 'constructor',
  },

  // Python Easy
  {
    srNo: 17,
    id: 'cr-py-easy-01',
    title: 'Function Definition',
    description: 'Define a function in Python.',
    language: 'python',
    difficulty: 'Easy',
    snippet: '___ my_func():',
    answer: 'def',
  },
  {
    srNo: 18,
    id: 'cr-py-easy-02',
    title: 'For Loop Range',
    description: 'Loop from 0 to 9.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'for i in ___(10):',
    answer: 'range',
  },
  {
    srNo: 19,
    id: 'cr-py-easy-03',
    title: 'Else Statement',
    description: 'Add the else block to an if statement.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if x > 0:\n  print("Positive")\n___:\n  print("Not positive")',
    answer: 'else',
  },
  {
    srNo: 20,
    id: 'cr-py-easy-04',
    title: 'Check for membership',
    description: 'Check if an item exists in a list.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if "apple" ___ my_list:',
    answer: 'in',
  },
    {
    srNo: 21,
    id: 'cr-py-easy-05',
    title: 'Get Length',
    description: 'Get the length of a list.',
    language: 'python',
    difficulty: 'Easy',
    snippet: '___(my_list)',
    answer: 'len',
  },

  // Python Medium
  {
    srNo: 22,
    id: 'cr-py-medium-01',
    title: 'Import Module',
    description: 'Import the math module.',
    language: 'python',
    difficulty: 'Medium',
    snippet: '___ math',
    answer: 'import',
  },
  {
    srNo: 23,
    id: 'cr-py-medium-02',
    title: 'List Append',
    description: 'Add an item to a list.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'my_list.___(4)',
    answer: 'append',
  },
  {
    srNo: 24,
    id: 'cr-py-medium-03',
    title: 'Lambda Function',
    description: 'Create a simple lambda function.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'x = ___ a : a + 10',
    answer: 'lambda',
  },
  {
    srNo: 25,
    id: 'cr-py-medium-04',
    title: 'Class Constructor',
    description: 'Define the constructor for a Python class.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'def ___ (self):\n  pass',
    answer: '__init__',
  },
    {
    srNo: 26,
    id: 'cr-py-medium-05',
    title: 'Elif Clause',
    description: 'Use an "else if" condition.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'if x > 10:\n  ...\n___ x > 5:\n  ...',
    answer: 'elif',
  },

  // Python Hard
  {
    srNo: 27,
    id: 'cr-py-hard-01',
    title: 'List Comprehension',
    description: 'Complete the list comprehension.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '[x*x ___ x in range(5)]',
    answer: 'for',
  },
    {
    srNo: 28,
    id: 'cr-py-hard-02',
    title: 'Decorator Syntax',
    description: 'Apply a decorator to a function.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '___my_decorator\ndef say_hello():\n  pass',
    answer: '@',
  },
  {
    srNo: 29,
    id: 'cr-py-hard-03',
    title: 'Context Manager',
    description: 'Open a file using a context manager.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '___ open("file.txt", "r") as f:',
    answer: 'with',
  },
  {
    srNo: 30,
    id: 'cr-py-hard-04',
    title: 'Generator Yield',
    description: 'Yield a value from a generator function.',
    language: 'python',
    difficulty: 'Hard',
    snippet: 'def my_gen():\n  ___ 1',
    answer: 'yield',
  },
    
  // Java Easy
  {
    srNo: 31,
    id: 'cr-java-easy-01',
    title: 'Main Method',
    description: 'Define the main method entry point.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'public ___ void main(String[] args)',
    answer: 'static',
  },
  {
    srNo: 32,
    id: 'cr-java-easy-02',
    title: 'New Instance',
    description: 'Create a new object instance.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'String myString = ___ String();',
    answer: 'new',
  },
  {
    srNo: 33,
    id: 'cr-java-easy-03',
    title: 'System Output',
    description: 'Print a line to the console.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'System.out.___("Hello");',
    answer: 'println',
  },
  {
    srNo: 34,
    id: 'cr-java-easy-04',
    title: 'For Loop',
    description: 'Complete the for loop syntax.',
    language: 'java',
    difficulty: 'Easy',
    snippet: '___ (int i = 0; i < 5; i++)',
    answer: 'for',
  },
  {
    srNo: 35,
    id: 'cr-java-easy-05',
    title: 'Final Variable',
    description: 'Declare a constant variable.',
    language: 'java',
    difficulty: 'Easy',
    snippet: '___ int MY_NUM = 15;',
    answer: 'final',
  },

  // Java Medium
  {
    srNo: 36,
    id: 'cr-java-medium-01',
    title: 'Import Statement',
    description: 'Import the ArrayList class.',
    language: 'java',
    difficulty: 'Medium',
    snippet: '___ java.util.ArrayList;',
    answer: 'import',
  },
  {
    srNo: 37,
    id: 'cr-java-medium-02',
    title: 'Class Inheritance',
    description: 'Make a class inherit from another.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'class Dog ___ Animal { }',
    answer: 'extends',
  },
  {
    srNo: 38,
    id: 'cr-java-medium-03',
    title: 'Interface Implementation',
    description: 'Make a class implement an interface.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'class Car ___ Drivable { }',
    answer: 'implements',
  },
  {
    srNo: 39,
    id: 'cr-java-medium-04',
    title: 'Public Access',
    description: 'Specify a method as publicly accessible.',
    language: 'java',
    difficulty: 'Medium',
    snippet: '___ void myMethod() {}',
    answer: 'public',
  },

  // Java Hard
  {
    srNo: 40,
    id: 'cr-java-hard-01',
    title: 'Exception Handling',
    description: 'Catch an exception.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'try { ... } ___ (Exception e) { ... }',
    answer: 'catch',
  },
  {
    srNo: 41,
    id: 'cr-java-hard-02',
    title: 'Override Annotation',
    description: 'Mark a method as an override.',
    language: 'java',
    difficulty: 'Hard',
    snippet: '___ \npublic String toString() { ... }',
    answer: '@Override',
  },
  {
    srNo: 42,
    id: 'cr-java-hard-03',
    title: 'Thread-safe method',
    description: 'Mark a method as thread-safe.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'public ___ void myMethod() { ... }',
    answer: 'synchronized',
  },
  {
    srNo: 43,
    id: 'cr-java-hard-04',
    title: 'Generic Type',
    description: 'Define a generic ArrayList.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'ArrayList<___> list = new ArrayList<>();',
    answer: 'String',
  },

  // C++ Easy
  {
    srNo: 44,
    id: 'cr-cpp-easy-01',
    title: 'Include Directive',
    description: 'Include the iostream library.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '#include <___>',
    answer: 'iostream',
  },
  {
    srNo: 45,
    id: 'cr-cpp-easy-02',
    title: 'Standard Output',
    description: 'Print to the console.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'std::___ << "Hello";',
    answer: 'cout',
  },
  {
    srNo: 46,
    id: 'cr-cpp-easy-03',
    title: 'Using Namespace',
    description: 'Use the standard namespace.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '___ namespace std;',
    answer: 'using',
  },
  {
    srNo: 47,
    id: 'cr-cpp-easy-04',
    title: 'Main function return',
    description: 'End the main function successfully.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '___ 0;',
    answer: 'return',
  },
  {
    srNo: 48,
    id: 'cr-cpp-easy-05',
    title: 'Vector Include',
    description: 'Include the vector library.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '#include <___>',
    answer: 'vector',
  },

  // C++ Medium
  {
    srNo: 49,
    id: 'cr-cpp-medium-01',
    title: 'Pointer Declaration',
    description: 'Declare a pointer to an integer.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int___ p;',
    answer: '*',
  },
  {
    srNo: 50,
    id: 'cr-cpp-medium-02',
    title: 'Dynamic Memory Allocation',
    description: 'Allocate an integer on the heap.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int* p = ___ int;',
    answer: 'new',
  },
  {
    srNo: 51,
    id: 'cr-cpp-medium-03',
    title: 'Vector push_back',
    description: 'Add an element to a vector.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'my_vector.___ (10);',
    answer: 'push_back',
  },
    {
    srNo: 52,
    id: 'cr-cpp-medium-04',
    title: 'Class Inheritance',
    description: 'Inherit from a base class.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'class Derived : ___ Base {};',
    answer: 'public',
  },
  
  // C++ Hard
  {
    srNo: 53,
    id: 'cr-cpp-hard-01',
    title: 'Virtual Function',
    description: 'Declare a virtual function for polymorphism.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: '___ void my_func() = 0;',
    answer: 'virtual',
  },
  {
    srNo: 54,
    id: 'cr-cpp-hard-02',
    title: 'Template Declaration',
    description: 'Declare a function template.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: '___<typename T>',
    answer: 'template',
  },
  {
    srNo: 55,
    id: 'cr-cpp-hard-03',
    title: 'Deallocate Array',
    description: 'Deallocate an array from the heap.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'delete___ arr;',
    answer: '[]',
  },
  {
    srNo: 56,
    id: 'cr-cpp-hard-04',
    title: 'Header Guard',
    description: 'Start a header guard to prevent multiple inclusions.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: '___ MY_HEADER_H',
    answer: '#ifndef',
  },
  {
    srNo: 57,
    id: 'cr-js-easy-10',
    title: 'Alert Box',
    description: 'Display a simple alert box.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: '___("Hello World");',
    answer: 'alert',
  },
  {
    srNo: 58,
    id: 'cr-js-medium-11',
    title: 'Spread Operator (Objects)',
    description: 'Combine two objects into a new object.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const merged = { ...obj1, ___ };',
    answer: '...obj2',
  },
  {
    srNo: 59,
    id: 'cr-js-hard-05',
    title: 'Class Inheritance',
    description: 'Make a `Dog` class inherit from `Animal`.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'class Dog ___ Animal { }',
    answer: 'extends',
  },
  {
    srNo: 60,
    id: 'cr-py-easy-06',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'len(___)',
    answer: 'my_string',
  },
  {
    srNo: 61,
    id: 'cr-py-medium-06',
    title: 'Dictionary Get',
    description: 'Safely get a value from a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'my_dict.___("key", "default_value")',
    answer: 'get',
  },
  {
    srNo: 62,
    id: 'cr-py-hard-05',
    title: 'Enumerate Function',
    description: 'Iterate over a list with both index and value.',
    language: 'python',
    difficulty: 'Hard',
    snippet: 'for i, val in ___(my_list):',
    answer: 'enumerate',
  },
  {
    srNo: 63,
    id: 'cr-java-easy-06',
    title: 'Array Access',
    description: 'Access the first element of an array.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'int first = myArray[___];',
    answer: '0',
  },
  {
    srNo: 64,
    id: 'cr-java-medium-05',
    title: 'ArrayList Add',
    description: 'Add an element to an ArrayList.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'myList.___("item");',
    answer: 'add',
  },
  {
    srNo: 65,
    id: 'cr-java-hard-05',
    title: 'HashMap Creation',
    description: 'Create a new HashMap.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'HashMap<String, Integer> map = new ___<>();',
    answer: 'HashMap',
  },
  {
    srNo: 66,
    id: 'cr-cpp-easy-06',
    title: 'Get Address',
    description: 'Get the memory address of a variable.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'int* p = ___myVar;',
    answer: '&',
  },
  {
    srNo: 67,
    id: 'cr-cpp-medium-05',
    title: 'Dereference Pointer',
    description: 'Access the value pointed to by a pointer.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int val = ___p;',
    answer: '*',
  },
  {
    srNo: 68,
    id: 'cr-cpp-hard-05',
    title: 'Smart Pointer',
    description: 'Create a unique pointer.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'std::unique_ptr<int> p1 = std::___<int>(5);',
    answer: 'make_unique',
  },
  {
    srNo: 69,
    id: 'cr-js-easy-12',
    title: 'Get Array Index',
    description: 'Find the index of an element in an array.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const index = fruits.___("Banana");',
    answer: 'indexOf',
  },
  {
    srNo: 70,
    id: 'cr-js-medium-12',
    title: 'JSON Parse',
    description: 'Parse a JSON string into an object.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const obj = JSON.___(\'{"name":"John"}\');',
    answer: 'parse',
  },
  {
    srNo: 71,
    id: 'cr-py-easy-07',
    title: 'Print to console',
    description: 'Print a message to the console.',
    language: 'python',
    difficulty: 'Easy',
    snippet: '___("Hello Python")',
    answer: 'print',
  },
  {
    srNo: 72,
    id: 'cr-py-medium-07',
    title: 'Dictionary Keys',
    description: 'Get all keys from a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'my_dict.keys()',
    answer: 'keys',
  },
  {
    srNo: 73,
    id: 'cr-java-easy-07',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'int len = myString.___();',
    answer: 'length',
  },
  {
    srNo: 74,
    id: 'cr-java-medium-06',
    title: 'Array Length',
    description: 'Get the number of elements in an array.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'int len = myArray.length;',
    answer: 'length',
  },
  {
    srNo: 75,
    id: 'cr-cpp-easy-07',
    title: 'Input Stream',
    description: 'Read input from the console.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'std::___ >> myVar;',
    answer: 'cin',
  },
  {
    srNo: 76,
    id: 'cr-cpp-medium-06',
    title: 'Struct Member Access',
    description: 'Access a member of a struct pointer.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'my_struct_ptr___member = 10;',
    answer: '->',
  },
  {
    srNo: 77,
    id: 'cr-js-easy-13',
    title: 'Template Literals',
    description: 'Use template literals to create a formatted string.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const name = "World";\nconst greeting = `Hello, ${___}!`;',
    answer: 'name',
  },
  {
    srNo: 78,
    id: 'cr-js-medium-13',
    title: 'Array forEach',
    description: 'Iterate over an array using forEach.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: '["a", "b", "c"].___(item => console.log(item));',
    answer: 'forEach',
  },
  {
    srNo: 79,
    id: 'cr-js-hard-06',
    title: 'Promise catch',
    description: 'Handle a rejected promise.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'myPromise.then(...).___(error => console.error(error));',
    answer: 'catch',
  },
  {
    srNo: 80,
    id: 'cr-py-easy-08',
    title: 'Boolean Check',
    description: 'Check if a variable is True.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if is_active ___ True:',
    answer: '==',
  },
  {
    srNo: 81,
    id: 'cr-py-medium-08',
    title: 'Import Specific Function',
    description: 'Import only the `sqrt` function from a module.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'from math import ___',
    answer: 'sqrt',
  },
  {
    srNo: 82,
    id: 'cr-py-hard-06',
    title: 'Raise Exception',
    description: 'Manually raise an exception.',
    language: 'python',
    difficulty: 'Hard',
    snippet: 'if x < 0:\n  ___ ValueError("Number cannot be negative")',
    answer: 'raise',
  },
  {
    srNo: 83,
    id: 'cr-java-easy-08',
    title: 'Method Parameters',
    description: 'Define a method that takes an integer parameter.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'public void myMethod(int ___) { }',
    answer: 'x',
  },
  {
    srNo: 84,
    id: 'cr-java-medium-07',
    title: '`this` keyword',
    description: 'Refer to the current object\'s instance variable.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'this.___ = name;',
    answer: 'name',
  },
  {
    srNo: 85,
    id: 'cr-java-hard-06',
    title: 'Super Constructor',
    description: 'Call the constructor of the parent class.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'class Dog extends Animal { Dog() { ___(); } }',
    answer: 'super',
  },
  {
    srNo: 86,
    id: 'cr-cpp-easy-08',
    title: 'Loop Condition',
    description: 'Complete the loop condition.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'for (int i=0; i ___ 10; i++)',
    answer: '<',
  },
  {
    srNo: 87,
    id: 'cr-cpp-medium-07',
    title: 'Class Member Access',
    description: 'Access a public member of a class instance.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'MyClass obj;\nobj.___ = 5;',
    answer: 'myMember',
  },
  {
    srNo: 88,
    id: 'cr-cpp-hard-06',
    title: 'Lambda Capture',
    description: 'Capture a variable by reference in a lambda.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'int x = 5;\nauto myLambda = [___]() { x++; };',
    answer: '&x',
  },
  {
    srNo: 89,
    id: 'cr-js-easy-14',
    title: 'Access Object Property',
    description: 'Access the age property of the person object.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const age = person.___',
    answer: 'age',
  },
  {
    srNo: 90,
    id: 'cr-js-medium-14',
    title: 'Array `includes`',
    description: 'Check if an array includes a certain value.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const hasTwo = [1, 2, 3].___(2);',
    answer: 'includes',
  },
  {
    srNo: 91,
    id: 'cr-js-hard-07',
    title: 'Object keys',
    description: 'Get an array of an object\'s own enumerable property names.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'const keys = Object.___({a: 1, b: 2});',
    answer: 'keys',
  },
  {
    srNo: 92,
    id: 'cr-py-easy-09',
    title: 'Not Equal',
    description: 'Check if two values are not equal.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if a ___ b:',
    answer: '!=',
  },
  {
    srNo: 93,
    id: 'cr-py-medium-09',
    title: 'String `join`',
    description: 'Join elements of a list into a single string.',
    language: 'python',
    difficulty: 'Medium',
    snippet: '" ".___([\'a\', \'b\', \'c\'])',
    answer: 'join',
  },
  {
    srNo: 94,
    id: 'cr-py-hard-07',
    title: '`*args` Unpacking',
    description: 'Pass a list as separate arguments to a function.',
    language: 'python',
    difficulty: 'Hard',
    snippet: 'my_func(___my_list)',
    answer: '*',
  },
  {
    srNo: 95,
    id: 'cr-java-easy-09',
    title: 'Not Equal',
    description: 'Check if two integers are not equal.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'if (x ___ y)',
    answer: '!=',
  },
  {
    srNo: 96,
    id: 'cr-java-medium-08',
    title: 'Abstract Method',
    description: 'Declare an abstract method in an abstract class.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'public ___ void myMethod();',
    answer: 'abstract',
  },
  {
    srNo: 97,
    id: 'cr-java-hard-07',
    title: 'Try-with-resources',
    description: 'Automatically close a resource after use.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'try (___ stream = new FileInputStream("f.txt")) { ... }',
    answer: 'FileInputStream',
  },
  {
    srNo: 98,
    id: 'cr-cpp-easy-09',
    title: 'String Include',
    description: 'Include the string library.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '#include <___>',
    answer: 'string',
  },
  {
    srNo: 99,
    id: 'cr-cpp-medium-08',
    title: 'Vector Size',
    description: 'Get the number of elements in a vector.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int n = my_vector.___();',
    answer: 'size',
  },
  {
    srNo: 100,
    id: 'cr-cpp-hard-08',
    title: 'Shared Pointer',
    description: 'Create a shared pointer.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'std::shared_ptr<int> p1 = std::___<int>(5);',
    answer: 'make_shared',
  },
  {
    srNo: 101,
    id: 'cr-js-easy-15',
    title: 'Math Constant',
    description: 'Access the value of PI.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const pi = ___ .PI;',
    answer: 'Math',
  },
  {
    srNo: 102,
    id: 'cr-js-medium-15',
    title: 'Remove First Element',
    description: 'Remove the first element from an array.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const first = arr.___();',
    answer: 'shift',
  },
  {
    srNo: 103,
    id: 'cr-js-hard-08',
    title: 'JSON Stringify',
    description: 'Convert a JavaScript object to a JSON string.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'const json = JSON.___ (obj);',
    answer: 'stringify',
  },
  {
    srNo: 104,
    id: 'cr-py-easy-10',
    title: 'Missing Colon',
    description: 'Complete the if-statement syntax.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if x > y ___',
    answer: ':',
  },
  {
    srNo: 105,
    id: 'cr-py-medium-10',
    title: 'Dictionary Pop',
    description: 'Remove an item from a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'my_dict.___("model")',
    answer: 'pop',
  },
  {
    srNo: 106,
    id: 'cr-py-hard-08',
    title: 'Super Call',
    description: 'Call the parent class\'s method.',
    language: 'python',
    difficulty: 'Hard',
    snippet: 'class Child(Parent):\n  def __init__(self):\n    ___.__init__(self)',
    answer: 'super()',
  },
  {
    srNo: 107,
    id: 'cr-java-easy-10',
    title: 'Break Keyword',
    description: 'Exit a switch statement case.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'case 1: ...; ___ ;',
    answer: 'break',
  },
  {
    srNo: 108,
    id: 'cr-java-medium-09',
    title: 'Private Access',
    description: 'Make a variable accessible only within the class.',
    language: 'java',
    difficulty: 'Medium',
    snippet: '___ String secret;',
    answer: 'private',
  },
  {
    srNo: 109,
    id: 'cr-java-hard-08',
    title: 'Stream API Filter',
    description: 'Filter a list using the Stream API.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'list.stream().___(s -> s.startsWith("a"))',
    answer: 'filter',
  },
  {
    srNo: 110,
    id: 'cr-cpp-easy-10',
    title: 'Vector push_back',
    description: 'Add an element to the end of a vector.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'v.push_back(___);',
    answer: '5',
  },
  {
    srNo: 111,
    id: 'cr-cpp-medium-09',
    title: 'Reference Parameter',
    description: 'Pass a variable by reference to a function.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'void myFunc(int___ x) { }',
    answer: '&',
  },
  {
    srNo: 112,
    id: 'cr-cpp-hard-09',
    title: 'RAII with unique_ptr',
    description: 'Use a smart pointer to manage memory automatically.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'std::___<MyClass> ptr = std::make_unique<MyClass>();',
    answer: 'unique_ptr',
  },
  {
    srNo: 113,
    id: 'cr-js-easy-16',
    title: 'Math Round',
    description: 'Round a number to the nearest integer.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'const rounded = Math.___ (4.7);',
    answer: 'round',
  },
  {
    srNo: 114,
    id: 'cr-js-medium-16',
    title: 'Add to Start of Array',
    description: 'Add one or more elements to the beginning of an array.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'arr.___("Lemon", "Pineapple");',
    answer: 'unshift',
  },
  {
    srNo: 115,
    id: 'cr-js-hard-09',
    title: 'Set Data Structure',
    description: 'Create a new Set from an array to get unique values.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'const unique = new ___ ([1, 1, 2, 2, 3]);',
    answer: 'Set',
  },
  {
    srNo: 116,
    id: 'cr-py-easy-11',
    title: 'List Remove',
    description: 'Remove an item from a list by its value.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'my_list.___("banana")',
    answer: 'remove',
  },
  {
    srNo: 117,
    id: 'cr-py-medium-11',
    title: 'Dictionary Values',
    description: 'Get all values from a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'for x in my_dict.___():\n  print(x)',
    answer: 'values',
  },
  {
    srNo: 118,
    id: 'cr-py-hard-09',
    title: 'Async/Await',
    description: 'Define and run a simple asynchronous function.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '___ def main():\n  await asyncio.sleep(1)',
    answer: 'async',
  },
  {
    srNo: 119,
    id: 'cr-java-easy-11',
    title: 'Array Index Access',
    description: 'Access the third element in an array.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'int x = myArray[___];',
    answer: '2',
  },
  {
    srNo: 120,
    id: 'cr-java-medium-10',
    title: 'Interface Keyword',
    description: 'Declare an interface.',
    language: 'java',
    difficulty: 'Medium',
    snippet: '___ Animal { ... }',
    answer: 'interface',
  },
  {
    srNo: 121,
    id: 'cr-java-hard-10',
    title: 'Stream API Collect',
    description: 'Collect the results of a stream operation into a List.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'list.stream().filter(...).___(Collectors.toList());',
    answer: 'collect',
  },
  {
    srNo: 122,
    id: 'cr-cpp-easy-11',
    title: 'End Line',
    description: 'End a line and flush the output stream.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'std::cout << "Hello" << std::___;',
    answer: 'endl',
  },
  {
    srNo: 123,
    id: 'cr-cpp-medium-11',
    title: 'Struct Keyword',
    description: 'Define a simple structure.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: '___ Point { int x; int y; };',
    answer: 'struct',
  },
  {
    srNo: 124,
    id: 'cr-cpp-hard-11',
    title: 'Lambda Function',
    description: 'Define a simple lambda function.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'auto func = ___() { std::cout << "Hi"; };',
    answer: '[]',
  }
];

export function getCodeRushChallengeById(id: string): CodeRushChallenge | undefined {
  return codeRushChallenges.find((c) => c.id === id);
}

export function getNextCodeRushChallengeId(currentId: string): string | null {
    const currentIndex = codeRushChallenges.findIndex(c => c.id === currentId);
    if (currentIndex === -1 || currentIndex >= codeRushChallenges.length - 1) {
        return null;
    }
    return codeRushChallenges[currentIndex + 1].id;
}
