
export interface CodeRushChallenge {
  srNo: number;
  id: string;
  title: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  snippet: string; // e.g., "for (let i = 0; i < ___; i++)"
  answer: string; // e.g., "5"
}

export const codeRushChallenges: CodeRushChallenge[] = [
  // JavaScript Easy
  {
    srNo: 1,
    id: 'cr-js-easy-01',
    title: 'Variable Declaration',
    description: 'Declare a variable named "count".',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: '___ count = 10;',
    answer: 'let',
  },
  {
    srNo: 2,
    id: 'cr-js-easy-02',
    title: 'If Statement',
    description: 'Complete the if statement condition.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'if (x ___ 5)',
    answer: '>',
  },
  {
    srNo: 3,
    id: 'cr-js-easy-03',
    title: 'Function Keyword',
    description: 'Define a function named "myFunction".',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: '___ myFunction() { }',
    answer: 'function',
  },
  {
    srNo: 4,
    id: 'cr-js-easy-04',
    title: 'Logging to Console',
    description: 'Log a message to the console.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'console.___("Hello");',
    answer: 'log',
  },
  {
    srNo: 5,
    id: 'cr-js-easy-05',
    title: 'Strict Equality',
    description: 'Check if two values are strictly equal.',
    language: 'javascript',
    difficulty: 'Easy',
    snippet: 'if (a ___ b)',
    answer: '===',
  },

  // JavaScript Medium
  {
    srNo: 6,
    id: 'cr-js-medium-01',
    title: 'For...of Loop',
    description: 'Iterate over an array.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'for (const item ___ myArray) { }',
    answer: 'of',
  },
  {
    srNo: 7,
    id: 'cr-js-medium-02',
    title: 'Arrow Function',
    description: 'Define a simple arrow function.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const add = (a, b) ___ a + b;',
    answer: '=>',
  },
    {
    srNo: 8,
    id: 'cr-js-medium-03',
    title: 'Array Filter',
    description: 'Filter an array for even numbers.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const evens = arr.filter(n => n % 2 ___ 0);',
    answer: '===',
  },
  {
    srNo: 9,
    id: 'cr-js-medium-04',
    title: 'Ternary Operator',
    description: 'Use a ternary operator for a simple condition.',
    language: 'javascript',
    difficulty: 'Medium',
    snippet: 'const type = age >= 18 ___ "adult" : "minor";',
    answer: '?',
  },

  // JavaScript Hard
  {
    srNo: 10,
    id: 'cr-js-hard-01',
    title: 'Async/Await',
    description: 'Wait for a promise to resolve.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'const data = ___ response.json();',
    answer: 'await',
  },
  {
    srNo: 11,
    id: 'cr-js-hard-02',
    title: 'Array Reduce',
    description: 'Complete the reduce function to sum an array.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: 'arr.reduce((acc, curr) => acc + curr, ___);',
    answer: '0',
  },
  {
    srNo: 12,
    id: 'cr-js-hard-03',
    title: 'Promise.all',
    description: 'Wait for multiple promises to resolve.',
    language: 'javascript',
    difficulty: 'Hard',
    snippet: '___([promise1, promise2]);',
    answer: 'Promise.all',
  },

  // Python Easy
  {
    srNo: 13,
    id: 'cr-py-easy-01',
    title: 'Function Definition',
    description: 'Define a function in Python.',
    language: 'python',
    difficulty: 'Easy',
    snippet: '___ my_func():',
    answer: 'def',
  },
  {
    srNo: 14,
    id: 'cr-py-easy-02',
    title: 'For Loop Range',
    description: 'Loop from 0 to 9.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'for i in ___(10):',
    answer: 'range',
  },
  {
    srNo: 15,
    id: 'cr-py-easy-03',
    title: 'Else Statement',
    description: 'Add the else block to an if statement.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if x > 0:\n  print("Positive")\n___:\n  print("Not positive")',
    answer: 'else',
  },
  {
    srNo: 16,
    id: 'cr-py-easy-04',
    title: 'Check for membership',
    description: 'Check if an item exists in a list.',
    language: 'python',
    difficulty: 'Easy',
    snippet: 'if "apple" ___ my_list:',
    answer: 'in',
  },

  // Python Medium
  {
    srNo: 17,
    id: 'cr-py-medium-01',
    title: 'Import Module',
    description: 'Import the math module.',
    language: 'python',
    difficulty: 'Medium',
    snippet: '___ math',
    answer: 'import',
  },
  {
    srNo: 18,
    id: 'cr-py-medium-02',
    title: 'List Append',
    description: 'Add an item to a list.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'my_list.___(4)',
    answer: 'append',
  },
  {
    srNo: 19,
    id: 'cr-py-medium-03',
    title: 'Lambda Function',
    description: 'Create a simple lambda function.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'x = ___ a : a + 10',
    answer: 'lambda',
  },
  {
    srNo: 20,
    id: 'cr-py-medium-04',
    title: 'Class Constructor',
    description: 'Define the constructor for a Python class.',
    language: 'python',
    difficulty: 'Medium',
    snippet: 'def ___ (self):\n  pass',
    answer: '__init__',
  },

  // Python Hard
  {
    srNo: 21,
    id: 'cr-py-hard-01',
    title: 'List Comprehension',
    description: 'Complete the list comprehension.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '[x*x ___ x in range(5)]',
    answer: 'for',
  },
    {
    srNo: 22,
    id: 'cr-py-hard-02',
    title: 'Decorator Syntax',
    description: 'Apply a decorator to a function.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '___my_decorator\ndef say_hello():\n  pass',
    answer: '@',
  },
  {
    srNo: 23,
    id: 'cr-py-hard-03',
    title: 'Context Manager',
    description: 'Open a file using a context manager.',
    language: 'python',
    difficulty: 'Hard',
    snippet: '___ open("file.txt", "r") as f:',
    answer: 'with',
  },
    
  // Java Easy
  {
    srNo: 24,
    id: 'cr-java-easy-01',
    title: 'Main Method',
    description: 'Define the main method entry point.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'public ___ void main(String[] args)',
    answer: 'static',
  },
  {
    srNo: 25,
    id: 'cr-java-easy-02',
    title: 'New Instance',
    description: 'Create a new object instance.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'String myString = ___ String();',
    answer: 'new',
  },
  {
    srNo: 26,
    id: 'cr-java-easy-03',
    title: 'System Output',
    description: 'Print a line to the console.',
    language: 'java',
    difficulty: 'Easy',
    snippet: 'System.out.___("Hello");',
    answer: 'println',
  },
  {
    srNo: 27,
    id: 'cr-java-easy-04',
    title: 'For Loop',
    description: 'Complete the for loop syntax.',
    language: 'java',
    difficulty: 'Easy',
    snippet: '___ (int i = 0; i < 5; i++)',
    answer: 'for',
  },

  // Java Medium
  {
    srNo: 28,
    id: 'cr-java-medium-01',
    title: 'Import Statement',
    description: 'Import the ArrayList class.',
    language: 'java',
    difficulty: 'Medium',
    snippet: '___ java.util.ArrayList;',
    answer: 'import',
  },
  {
    srNo: 29,
    id: 'cr-java-medium-02',
    title: 'Class Inheritance',
    description: 'Make a class inherit from another.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'class Dog ___ Animal { }',
    answer: 'extends',
  },
  {
    srNo: 30,
    id: 'cr-java-medium-03',
    title: 'Interface Implementation',
    description: 'Make a class implement an interface.',
    language: 'java',
    difficulty: 'Medium',
    snippet: 'class Car ___ Drivable { }',
    answer: 'implements',
  },

  // Java Hard
  {
    srNo: 31,
    id: 'cr-java-hard-01',
    title: 'Exception Handling',
    description: 'Catch an exception.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'try { ... } ___ (Exception e) { ... }',
    answer: 'catch',
  },
  {
    srNo: 32,
    id: 'cr-java-hard-02',
    title: 'Override Annotation',
    description: 'Mark a method as an override.',
    language: 'java',
    difficulty: 'Hard',
    snippet: '___ \npublic String toString() { ... }',
    answer: '@Override',
  },
  {
    srNo: 33,
    id: 'cr-java-hard-03',
    title: 'Thread-safe method',
    description: 'Mark a method as thread-safe.',
    language: 'java',
    difficulty: 'Hard',
    snippet: 'public ___ void myMethod() { ... }',
    answer: 'synchronized',
  },

  // C++ Easy
  {
    srNo: 34,
    id: 'cr-cpp-easy-01',
    title: 'Include Directive',
    description: 'Include the iostream library.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '___ <iostream>',
    answer: '#include',
  },
  {
    srNo: 35,
    id: 'cr-cpp-easy-02',
    title: 'Standard Output',
    description: 'Print to the console.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: 'std::___ << "Hello";',
    answer: 'cout',
  },
  {
    srNo: 36,
    id: 'cr-cpp-easy-03',
    title: 'Using Namespace',
    description: 'Use the standard namespace.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '___ namespace std;',
    answer: 'using',
  },
  {
    srNo: 37,
    id: 'cr-cpp-easy-04',
    title: 'Main function return',
    description: 'End the main function successfully.',
    language: 'cpp',
    difficulty: 'Easy',
    snippet: '___ 0;',
    answer: 'return',
  },

  // C++ Medium
  {
    srNo: 38,
    id: 'cr-cpp-medium-01',
    title: 'Pointer Declaration',
    description: 'Declare a pointer to an integer.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int___ p;',
    answer: '*',
  },
  {
    srNo: 39,
    id: 'cr-cpp-medium-02',
    title: 'Dynamic Memory Allocation',
    description: 'Allocate an integer on the heap.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'int* p = ___ int;',
    answer: 'new',
  },
  {
    srNo: 40,
    id: 'cr-cpp-medium-03',
    title: 'Vector push_back',
    description: 'Add an element to a vector.',
    language: 'cpp',
    difficulty: 'Medium',
    snippet: 'my_vector.___ (10);',
    answer: 'push_back',
  },
  
  // C++ Hard
  {
    srNo: 41,
    id: 'cr-cpp-hard-01',
    title: 'Virtual Function',
    description: 'Declare a virtual function for polymorphism.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: '___ void my_func() = 0;',
    answer: 'virtual',
  },
  {
    srNo: 42,
    id: 'cr-cpp-hard-02',
    title: 'Template Declaration',
    description: 'Declare a function template.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: '___<typename T>',
    answer: 'template',
  },
  {
    srNo: 43,
    id: 'cr-cpp-hard-03',
    title: 'Deallocate Array',
    description: 'Deallocate an array from the heap.',
    language: 'cpp',
    difficulty: 'Hard',
    snippet: 'delete___ arr;',
    answer: '[]',
  }
];

export function getCodeRushChallengeById(id: string): CodeRushChallenge | undefined {
  return codeRushChallenges.find((c) => c.id === id);
}

export function getNextCodeRushChallengeId(currentId: string): string | null {
    const currentIndex = codeRushChallenges.findIndex(c => c.id === currentId);
    if (currentIndex === -1 || currentIndex >= codeRushChallenges.length - 1) {
        return null;
    }
    return codeRushChallenges[currentIndex + 1].id;
}
