
export interface ConceptMatchChallenge {
  srNo: number;
  id: string;
  concept: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  options: string[]; // Array of code snippets
  correctAnswer: string; // The correct code snippet
  explanation: string;
}

export const conceptMatchChallenges: ConceptMatchChallenge[] = [
  // JavaScript - Easy
  {
    srNo: 1,
    id: 'cm-js-easy-01',
    concept: 'Variable Declaration (let)',
    description: 'Which snippet correctly declares a variable that can be reassigned?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'const name = "Alice";',
      'let score = 100;',
      'variable user = "Bob";',
      'static String title = "Page";',
    ],
    correctAnswer: 'let score = 100;',
    explanation: 'In modern JavaScript, `let` is used to declare variables that can be reassigned. `const` is for variables that cannot be reassigned.',
  },
  {
    srNo: 2,
    id: 'cm-js-easy-02',
    concept: 'Arrow Function',
    description: 'Which snippet shows the correct syntax for a simple arrow function?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'function add(a, b) => a + b;',
      'const add = (a, b) => a + b;',
      'const add = function(a, b) => a + b;',
      'def add = (a, b) => a + b;',
    ],
    correctAnswer: 'const add = (a, b) => a + b;',
    explanation: 'Arrow function syntax uses `=>` to separate the parameters from the function body. For a single return expression, curly braces are not needed.',
  },
  {
    srNo: 3,
    id: 'cm-js-easy-03',
    concept: 'Strict Equality',
    description: 'Which snippet correctly checks if two values are equal in both value and type?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'if (a == b)',
      'if (a === b)',
      'if (a = b)',
      'if (a equals b)',
    ],
    correctAnswer: 'if (a === b)',
    explanation: 'The strict equality operator `===` checks for equality without performing type coercion, meaning both the value and the type must be the same.',
  },
  {
    srNo: 4,
    id: 'cm-js-easy-04',
    concept: 'Array `push` Method',
    description: 'Which snippet correctly adds an element to the end of an array?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'myArray.add("new_item");',
      'myArray.append("new_item");',
      'myArray.push("new_item");',
      'myArray[myArray.length] = "new_item";',
    ],
    correctAnswer: 'myArray.push("new_item");',
    explanation: 'The `push()` method is the standard way to add one or more elements to the end of an array in JavaScript.',
  },
  {
    srNo: 5,
    id: 'cm-js-easy-05',
    concept: 'Object Property Access',
    description: 'Which snippet correctly accesses the `model` property of the `car` object?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'car.model',
      'car["model"]',
      'car(model)',
      'get(car, "model")',
    ],
    correctAnswer: 'car.model',
    explanation: 'Dot notation (`object.property`) is a common and direct way to access the properties of an object.',
  },

  // JavaScript - Medium
  {
    srNo: 6,
    id: 'cm-js-medium-01',
    concept: 'Array `map` method',
    description: 'Which snippet correctly creates a new array with the doubled values of the original?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'numbers.forEach(num => num * 2);',
      'const doubled = numbers.map(num => num * 2);',
      'for (let num of numbers) { num * 2; }',
      'const doubled = numbers.reduce(num => num * 2);',
    ],
    correctAnswer: 'const doubled = numbers.map(num => num * 2);',
    explanation: 'The `map` method creates a new array populated with the results of calling a provided function on every element in the calling array.',
  },
  {
    srNo: 7,
    id: 'cm-js-medium-02',
    concept: 'Destructuring Assignment',
    description: 'Which snippet correctly extracts the `name` and `age` from the person object?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'let { name, age } = person;',
      'let [name, age] = person;',
      'let name = person.name, age = person.age;',
      'let person = {name, age};',
    ],
    correctAnswer: 'let { name, age } = person;',
    explanation: 'Object destructuring provides a concise way to extract properties from objects and bind them to variables.',
  },
  {
    srNo: 8,
    id: 'cm-js-medium-03',
    concept: 'Ternary Operator',
    description: 'Which snippet correctly assigns a value based on a condition?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'let type = if (age >= 18) "adult" else "minor";',
      'let type = age >= 18 ? "adult" : "minor";',
      'let type = age >= 18 ("adult") || ("minor");',
      'let type = age.isAdult() ? "adult" : "minor";',
    ],
    correctAnswer: 'let type = age >= 18 ? "adult" : "minor";',
    explanation: 'The conditional (ternary) operator is the only JavaScript operator that takes three operands: a condition followed by a question mark (?), then an expression to execute if the condition is truthy followed by a colon (:), and finally the expression to execute if the condition is falsy.',
  },

  // JavaScript - Hard
  {
    srNo: 9,
    id: 'cm-js-hard-01',
    concept: 'Promise',
    description: 'Which snippet correctly creates a promise that resolves after a short delay?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const promise = new Promise((resolve) => setTimeout(resolve, 100));',
      'const promise = setTimeout(() => Promise.resolve(), 100);',
      'const promise = await setTimeout(100);',
      'const promise = async () => { await 100; };',
    ],
    correctAnswer: 'const promise = new Promise((resolve) => setTimeout(resolve, 100));',
    explanation: 'The `Promise` constructor takes a function (an executor) that is passed `resolve` and `reject` functions. Asynchronous operations like `setTimeout` are placed inside the executor.',
  },
  {
    srNo: 10,
    id: 'cm-js-hard-02',
    concept: 'Closure',
    description: 'Which snippet demonstrates a closure where an inner function has access to the outer function\'s variables?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'function outer() { let a = 1; function inner() { return a; } }',
      'function outer() { let a = 1; } function inner() { return a; }',
      'function outer() { let a = 1; return function inner() { return a; } }',
      'function outer(a) { function inner() { return a; } }',
    ],
    correctAnswer: 'function outer() { let a = 1; return function inner() { return a; } }',
    explanation: 'A closure is the combination of a function bundled together (enclosed) with references to its surrounding state (the lexical environment). The inner function "closes over" the variable `a` from the outer function\'s scope.',
  },
  {
    srNo: 11,
    id: 'cm-js-easy-06',
    concept: 'Template Literals',
    description: 'Which snippet uses template literals to embed a variable in a string?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'console.log("Name: " + name);',
      'console.log(`Name: ${name}`);',
      'console.log("Name: %s", name);',
      'console.log("Name: ", name);',
    ],
    correctAnswer: 'console.log(`Name: ${name}`);',
    explanation: 'Template literals use backticks (``) and allow for embedded expressions using `${...}` syntax for cleaner string formatting.',
  },
  {
    srNo: 12,
    id: 'cm-js-easy-07',
    concept: 'If-Else Statement',
    description: 'Which snippet correctly checks if a number is positive, negative, or zero?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'if (x > 0) {} else if (x < 0) {} else {}',
      'if (x > 0); else if (x < 0); else;',
      'switch (x) { case > 0: ... }',
      'if (x > 0) then {}',
    ],
    correctAnswer: 'if (x > 0) {} else if (x < 0) {} else {}',
    explanation: 'The standard `if...else if...else` structure is used for multi-way conditional branching.',
  },
  {
    srNo: 13,
    id: 'cm-js-easy-08',
    concept: 'For Loop',
    description: 'Which snippet correctly loops from 0 up to (but not including) 5?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'for (let i = 0; i <= 5; i++)',
      'for (let i = 1; i < 5; i++)',
      'for (let i = 0; i < 5; i++)',
      'for (let i = 0; i < 5; i--)',
    ],
    correctAnswer: 'for (let i = 0; i < 5; i++)',
    explanation: 'A standard for loop initializes a counter (`let i = 0`), sets a condition to continue (`i < 5`), and defines an increment step (`i++`).',
  },
  {
    srNo: 14,
    id: 'cm-js-easy-09',
    concept: 'Adding an Event Listener',
    description: 'Which snippet is the correct way to listen for a click event on a button?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'button.onClick = function() { ... }',
      'button.addEventListener("click", function() { ... })',
      'button.attachEvent("onclick", function() { ... })',
      'button.listen("click", function() { ... })',
    ],
    correctAnswer: 'button.addEventListener("click", function() { ... })',
    explanation: '`addEventListener` is the modern, standard method for attaching event handlers to elements without overwriting existing handlers.',
  },
  {
    srNo: 15,
    id: 'cm-js-easy-10',
    concept: 'Creating an Object',
    description: 'Which snippet correctly creates a JavaScript object?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'let car = ["Ford", "Mustang"];',
      'let car = "Ford";',
      'let car = {brand: "Ford", model: "Mustang"};',
      'let car = new Object(brand="Ford");',
    ],
    correctAnswer: 'let car = {brand: "Ford", model: "Mustang"};',
    explanation: 'Object literals, using curly braces `{}`, are the most common and concise way to create objects in JavaScript.',
  },
  {
    srNo: 16,
    id: 'cm-js-medium-04',
    concept: 'Array `filter` Method',
    description: 'Which snippet correctly creates a new array containing only numbers greater than 10?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'const filtered = numbers.filter(n => n > 10);',
      'const filtered = numbers.map(n => n > 10);',
      'const filtered = numbers.forEach(n => n > 10);',
      'const filtered = numbers.reduce(n => n > 10);',
    ],
    correctAnswer: 'const filtered = numbers.filter(n => n > 10);',
    explanation: 'The `filter` method creates a new array with all elements that pass the test implemented by the provided function.',
  },
  {
    srNo: 17,
    id: 'cm-js-medium-05',
    concept: 'Async/Await',
    description: 'Which snippet correctly fetches data from an API using async/await?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'async function getData() { return fetch(url); }',
      'function getData() { return await fetch(url); }',
      'async function getData() { const res = await fetch(url); return await res.json(); }',
      'async function getData() { const res = fetch(url); return res.json(); }',
    ],
    correctAnswer: 'async function getData() { const res = await fetch(url); return await res.json(); }',
    explanation: 'The `async` keyword defines an asynchronous function, and `await` is used to pause execution and wait for a Promise to resolve before continuing.',
  },
  {
    srNo: 18,
    id: 'cm-js-medium-06',
    concept: 'Spread Operator (Arrays)',
    description: 'Which snippet correctly merges two arrays into a new one?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'const merged = arr1.concat(arr2);',
      'const merged = [...arr1, ...arr2];',
      'const merged = arr1 + arr2;',
      'const merged = Object.assign([], arr1, arr2);',
    ],
    correctAnswer: 'const merged = [...arr1, ...arr2];',
    explanation: 'The spread syntax `...` allows an iterable such as an array to be expanded in places where zero or more arguments or elements are expected.',
  },
  {
    srNo: 19,
    id: 'cm-js-medium-07',
    concept: '`this` in a Method',
    description: 'Which snippet correctly refers to the object\'s own property inside a method?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'const obj = { prop: "A", get: function() { return prop; } }',
      'const obj = { prop: "A", get: function() { return obj.prop; } }',
      'const obj = { prop: "A", get: function() { return this.prop; } }',
      'const obj = { prop: "A", get: function() { return self.prop; } }',
    ],
    correctAnswer: 'const obj = { prop: "A", get: function() { return this.prop; } }',
    explanation: 'Inside an object method (defined with `function`), `this` refers to the object the method was called on.',
  },
  {
    srNo: 20,
    id: 'cm-js-medium-08',
    concept: 'Array `reduce` Method',
    description: 'Which snippet correctly calculates the sum of all numbers in an array?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'numbers.reduce((acc, val) => acc + val, 0);',
      'numbers.sum();',
      'numbers.forEach(sum += n);',
      'for(n in numbers) sum += n;',
    ],
    correctAnswer: 'numbers.reduce((acc, val) => acc + val, 0);',
    explanation: 'The `reduce` method executes a user-supplied "reducer" callback function on each element of the array, passing in the return value from the calculation on the preceding element.',
  },
  {
    srNo: 21,
    id: 'cm-js-hard-03',
    concept: 'Class and Inheritance',
    description: 'Which snippet correctly shows a `Dog` class inheriting from an `Animal` class?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'class Dog extends Animal { constructor() { super(); } }',
      'class Dog inherits Animal { }',
      'class Dog: Animal { }',
      'class Dog implements Animal { }',
    ],
    correctAnswer: 'class Dog extends Animal { constructor() { super(); } }',
    explanation: 'The `extends` keyword is used in class declarations to create a class as a child of another class. The `super()` keyword is used to call the constructor of the parent class.',
  },
  {
    srNo: 22,
    id: 'cm-js-hard-04',
    concept: 'Generator Function',
    description: 'Which snippet defines a function that can pause its execution and yield multiple values?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'async function* myGenerator() { await 1; yield 2; }',
      'function* myGenerator() { yield 1; yield 2; }',
      'function myGenerator() { return [1, 2]; }',
      'function myGenerator() { pause; yield 1; }',
    ],
    correctAnswer: 'function* myGenerator() { yield 1; yield 2; }',
    explanation: 'Generator functions are declared with `function*` syntax and use the `yield` keyword to produce a sequence of values.',
  },
  {
    srNo: 23,
    id: 'cm-js-hard-05',
    concept: '`Promise.all`',
    description: 'Which snippet correctly waits for multiple promises to resolve?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'await Promise.all([p1, p2]);',
      'await Promises.all(p1, p2);',
      'Promise.awaitAll([p1, p2]);',
      'await [p1, p2];',
    ],
    correctAnswer: 'await Promise.all([p1, p2]);',
    explanation: '`Promise.all()` takes an iterable of promises and returns a single Promise that resolves when all of the promises in the iterable have resolved.',
  },
  {
    srNo: 24,
    id: 'cm-js-hard-06',
    concept: 'Module Export',
    description: 'Which snippet correctly exports a function as the default export in an ES module?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'export default function myFunc() { ... }',
      'module.exports = function myFunc() { ... }',
      'exports.default = function myFunc() { ... }',
      'return function myFunc() { ... }',
    ],
    correctAnswer: 'export default function myFunc() { ... }',
    explanation: 'The `export default` syntax is used in ES modules to export a single value (a function, class, or object) as the default export from that module.',
  },
  {
    srNo: 25,
    id: 'cm-js-hard-07',
    concept: '`Proxy` Object',
    description: 'Which snippet creates a proxy to intercept property access on an object?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const proxy = new Proxy(target, { get(t, p) { ... } });',
      'const proxy = target.toProxy({ get(t, p) { ... } });',
      'const proxy = new Interceptor(target, { get(t, p) { ... } });',
      'const proxy = Proxy.create(target, { get(t, p) { ... } });',
    ],
    correctAnswer: 'const proxy = new Proxy(target, { get(t, p) { ... } });',
    explanation: 'The `Proxy` object enables you to create a proxy for another object, which can intercept and redefine fundamental operations for that object, such as property lookup.',
  },
  {
    srNo: 26,
    id: 'cm-js-hard-08',
    concept: '`Map` Data Structure',
    description: 'Which snippet correctly creates and uses a Map?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const map = { key: "value" };',
      'const map = new Map(); map.set("key", "value");',
      'const map = new ArrayMap(); map.add("key", "value");',
      'const map = createMap(); map.key = "value";',
    ],
    correctAnswer: 'const map = new Map(); map.set("key", "value");',
    explanation: 'The `Map` object holds key-value pairs and remembers the original insertion order of the keys. Any value (both objects and primitive values) may be used as either a key or a value.',
  },
  {
    srNo: 27,
    id: 'cm-js-hard-09',
    concept: '`Set` Data Structure',
    description: 'Which snippet correctly creates a Set and adds a value?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const set = [1, 2, 3];',
      'const set = new Set(); set.add(1);',
      'const set = {}; set.add(1);',
      'const set = new UniqueArray(); set.push(1);',
    ],
    correctAnswer: 'const set = new Set(); set.add(1);',
    explanation: 'The `Set` object lets you store unique values of any type, whether primitive values or object references.',
  },
  {
    srNo: 28,
    id: 'cm-js-hard-10',
    concept: 'Web Worker Instantiation',
    description: 'Which snippet correctly creates a new web worker?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const worker = new Worker("worker.js");',
      'const worker = createWorker("worker.js");',
      'const worker = new Thread("worker.js");',
      'const worker = new WebWorker("worker.js");',
    ],
    correctAnswer: 'const worker = new Worker("worker.js");',
    explanation: 'The `Worker()` constructor creates a `Worker` object that executes the script at the specified URL. This script must obey the same-origin policy.',
  },
  {
    srNo: 29,
    id: 'cm-js-easy-11',
    concept: 'Array `indexOf`',
    description: 'Which snippet correctly finds the index of "Banana"?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'fruits.indexOf("Banana");',
      'fruits.find("Banana");',
      'fruits.search("Banana");',
      'fruits.index("Banana");',
    ],
    correctAnswer: 'fruits.indexOf("Banana");',
    explanation: 'The `indexOf()` method returns the first index at which a given element can be found in the array, or -1 if it is not present.',
  },
  {
    srNo: 30,
    id: 'cm-js-easy-12',
    concept: 'String `toUpperCase`',
    description: 'Which snippet converts a string to all uppercase letters?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'str.toUpperCase();',
      'str.toUpper();',
      'str.upper();',
      'str.upperCase();',
    ],
    correctAnswer: 'str.toUpperCase();',
    explanation: 'The `toUpperCase()` method returns the calling string value converted to uppercase.',
  },
  {
    srNo: 31,
    id: 'cm-js-easy-13',
    concept: '`Math.random`',
    description: 'Which snippet generates a random number between 0 and 1?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'Math.rand();',
      'Math.random();',
      'random();',
      'new Random();',
    ],
    correctAnswer: 'Math.random();',
    explanation: 'The `Math.random()` function returns a floating-point, pseudo-random number in the range from 0 inclusive up to but not including 1.',
  },
  {
    srNo: 32,
    id: 'cm-js-medium-09',
    concept: 'Array `slice`',
    description: 'Which snippet extracts a portion of an array into a new array?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'fruits.slice(1, 3);',
      'fruits.splice(1, 3);',
      'fruits.cut(1, 3);',
      'fruits.subset(1, 3);',
    ],
    correctAnswer: 'fruits.slice(1, 3);',
    explanation: 'The `slice()` method returns a shallow copy of a portion of an array into a new array object selected from `start` to `end` (`end` not included). The original array will not be modified.',
  },
  {
    srNo: 33,
    id: 'cm-js-medium-10',
    concept: 'Array `splice`',
    description: 'Which snippet changes the contents of an array by removing or replacing existing elements?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'fruits.slice(2, 0, "Lemon");',
      'fruits.splice(2, 0, "Lemon");',
      'fruits.add(2, "Lemon");',
      'fruits.insert(2, "Lemon");',
    ],
    correctAnswer: 'fruits.splice(2, 0, "Lemon");',
    explanation: 'The `splice()` method changes the contents of an array by removing or replacing existing elements and/or adding new elements in place.',
  },
  {
    srNo: 34,
    id: 'cm-js-medium-11',
    concept: '`JSON.stringify`',
    description: 'Which snippet converts a JavaScript object into a JSON string?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'JSON.stringify(obj);',
      'JSON.toString(obj);',
      'obj.toJSON();',
      'obj.toString();',
    ],
    correctAnswer: 'JSON.stringify(obj);',
    explanation: 'The `JSON.stringify()` method converts a JavaScript object or value to a JSON string.',
  },
  {
    srNo: 35,
    id: 'cm-js-medium-12',
    concept: '`JSON.parse`',
    description: 'Which snippet parses a JSON string, constructing the JavaScript value or object described by the string?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'JSON.parse(jsonString);',
      'JSON.toObject(jsonString);',
      'jsonString.parse();',
      'Object.fromJSON(jsonString);',
    ],
    correctAnswer: 'JSON.parse(jsonString);',
    explanation: 'The `JSON.parse()` method parses a JSON string, constructing the JavaScript value or object described by the string.',
  },
  {
    srNo: 36,
    id: 'cm-js-hard-11',
    concept: 'Symbol',
    description: 'Which snippet creates a unique and immutable data type, often used as an identifier for object properties?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const sym = new Symbol("id");',
      'const sym = Symbol("id");',
      'const sym = "Symbol(id)";',
      'const sym = createSymbol("id");',
    ],
    correctAnswer: 'const sym = Symbol("id");',
    explanation: 'A `Symbol` is a primitive data type. The `Symbol()` function returns a new unique symbol value. You do not use `new` with `Symbol()`.',
  },
  {
    srNo: 37,
    id: 'cm-js-hard-12',
    concept: 'WeakMap',
    description: 'Which snippet creates a collection of key/value pairs in which the keys are weakly referenced?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const wm = new WeakMap();',
      'const wm = new Map({weak: true});',
      'const wm = new WeakReferenceMap();',
      'const wm = new Map.weak();',
    ],
    correctAnswer: 'const wm = new WeakMap();',
    explanation: 'The keys of a `WeakMap` must be objects. The references to the keys are held "weakly," meaning they do not prevent garbage collection if there is no other reference to the object.',
  },
  {
    srNo: 38,
    id: 'cm-js-hard-13',
    concept: 'Promise.race',
    description: 'Which snippet returns a promise that fulfills or rejects as soon as one of the promises in an iterable fulfills or rejects?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'Promise.any([p1, p2]);',
      'Promise.all([p1, p2]);',
      'Promise.first([p1, p2]);',
      'Promise.race([p1, p2]);',
    ],
    correctAnswer: 'Promise.race([p1, p2]);',
    explanation: '`Promise.race()` is useful when you want to get the result from the first asynchronous task to complete.',
  },

  // Python - Easy
  {
    srNo: 39,
    id: 'cm-py-easy-01',
    concept: 'F-String Formatting',
    description: 'Which snippet correctly formats a string using an f-string?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'print("Name: {name}")',
      'print(f"Name: {name}")',
      'print("Name: %s" % name)',
      'print("Name: " + name)',
    ],
    correctAnswer: 'print(f"Name: {name}")',
    explanation: 'F-strings (formatted string literals) provide a concise and convenient way to embed Python expressions inside string literals for formatting.',
  },
  {
    srNo: 40,
    id: 'cm-py-easy-02',
    concept: 'List Append',
    description: 'Which snippet correctly adds an element to a list?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'my_list.add(4)',
      'my_list.push(4)',
      'my_list.insert(4)',
      'my_list.append(4)',
    ],
    correctAnswer: 'my_list.append(4)',
    explanation: 'The `append()` method is used to add a single item to the end of a list in Python.',
  },
  {
    srNo: 41,
    id: 'cm-py-easy-03',
    concept: 'Dictionary Access',
    description: 'Which snippet correctly accesses the value associated with the key "city"?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'person.get("city")',
      'person["city"]',
      'person.city',
      'person("city")',
    ],
    correctAnswer: 'person["city"]',
    explanation: 'In Python, dictionary values are accessed using square bracket notation with the key inside.',
  },
  {
    srNo: 42,
    id: 'cm-py-easy-04',
    concept: 'Function Definition',
    description: 'Which snippet correctly defines a function named `calculate_sum`?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'function calculate_sum(a, b):',
      'def calculate_sum(a, b):',
      'method calculate_sum(a, b):',
      'define calculate_sum(a, b):',
    ],
    correctAnswer: 'def calculate_sum(a, b):',
    explanation: 'The `def` keyword is used to define a function in Python, followed by the function name and parentheses for parameters.',
  },
  {
    srNo: 43,
    id: 'cm-py-easy-05',
    concept: 'Conditional `if` statement',
    description: 'Which snippet shows a correct if statement to check if a is greater than b?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'if a > b then',
      'if (a > b)',
      'if a > b:',
      'if a > b {}',
    ],
    correctAnswer: 'if a > b:',
    explanation: 'In Python, an `if` statement ends with a colon, and the code to be executed is indented on the next line.',
  },
  {
    srNo: 44,
    id: 'cm-py-easy-06',
    concept: 'Get String Length',
    description: 'Which snippet correctly finds the length of a string?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      's.length()',
      'len(s)',
      's.size()',
      'length(s)',
    ],
    correctAnswer: 'len(s)',
    explanation: 'The built-in `len()` function is used to get the number of items in a sequence, including the number of characters in a string.',
  },
  {
    srNo: 45,
    id: 'cm-py-easy-07',
    concept: 'For Loop',
    description: 'Which snippet correctly iterates through the items of a list named `fruits`?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'for fruit in fruits:',
      'for each fruit in fruits:',
      'loop fruit in fruits:',
      'for (fruit in fruits):',
    ],
    correctAnswer: 'for fruit in fruits:',
    explanation: 'The `for...in` syntax is used to iterate over the items of any sequence, such as a list or a string.',
  },
  {
    srNo: 46,
    id: 'cm-py-easy-11',
    concept: 'User Input',
    description: 'Which snippet correctly gets input from the user?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'name = input("Enter name: ")',
      'name = Console.read("Enter name: ")',
      'name = system.in("Enter name: ")',
      'name = get_input("Enter name: ")',
    ],
    correctAnswer: 'name = input("Enter name: ")',
    explanation: 'The `input()` function prompts the user for input and returns it as a string.',
  },
  {
    srNo: 47,
    id: 'cm-py-easy-12',
    concept: 'While Loop',
    description: 'Which snippet correctly creates a loop that runs as long as `i` is less than 5?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'while i < 5:',
      'while(i < 5)',
      'loop while i < 5:',
      'for i < 5:',
    ],
    correctAnswer: 'while i < 5:',
    explanation: 'A `while` loop statement in Python repeatedly executes a target statement as long as a given condition is true.',
  },
  {
    srNo: 48,
    id: 'cm-py-easy-13',
    concept: 'Tuple Creation',
    description: 'Which snippet correctly creates a tuple?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'my_tuple = (1, 2, 3)',
      'my_tuple = [1, 2, 3]',
      'my_tuple = {1, 2, 3}',
      'my_tuple = tuple{1, 2, 3}',
    ],
    correctAnswer: 'my_tuple = (1, 2, 3)',
    explanation: 'Tuples are created using parentheses `()` and are immutable, meaning their contents cannot be changed.',
  },
  {
    srNo: 49,
    id: 'cm-py-easy-14',
    concept: 'Set Creation',
    description: 'Which snippet correctly creates a set?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'my_set = {1, 2, 3}',
      'my_set = [1, 2, 3]',
      'my_set = (1, 2, 3)',
      'my_set = new Set({1, 2, 3})',
    ],
    correctAnswer: 'my_set = {1, 2, 3}',
    explanation: 'Sets are created using curly braces `{}`. They are unordered collections of unique items.',
  },
  {
    srNo: 50,
    id: 'cm-py-easy-15',
    concept: 'Importing a Module',
    description: 'Which snippet correctly imports the `math` module?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'import math',
      'include math',
      'require math',
      'using math',
    ],
    correctAnswer: 'import math',
    explanation: 'The `import` statement is used to make code from one module available in another.',
  },

  // Python - Medium
  {
    srNo: 51,
    id: 'cm-py-medium-01',
    concept: 'List Comprehension',
    description: 'Which snippet correctly creates a list of squares for even numbers from 0 to 9?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      '[x**2 for x in range(10) if x % 2 == 0]',
      '{x**2 for x in range(10) if x % 2 == 0}',
      'map(lambda x: x**2, filter(lambda x: x % 2 == 0, range(10)))',
      '[for x in range(10): if x % 2 == 0: x**2]',
    ],
    correctAnswer: '[x**2 for x in range(10) if x % 2 == 0]',
    explanation: 'List comprehensions offer a shorter syntax when you want to create a new list based on the values of an existing list, including conditional logic.',
  },
  {
    srNo: 52,
    id: 'cm-py-medium-02',
    concept: '`with` statement',
    description: 'Which snippet shows the correct and safest way to open and read a file?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'file = open("a.txt"); file.read(); file.close()',
      'try: file=open("a.txt"); file.read() finally: file.close()',
      'with open("a.txt") as file: file.read()',
      'read(open("a.txt"))',
    ],
    correctAnswer: 'with open("a.txt") as file: file.read()',
    explanation: 'The `with` statement ensures that the file is automatically closed even if errors occur, making it the preferred way to handle file I/O.',
  },
  {
    srNo: 53,
    id: 'cm-py-medium-03',
    concept: 'Lambda Function',
    description: 'Which snippet defines a small, anonymous function that doubles its input?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'def(x): return x * 2',
      'lambda x: x * 2',
      'anon x: x * 2',
      'function(x) => x * 2',
    ],
    correctAnswer: 'lambda x: x * 2',
    explanation: 'A `lambda` function is a small anonymous function that can take any number of arguments, but can only have one expression.',
  },
  {
    srNo: 54,
    id: 'cm-py-medium-04',
    concept: 'Dictionary `.get()` method',
    description: 'Which snippet safely gets a value from a dictionary, providing a default if the key does not exist?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'my_dict["key"] or "default"',
      'my_dict.get("key", "default")',
      'my_dict.try_get("key", "default")',
      'my_dict.fetch("key", "default")',
    ],
    correctAnswer: 'my_dict.get("key", "default")',
    explanation: 'The `.get()` method is used to access a dictionary value. It returns a default value (the second argument) if the specified key does not exist, avoiding a KeyError.',
  },
  {
    srNo: 55,
    id: 'cm-py-medium-11',
    concept: 'Slicing with a Step',
    description: 'Which snippet extracts every second element from a list?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'my_list[::2]',
      'my_list.step(2)',
      'my_list.slice(0, -1, 2)',
      'my_list[0, -1, 2]',
    ],
    correctAnswer: 'my_list[::2]',
    explanation: 'List slicing syntax `[start:stop:step]` allows for a third argument, `step`, to skip elements.',
  },
  {
    srNo: 56,
    id: 'cm-py-medium-12',
    concept: '`enumerate` Function',
    description: 'Which snippet correctly gets both the index and value during a loop?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'for i, val in enumerate(my_list):',
      'for i, val in my_list.indexed():',
      'for i in range(len(my_list)): val = my_list[i]',
      'for i, val in zip(range(len(my_list)), my_list):',
    ],
    correctAnswer: 'for i, val in enumerate(my_list):',
    explanation: 'The `enumerate()` function adds a counter to an iterable and returns it in a form of an enumerating object.',
  },
  {
    srNo: 57,
    id: 'cm-py-medium-13',
    concept: '`*args` in Function',
    description: 'Which snippet defines a function that can accept a variable number of positional arguments?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'def my_func(*args):',
      'def my_func(args[]):',
      'def my_func(...args):',
      'def my_func(any args):',
    ],
    correctAnswer: 'def my_func(*args):',
    explanation: 'The special `*args` syntax in function definitions is used to pass a variable-length, non-keyworded argument list.',
  },
  {
    srNo: 58,
    id: 'cm-py-medium-14',
    concept: '`**kwargs` in Function',
    description: 'Which snippet defines a function that can accept a variable number of keyword arguments?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'def my_func(**kwargs):',
      'def my_func(*kwargs):',
      'def my_func(map kwargs):',
      'def my_func(dict kwargs):',
    ],
    correctAnswer: 'def my_func(**kwargs):',
    explanation: 'The special `**kwargs` syntax in function definitions is used to pass a keyworded, variable-length argument list as a dictionary.',
  },
  {
    srNo: 59,
    id: 'cm-py-medium-15',
    concept: '`__init__` Method',
    description: 'Which snippet correctly defines the constructor for a class?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'def __init__(self):',
      'def __new__(self):',
      'def constructor(self):',
      'def class_init(self):',
    ],
    correctAnswer: 'def __init__(self):',
    explanation: 'The `__init__` method is a special method, often called a constructor, that is called when an object is created from a class and it allows the class to initialize the attributes of an object.',
  },

  // Python - Hard
  {
    srNo: 60,
    id: 'cm-py-hard-01',
    concept: 'Decorator',
    description: 'Which snippet correctly defines a simple decorator that wraps another function?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'def decorator(func): return func()',
      'def decorator(func): def wrapper(): print("Wrapped"); func(); return wrapper',
      '@decorator def my_func(): ...',
      'class Decorator: def __call__(self, func): ...',
    ],
    correctAnswer: 'def decorator(func): def wrapper(): print("Wrapped"); func(); return wrapper',
    explanation: 'A decorator is a function that takes another function as an argument, adds some functionality, and returns another function, all without altering the source code of the original function.',
  },
  {
    srNo: 61,
    id: 'cm-py-hard-02',
    concept: 'Generator Function',
    description: 'Which snippet defines a function that can pause and resume, yielding multiple values over time?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'def my_gen(): return [1, 2, 3]',
      'def my_gen(): yield 1; yield 2; yield 3',
      'def my_gen(): print(1); print(2); print(3)',
      'async def my_gen(): return 1, 2, 3',
    ],
    correctAnswer: 'def my_gen(): yield 1; yield 2; yield 3',
    explanation: 'A generator function uses the `yield` keyword to produce a sequence of values. It pauses execution after each yield and resumes from that point on the next call.',
  },
  {
    srNo: 62,
    id: 'cm-py-hard-03',
    concept: 'Class Inheritance',
    description: 'Which snippet correctly shows a `Car` class inheriting from a `Vehicle` class?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'class Car(Vehicle):',
      'class Car inherits Vehicle:',
      'class Car extends Vehicle:',
      'class Car from Vehicle:',
    ],
    correctAnswer: 'class Car(Vehicle):',
    explanation: 'In Python, inheritance is specified by placing the name of the parent class in parentheses after the child class name.',
  },
  {
    srNo: 63,
    id: 'cm-py-hard-04',
    concept: 'Exception Handling',
    description: 'Which snippet shows the correct way to catch a specific type of error?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'catch ValueError as e:',
      'try: ... except ValueError as e:',
      'except ValueError => e:',
      'on ValueError as e:',
    ],
    correctAnswer: 'try: ... except ValueError as e:',
    explanation: 'The `try...except` block is used for handling exceptions. A specific exception type, like `ValueError`, can be caught and assigned to a variable using the `as` keyword.',
  },
  {
    srNo: 64,
    id: 'cm-py-hard-11',
    concept: 'Context Manager (`with` statement)',
    description: 'Which dunder method must a class implement to be used in a `with` statement?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '`__enter__` and `__exit__`',
      '`__open__` and `__close__`',
      '`__start__` and `__end__`',
      '`__with__` and `__endwith__`',
    ],
    correctAnswer: '`__enter__` and `__exit__`',
    explanation: 'To create a context manager, a class must implement an `__enter__` method (called at the start of the `with` block) and an `__exit__` method (called at the end, handling cleanup).',
  },
  {
    srNo: 65,
    id: 'cm-py-hard-12',
    concept: 'Asyncio Coroutine',
    description: 'Which snippet correctly defines and runs a simple asynchronous coroutine?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'async def main(): ...; main()',
      'def main(): await ...; asyncio.run(main())',
      'async def main(): ...; asyncio.run(main())',
      'coroutine main(): ...; run(main())',
    ],
    correctAnswer: 'async def main(): ...; asyncio.run(main())',
    explanation: 'Coroutines are defined with `async def`. The `asyncio.run()` function is the main entry point for running an asyncio program.',
  },
  {
    srNo: 66,
    id: 'cm-py-hard-13',
    concept: '`@staticmethod`',
    description: 'Which snippet defines a method that belongs to the class but does not have access to the instance (`self`)?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '@staticmethod\ndef my_method(): ...',
      '@classmethod\ndef my_method(cls): ...',
      'def my_method(): ...',
      'static def my_method(): ...',
    ],
    correctAnswer: '@staticmethod\ndef my_method(): ...',
    explanation: 'A static method does not receive an implicit first argument. It is bound to the class and not the object of the class.',
  },
  {
    srNo: 67,
    id: 'cm-py-hard-14',
    concept: '`@classmethod`',
    description: 'Which snippet defines a method that receives the class itself as the first argument (`cls`)?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '@staticmethod\ndef my_method(): ...',
      '@classmethod\ndef my_method(cls): ...',
      'def my_method(self): ...',
      'class def my_method(): ...',
    ],
    correctAnswer: '@classmethod\ndef my_method(cls): ...',
    explanation: 'A class method receives the class as the implicit first argument, just like an instance method receives the instance. It is often used for factory methods that create instances of the class.',
  },
  {
    srNo: 68,
    id: 'cm-py-hard-15',
    concept: 'Metaclass',
    description: 'Which snippet correctly defines a simple metaclass?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'class MyMeta(type): ...',
      'class MyMeta(metaclass=type): ...',
      'meta MyMeta: ...',
      'class MyMeta(object): __metaclass__ = ...',
    ],
    correctAnswer: 'class MyMeta(type): ...',
    explanation: 'Metaclasses are classes whose instances are classes. A metaclass is created by inheriting from `type`.',
  },
  {
    srNo: 69,
    id: 'cm-py-easy-16',
    concept: '`isinstance` function',
    description: 'Which snippet checks if a variable is an integer?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'isinstance(x, int)',
      'type(x) == int',
      'x.is_integer()',
      'int.is(x)',
    ],
    correctAnswer: 'isinstance(x, int)',
    explanation: 'The `isinstance()` function is the recommended way to check an object\'s type, as it also handles inheritance.',
  },
  {
    srNo: 70,
    id: 'cm-py-easy-17',
    concept: '`in` operator',
    description: 'Which snippet checks if an item exists in a list?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      '"apple" in fruits',
      'fruits.contains("apple")',
      'fruits.has("apple")',
      'exists("apple", fruits)',
    ],
    correctAnswer: '"apple" in fruits',
    explanation: 'The `in` keyword is used to check if a value is present in a sequence (like a list, tuple, or string).',
  },
  {
    srNo: 71,
    id: 'cm-py-medium-16',
    concept: '`try...except...else`',
    description: 'Which snippet correctly uses the `else` block in exception handling?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'try: ... except: ... else: ...',
      'try: ... catch: ... else: ...',
      'try: ... else: ... except: ...',
      'try: ... except: ... then: ...',
    ],
    correctAnswer: 'try: ... except: ... else: ...',
    explanation: 'The `else` block is executed if and only if no exceptions were raised in the `try` block.',
  },
  {
    srNo: 72,
    id: 'cm-py-medium-17',
    concept: '`try...except...finally`',
    description: 'Which block of code is always executed, regardless of whether an exception occurred?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'finally:',
      'else:',
      'always:',
      'cleanup:',
    ],
    correctAnswer: 'finally:',
    explanation: 'The `finally` block is always executed before leaving the `try...except` statement, whether an exception has occurred or not. It is used for cleanup actions.',
  },
  {
    srNo: 73,
    id: 'cm-py-medium-18',
    concept: '`zip` function',
    description: 'Which snippet correctly combines two lists into a list of tuples?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'list(zip(list1, list2))',
      'list1.zip(list2)',
      'zip(list1, list2).toList()',
      'combine(list1, list2)',
    ],
    correctAnswer: 'list(zip(list1, list2))',
    explanation: 'The `zip()` function returns an iterator of tuples, where the i-th tuple contains the i-th element from each of the argument sequences or iterables.',
  },
  {
    srNo: 74,
    id: 'cm-py-hard-16',
    concept: '`__str__` vs `__repr__`',
    description: 'Which "dunder" method is called by `print()` and `str()` to get an "informal" string representation of an object?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '__str__',
      '__repr__',
      '__print__',
      '__format__',
    ],
    correctAnswer: '__str__',
    explanation: '`__str__` is intended to return a user-friendly, readable string representation of an object. `__repr__` is meant to return an unambiguous, official representation, often one that can be used to recreate the object.',
  },
  {
    srNo: 75,
    id: 'cm-py-hard-17',
    concept: '`*` for unpacking arguments',
    description: 'Which snippet correctly unpacks a list as positional arguments to a function?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'my_func(*my_list)',
      'my_func(my_list)',
      'my_func(...my_list)',
      'my_func(unpack(my_list))',
    ],
    correctAnswer: 'my_func(*my_list)',
    explanation: 'The `*` operator can be used to unpack an iterable into the arguments of a function call.',
  },
  {
    srNo: 76,
    id: 'cm-py-hard-18',
    concept: '`@property` decorator',
    description: 'Which decorator allows a method to be accessed like an attribute?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '@property',
      '@attribute',
      '@getter',
      '@get',
    ],
    correctAnswer: '@property',
    explanation: 'The `@property` decorator is used to define "getter" methods for a class, allowing you to run code when an attribute is accessed, but call it without parentheses.',
  },
  {
    srNo: 77,
    id: 'cm-py-hard-19',
    concept: 'Dataclasses',
    description: 'Which decorator automatically generates special methods like `__init__` and `__repr__` for a class?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      '@dataclass',
      '@autoclass',
      '@datamodel',
      '@generate',
    ],
    correctAnswer: '@dataclass',
    explanation: 'The `@dataclass` decorator from the `dataclasses` module provides a concise way to create classes that are primarily used for storing data.',
  },
  {
    srNo: 78,
    id: 'cm-py-hard-20',
    concept: '`asyncio.gather`',
    description: 'Which function is used to run multiple asyncio awaitable objects concurrently?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'await asyncio.gather(task1, task2)',
      'await asyncio.run(task1, task2)',
      'await asyncio.wait(task1, task2)',
      'await asyncio.all([task1, task2])',
    ],
    correctAnswer: 'await asyncio.gather(task1, task2)',
    explanation: '`asyncio.gather()` runs multiple awaitable objects concurrently and returns a list of their results once all are complete.',
  },

  // Java - Easy
  {
    srNo: 79,
    id: 'cm-java-easy-01',
    concept: 'String Comparison',
    description: 'Which snippet is the correct way to compare the content of two strings?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'if (s1 == s2)',
      'if (s1.equals(s2))',
      'if (s1 === s2)',
      'if (compare(s1, s2))',
    ],
    correctAnswer: 'if (s1.equals(s2))',
    explanation: 'In Java, `==` compares object references. The `.equals()` method must be used to compare the actual character content of strings.',
  },
  {
    srNo: 80,
    id: 'cm-java-easy-02',
    concept: 'Array Declaration',
    description: 'Which snippet correctly declares and initializes an array of integers?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'int numbers = {1, 2, 3};',
      'int[] numbers = [1, 2, 3];',
      'int[] numbers = {1, 2, 3};',
      'Array<int> numbers = {1, 2, 3};',
    ],
    correctAnswer: 'int[] numbers = {1, 2, 3};',
    explanation: 'The correct syntax for declaring and initializing an array in Java uses `type[] name = {values};`.',
  },
  {
    srNo: 81,
    id: 'cm-java-easy-03',
    concept: 'Main Method Signature',
    description: 'Which is the correct signature for the main method, the entry point of a Java application?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'public static void main(String[] args)',
      'public void main(String[] args)',
      'static public main(String[] args)',
      'public static main(string[] args)',
    ],
    correctAnswer: 'public static void main(String[] args)',
    explanation: 'The main method must be `public` (accessible everywhere), `static` (callable without an object), `void` (returns nothing), and take an array of strings as an argument.',
  },
  {
    srNo: 82,
    id: 'cm-java-easy-04',
    concept: 'For Loop',
    description: 'Which snippet shows the correct syntax for a for loop?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'for (i = 0; i < 5; i++)',
      'for i in range(5)',
      'for (int i = 0; i < 5; i++)',
      'foreach (int i in list)',
    ],
    correctAnswer: 'for (int i = 0; i < 5; i++)',
    explanation: 'A standard `for` loop in Java has three parts: initialization, condition, and increment/decrement.',
  },
  {
    srNo: 83,
    id: 'cm-java-easy-05',
    concept: 'String Length',
    description: 'Which snippet correctly gets the number of characters in a string?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      's.length',
      's.length()',
      's.size()',
      'length(s)',
    ],
    correctAnswer: 's.length()',
    explanation: 'In Java, the `length()` method of the String class is used to get the number of characters.',
  },
  {
    srNo: 84,
    id: 'cm-java-easy-06',
    concept: 'Creating an Object',
    description: 'Which snippet correctly creates an instance of a `Car` class?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'Car myCar = new Car();',
      'Car myCar = Car();',
      'new Car() = myCar;',
      'let myCar = new Car();',
    ],
    correctAnswer: 'Car myCar = new Car();',
    explanation: 'To create an object in Java, you specify the class name, a name for the object, and use the `new` keyword followed by a call to the class constructor.',
  },
  {
    srNo: 85,
    id: 'cm-java-easy-07',
    concept: 'Method Definition',
    description: 'Which snippet correctly defines a method that returns an integer?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'def myMethod() -> int',
      'function myMethod(): int',
      'myMethod(): int',
      'int myMethod()',
    ],
    correctAnswer: 'int myMethod()',
    explanation: 'In Java, a method definition starts with the return type, followed by the method name and parentheses for parameters.',
  },
  {
    srNo: 86,
    id: 'cm-java-easy-10',
    concept: 'Importing a Class',
    description: 'Which snippet correctly imports the `ArrayList` class?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'import java.util.ArrayList;',
      '#include <java.util.ArrayList>;',
      'using java.util.ArrayList;',
      'require java.util.ArrayList;',
    ],
    correctAnswer: 'import java.util.ArrayList;',
    explanation: 'The `import` keyword is used in Java to make classes from other packages accessible.',
  },
  {
    srNo: 87,
    id: 'cm-java-easy-11',
    concept: 'Single-Line Comment',
    description: 'Which snippet shows a single-line comment?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      '// This is a comment',
      '# This is a comment',
      '/* This is a comment */',
      '-- This is a comment',
    ],
    correctAnswer: '// This is a comment',
    explanation: 'In Java, `//` is used to start a single-line comment, which extends to the end of the line.',
  },
  {
    srNo: 88,
    id: 'cm-java-easy-12',
    concept: 'Multi-Line Comment',
    description: 'Which snippet shows a multi-line comment?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      '// This is a comment',
      '# This is a comment',
      '/* This is a comment */',
      '-- This is a comment',
    ],
    correctAnswer: '/* This is a comment */',
    explanation: 'A multi-line comment in Java starts with `/*` and ends with `*/`, and can span multiple lines.',
  },
  {
    srNo: 89,
    id: 'cm-java-easy-13',
    concept: 'Switch Statement',
    description: 'Which snippet correctly uses a `switch` statement?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'switch(day) { case 1: ... break; }',
      'switch day { case 1: ... }',
      'select(day) { case 1: ... }',
      'switch { case day == 1: ... }',
    ],
    correctAnswer: 'switch(day) { case 1: ... break; }',
    explanation: 'The `switch` statement evaluates an expression and, based on the expression\'s value, executes code associated with a matching `case` label.',
  },

  // Java - Medium
  {
    srNo: 90,
    id: 'cm-java-medium-01',
    concept: 'Enhanced For-Loop',
    description: 'Which snippet correctly iterates over an ArrayList of Strings?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'for (String s : myList)',
      'for (s in myList)',
      'for (s of myList)',
      'foreach (String s in myList)',
    ],
    correctAnswer: 'for (String s : myList)',
    explanation: 'The enhanced for-loop provides a simpler, more readable way to iterate over elements of a collection or array without needing an index counter.',
  },
  {
    srNo: 91,
    id: 'cm-java-medium-02',
    concept: 'Method Overloading',
    description: 'Which snippet correctly demonstrates method overloading?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'int sum(int a, int b) {}\ndouble sum(int a, int b) {}',
      'int sum(int x, int y) {}\nint sum(int a, int b) {}',
      'int sum(int a, int b) {}\nint sum(int a, int b, int c) {}',
      'int sum(int a, int b) {}\nint calculate(int a, int b) {}',
    ],
    correctAnswer: 'int sum(int a, int b) {}\nint sum(int a, int b, int c) {}',
    explanation: 'Method overloading allows multiple methods with the same name but different parameters (either number of parameters or their types) in the same class.',
  },
  {
    srNo: 92,
    id: 'cm-java-medium-03',
    concept: 'Creating an ArrayList',
    description: 'Which snippet correctly creates an ArrayList to hold strings?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'ArrayList<String> cars = new ArrayList<String>();',
      'List<String> cars = new List();',
      'ArrayList cars = new ArrayList();',
      'ArrayList<String> cars = new ArrayList();',
    ],
    correctAnswer: 'ArrayList<String> cars = new ArrayList<String>();',
    explanation: 'To create an ArrayList, you must import `java.util.ArrayList` and specify the type of objects it will hold in angle brackets `<>`.',
  },
  {
    srNo: 93,
    id: 'cm-java-medium-04',
    concept: 'HashMap',
    description: 'Which snippet correctly creates a HashMap to store String keys and Integer values?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'HashMap<String, Integer> map = new HashMap<>();',
      'HashMap<String, int> map = new HashMap<>();',
      'Map<String, Integer> map = new Map<>();',
      'HashMap map = new HashMap<String, Integer>();',
    ],
    correctAnswer: 'HashMap<String, Integer> map = new HashMap<>();',
    explanation: 'When using generic collections like HashMap, you must use wrapper classes (like `Integer`) for primitive types (like `int`).',
  },
  {
    srNo: 94,
    id: 'cm-java-medium-10',
    concept: 'Constructor',
    description: 'Which snippet correctly defines a constructor for the `Car` class?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'public Car() { ... }',
      'public void Car() { ... }',
      'public new Car() { ... }',
      'public init() { ... }',
    ],
    correctAnswer: 'public Car() { ... }',
    explanation: 'A constructor in Java is a special method used to initialize objects. It must have the same name as the class and has no explicit return type.',
  },
  {
    srNo: 95,
    id: 'cm-java-medium-11',
    concept: '`static` Keyword',
    description: 'Which snippet defines a method that belongs to the class rather than an instance of the class?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'public static void myMethod() { ... }',
      'public class void myMethod() { ... }',
      'public shared void myMethod() { ... }',
      'public void myMethod() { ... }',
    ],
    correctAnswer: 'public static void myMethod() { ... }',
    explanation: 'The `static` keyword means the method can be accessed without creating an object of the class.',
  },
  {
    srNo: 96,
    id: 'cm-java-medium-12',
    concept: 'Encapsulation (Getters/Setters)',
    description: 'Which snippet demonstrates encapsulation by making a field private and providing public access methods?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'public String name; public void setName(...) { ... }',
      'private String name; public String getName() { ... }',
      'protected String name;',
      'String name;',
    ],
    correctAnswer: 'private String name; public String getName() { ... }',
    explanation: 'Encapsulation is the practice of hiding the internal state of an object and requiring all interaction to be performed through an object\'s methods.',
  },
  {
    srNo: 97,
    id: 'cm-java-medium-13',
    concept: 'Abstract Class',
    description: 'Which snippet correctly declares a class that cannot be instantiated on its own?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'public abstract class Animal { ... }',
      'public virtual class Animal { ... }',
      'public non-instantiable class Animal { ... }',
      'public interface Animal { ... }',
    ],
    correctAnswer: 'public abstract class Animal { ... }',
    explanation: 'An `abstract` class is a restricted class that cannot be used to create objects (to access it, it must be inherited from another class).',
  },

  // Java - Hard
  {
    srNo: 98,
    id: 'cm-java-hard-01',
    concept: 'Interface Implementation',
    description: 'Which snippet shows a class correctly implementing an interface?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'class Car extends Drivable {}',
      'class Car inherits Drivable {}',
      'class Car uses Drivable {}',
      'class Car implements Drivable {}',
    ],
    correctAnswer: 'class Car implements Drivable {}',
    explanation: 'A class uses the `implements` keyword to use an interface. It must then provide an implementation for all the methods defined in that interface.',
  },
  {
    srNo: 99,
    id: 'cm-java-hard-02',
    concept: 'Exception Handling',
    description: 'Which snippet correctly handles a potential file reading error?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'try { readFile(); } catch (IOException e) { ... }',
      'if (readFile()) { ... } else { ... }',
      'on (error) { ... }',
      'throws IOException { readFile(); }',
    ],
    correctAnswer: 'try { readFile(); } catch (IOException e) { ... }',
    explanation: 'The `try...catch` block is the standard way to handle exceptions in Java. Code that might throw an exception is placed in the `try` block, and the code to handle it is in the `catch` block.',
  },
  {
    srNo: 100,
    id: 'cm-java-hard-03',
    concept: 'Polymorphism',
    description: 'Which snippet demonstrates polymorphism?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'Animal myAnimal = new Animal();',
      'Animal myDog = new Dog();',
      'Dog myDog = new Animal();',
      'Dog myDog = (Dog) new Animal();',
    ],
    correctAnswer: 'Animal myDog = new Dog();',
    explanation: 'Polymorphism means "many forms". It allows us to perform a single action in different ways. Here, a `Dog` object (a subclass) is being referred to by a variable of its superclass type, `Animal`.',
  },
  {
    srNo: 101,
    id: 'cm-java-hard-04',
    concept: 'Lambda Expression',
    description: 'Which snippet correctly uses a lambda expression to iterate over a list?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'list.forEach(item -> System.out.println(item));',
      'list.forEach(item => System.out.println(item));',
      'for (item : list) -> System.out.println(item);',
      'lambda item in list: System.out.println(item);',
    ],
    correctAnswer: 'list.forEach(item -> System.out.println(item));',
    explanation: 'Lambda expressions provide a clear and concise way to represent one method interface using an expression. The `->` separates the parameters from the expression body.',
  },
  {
    srNo: 102,
    id: 'cm-java-hard-11',
    concept: '`@Override` Annotation',
    description: 'Which annotation is used to indicate that a method is intended to override a method in a superclass?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      '@Override',
      '@Overload',
      '@Implements',
      '@Virtual',
    ],
    correctAnswer: '@Override',
    explanation: 'The `@Override` annotation informs the compiler that the element is meant to override an element declared in a superclass. It helps prevent errors if the method signature is incorrect.',
  },
  {
    srNo: 103,
    id: 'cm-java-hard-12',
    concept: 'Generic Class',
    description: 'Which snippet correctly defines a generic class that can hold any type?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'public class Box<T> { ... }',
      'public class Box<Any> { ... }',
      'public class Box<*> { ... }',
      'public generic class Box { ... }',
    ],
    correctAnswer: 'public class Box<T> { ... }',
    explanation: 'Generics are defined using angle brackets `<>`. `T` is a type parameter that will be replaced by a real type when an object of `Box` is created.',
  },
  {
    srNo: 104,
    id: 'cm-java-hard-13',
    concept: 'Enum',
    description: 'Which snippet correctly defines an enumeration?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'public enum Level { LOW, MEDIUM, HIGH }',
      'public enumeration Level { LOW, MEDIUM, HIGH }',
      'public class Level { enum { LOW, MEDIUM, HIGH } }',
      'public const Level = { LOW, MEDIUM, HIGH }',
    ],
    correctAnswer: 'public enum Level { LOW, MEDIUM, HIGH }',
    explanation: 'An `enum` is a special "class" that represents a group of constants (unchangeable variables).',
  },
  {
    srNo: 105,
    id: 'cm-java-hard-14',
    concept: 'Thread Creation',
    description: 'Which snippet correctly creates and starts a new thread?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'Thread t = new Thread(new MyRunnable()); t.start();',
      'Thread t = new MyRunnable(); t.run();',
      'Thread.create(new MyRunnable());',
      'new Thread().execute(new MyRunnable());',
    ],
    correctAnswer: 'Thread t = new Thread(new MyRunnable()); t.start();',
    explanation: 'A new thread is created by passing a `Runnable` object to the `Thread` constructor. The thread is started by calling its `start()` method, which in turn calls the `run()` method of the `Runnable`.',
  },
  {
    srNo: 106,
    id: 'cm-java-easy-14',
    concept: 'String length vs array length',
    description: 'Which snippet correctly gets the number of elements in an array?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'myArray.length()',
      'myArray.length',
      'myArray.size()',
      'sizeof(myArray)',
    ],
    correctAnswer: 'myArray.length',
    explanation: 'In Java, you get the number of elements in an array using the `length` property (no parentheses), whereas for a String, you use the `length()` method.',
  },
  {
    srNo: 107,
    id: 'cm-java-easy-15',
    concept: 'Ternary Operator',
    description: 'Which snippet uses the ternary operator to assign a value?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'String result = (time < 18) ? "Good day." : "Good evening.";',
      'String result = if (time < 18) "Good day." else "Good evening.";',
      'String result = (time < 18) -> "Good day." : "Good evening.";',
      'String result = when (time < 18) ? "Good day." : "Good evening.";',
    ],
    correctAnswer: 'String result = (time < 18) ? "Good day." : "Good evening.";',
    explanation: 'The ternary operator provides a concise way to write a simple if-else statement in a single line.',
  },
  {
    srNo: 108,
    id: 'cm-java-medium-14',
    concept: '`StringBuilder`',
    description: 'Which snippet is the most efficient way to build a string in a loop?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'String s = ""; for(...) { s += "x"; }',
      'StringBuilder sb = new StringBuilder(); for(...) { sb.append("x"); }',
      'String[] arr = new String[...]; for(...) { arr[i] = "x"; }',
      'StringBuffer sb = new StringBuffer(); for(...) { sb.add("x"); }',
    ],
    correctAnswer: 'StringBuilder sb = new StringBuilder(); for(...) { sb.append("x"); }',
    explanation: 'Since Strings are immutable, using `+=` in a loop creates many new String objects. `StringBuilder` is mutable and much more efficient for this task.',
  },
  {
    srNo: 109,
    id: 'cm-java-medium-15',
    concept: '`instanceof` operator',
    description: 'Which snippet correctly checks if an object is an instance of a particular class?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'if (obj instanceof Dog)',
      'if (obj.is(Dog))',
      'if (typeof(obj) == "Dog")',
      'if (obj.class == Dog.class)',
    ],
    correctAnswer: 'if (obj instanceof Dog)',
    explanation: 'The `instanceof` operator returns true if the object is an instance of the specified class or an instance of a subclass.',
  },
  {
    srNo: 110,
    id: 'cm-java-medium-16',
    concept: '`HashSet`',
    description: 'Which snippet correctly creates a collection that stores only unique items?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'List<String> set = new ArrayList<>();',
      'Set<String> set = new HashSet<>();',
      'UniqueList<String> set = new UniqueList<>();',
      'Collection<String> set = new Collection<>();',
    ],
    correctAnswer: 'Set<String> set = new HashSet<>();',
    explanation: '`HashSet` implements the `Set` interface and does not allow duplicate elements.',
  },
  {
    srNo: 111,
    id: 'cm-java-hard-15',
    concept: 'Stream API - filter',
    description: 'Which snippet uses the Stream API to filter a list?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'list.stream().filter(s -> s.startsWith("a")).collect(Collectors.toList());',
      'list.filter(s -> s.startsWith("a"));',
      'new Stream(list).filter(s -> s.startsWith("a")).toList();',
      'for(String s : list) { if(s.startsWith("a")) ... }',
    ],
    correctAnswer: 'list.stream().filter(s -> s.startsWith("a")).collect(Collectors.toList());',
    explanation: 'The Stream API provides a functional approach to processing collections. `.stream()` creates a stream, `.filter()` applies a predicate, and `.collect()` gathers the results.',
  },
  {
    srNo: 112,
    id: 'cm-java-hard-16',
    concept: 'Stream API - map',
    description: 'Which snippet uses the Stream API to transform each element in a list?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'list.stream().map(s -> s.toUpperCase()).collect(Collectors.toList());',
      'list.map(s -> s.toUpperCase());',
      'list.stream().transform(s -> s.toUpperCase());',
      'list.forEach(s -> s.toUpperCase());',
    ],
    correctAnswer: 'list.stream().map(s -> s.toUpperCase()).collect(Collectors.toList());',
    explanation: 'The `.map()` operation on a stream applies a function to each element, producing a new stream of the transformed elements.',
  },
  {
    srNo: 113,
    id: 'cm-java-hard-17',
    concept: '`Optional`',
    description: 'Which snippet is the correct way to create an Optional for a value that might be null?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'Optional.ofNullable(value);',
      'Optional.of(value);',
      'new Optional(value);',
      'Optional.create(value);',
    ],
    correctAnswer: 'Optional.ofNullable(value);',
    explanation: '`Optional.ofNullable()` returns an `Optional` describing the specified value, if non-null, otherwise returns an empty `Optional`. `Optional.of()` would throw a NullPointerException if the value is null.',
  },
  {
    srNo: 114,
    id: 'cm-java-hard-18',
    concept: '`synchronized` keyword',
    description: 'Which keyword is used to mark a method or block of code as thread-safe, allowing only one thread to execute it at a time?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'synchronized',
      'atomic',
      'locked',
      'threadsafe',
    ],
    correctAnswer: 'synchronized',
    explanation: 'The `synchronized` keyword provides a lock on an object to prevent race conditions when multiple threads access shared resources.',
  },
  {
    srNo: 115,
    id: 'cm-java-hard-19',
    concept: '`volatile` keyword',
    description: 'Which keyword ensures that modifications to a variable are always visible to other threads?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'volatile',
      'atomic',
      'visible',
      'shared',
    ],
    correctAnswer: 'volatile',
    explanation: 'The `volatile` keyword guarantees that any thread that reads the field will see the most recently written value, preventing issues with cached variable values in different threads.',
  },

  // C++ - Easy
  {
    srNo: 116,
    id: 'cm-cpp-easy-01',
    concept: 'Include Directive',
    description: 'Which snippet correctly includes the library for input and output streams?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'import <iostream>;',
      '#include <iostream>',
      '#import <iostream>',
      'include <iostream>;',
    ],
    correctAnswer: '#include <iostream>',
    explanation: 'In C++, the `#include` preprocessor directive is used to include the contents of a header file in the current source file.',
  },
  {
    srNo: 117,
    id: 'cm-cpp-easy-02',
    concept: 'Pointer Dereference',
    description: 'Which snippet correctly gets the value stored at the memory address held by a pointer?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'value = &ptr;',
      'value = *ptr;',
      'value = ptr.value;',
      'value = ptr->value;',
    ],
    correctAnswer: 'value = *ptr;',
    explanation: 'The dereference operator `*` is used to access the value that a pointer points to.',
  },
  {
    srNo: 118,
    id: 'cm-cpp-easy-03',
    concept: 'Reference Variable',
    description: 'Which snippet correctly declares a reference to another variable?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int &ref = original;',
      'int *ref = original;',
      'ref<int> = original;',
      'reference int ref = original;',
    ],
    correctAnswer: 'int &ref = original;',
    explanation: 'In C++, a reference is an alias for an already existing variable. It is declared using the ampersand `&` symbol.',
  },
  {
    srNo: 119,
    id: 'cm-cpp-easy-04',
    concept: 'Using Namespace',
    description: 'Which snippet allows you to use names for objects and variables from the standard library without the `std::` prefix?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'import namespace std;',
      'using namespace std;',
      'namespace(std);',
      'std::use();',
    ],
    correctAnswer: 'using namespace std;',
    explanation: 'The `using namespace std;` statement allows you to use elements from the `std` namespace directly, like `cout` instead of `std::cout`.',
  },
  {
    srNo: 120,
    id: 'cm-cpp-easy-05',
    concept: 'Array Declaration',
    description: 'Which snippet correctly declares an array of 4 integers?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int arr[4];',
      'int arr = new int[4];',
      'Array<int> arr(4);',
      'vector<int> arr(4);',
    ],
    correctAnswer: 'int arr[4];',
    explanation: 'In C++, a static array is declared with the syntax `type name[size];`.',
  },
  {
    srNo: 121,
    id: 'cm-cpp-easy-06',
    concept: 'Get String Length',
    description: 'Which snippet correctly gets the length of a `std::string`?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'len(myString)',
      'myString.length',
      'myString.length()',
      'sizeof(myString)',
    ],
    correctAnswer: 'myString.length()',
    explanation: 'The `std::string` class has a `length()` (or `size()`) method that returns the number of characters in the string.',
  },
  {
    srNo: 122,
    id: 'cm-cpp-easy-10',
    concept: 'Standard Output',
    description: 'Which snippet correctly prints "Hello" to the console?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'std::cout << "Hello";',
      'console.log("Hello");',
      'printf("Hello");',
      'System.out.println("Hello");',
    ],
    correctAnswer: 'std::cout << "Hello";',
    explanation: '`std::cout`, used with the stream insertion operator `<<`, is the standard way to output text in C++.',
  },
  {
    srNo: 123,
    id: 'cm-cpp-easy-11',
    concept: 'Main Function',
    description: 'Which is the correct signature for the main function, the entry point of a C++ program?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int main()',
      'void main()',
      'function main()',
      'int Main()',
    ],
    correctAnswer: 'int main()',
    explanation: 'The `main` function is the entry point of every C++ program. It traditionally returns an `int` to indicate the program\'s exit status.',
  },
  {
    srNo: 124,
    id: 'cm-cpp-easy-12',
    concept: '`std::vector` Declaration',
    description: 'Which snippet correctly declares a vector of integers?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'std::vector<int> v;',
      'vector<int> v;',
      'int<vector> v;',
      'std::vector v<int>;',
    ],
    correctAnswer: 'std::vector<int> v;',
    explanation: '`std::vector` is a sequence container representing arrays that can change in size. The type of elements it holds is specified in angle brackets `<>`.',
  },
  {
    srNo: 125,
    id: 'cm-cpp-easy-13',
    concept: 'Variable Assignment',
    description: 'Which snippet correctly assigns the value 10 to a variable `x`?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int x = 10;',
      'let x = 10;',
      'x := 10;',
      'int x == 10;',
    ],
    correctAnswer: 'int x = 10;',
    explanation: 'In C++, variables are declared with their type followed by the variable name, and the `=` operator is used for assignment.',
  },

  // C++ - Medium
  {
    srNo: 126,
    id: 'cm-cpp-medium-01',
    concept: 'Range-based For Loop',
    description: 'Which snippet correctly iterates over the elements of a vector?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'for (int i : my_vector)',
      'for (int i = 0; i < my_vector.size(); i++)',
      'my_vector.forEach(i => ...)',
      'for (i in my_vector)',
    ],
    correctAnswer: 'for (int i : my_vector)',
    explanation: 'The range-based for loop (since C++11) provides a more concise and less error-prone way to iterate over the elements of a container.',
  },
  {
    srNo: 127,
    id: 'cm-cpp-medium-02',
    concept: 'Class Constructor',
    description: 'Which snippet correctly defines a constructor for the `Car` class?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'void Car() { ... }',
      'Car() { ... }',
      'construct Car() { ... }',
      'def Car() { ... }',
    ],
    correctAnswer: 'Car() { ... }',
    explanation: 'A constructor in C++ is a special member function that has the same name as the class and is called when an object of the class is created. It has no return type.',
  },
  {
    srNo: 128,
    id: 'cm-cpp-medium-03',
    concept: 'Header Guards',
    description: 'Which snippet represents a standard header guard to prevent multiple inclusions?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      '#once',
      '#guard MY_HEADER_H',
      '#ifdef MY_HEADER_H',
      '#ifndef MY_HEADER_H\n#define MY_HEADER_H\n...\n#endif',
    ],
    correctAnswer: '#ifndef MY_HEADER_H\n#define MY_HEADER_H\n...\n#endif',
    explanation: 'Header guards are preprocessor directives that prevent the contents of a header from being included more than once in a single compilation unit, which would cause redefinition errors.',
  },
  {
    srNo: 129,
    id: 'cm-cpp-medium-04',
    concept: 'Dynamic Memory Allocation',
    description: 'Which snippet correctly allocates an integer on the heap?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'int* p = new int;',
      'int p = new int;',
      'int* p = malloc(sizeof(int));',
      'new int* p;',
    ],
    correctAnswer: 'int* p = new int;',
    explanation: 'The `new` operator is used in C++ to allocate memory on the heap. It returns a pointer to the allocated memory.',
  },
  {
    srNo: 130,
    id: 'cm-cpp-medium-05',
    concept: 'Function Overloading',
    description: 'Which snippet correctly demonstrates function overloading?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'int print(int i){}\nfloat print(int i){}',
      'int print(int i){}\nint print(int j){}',
      'int print(int i){}\nint print(double d){}',
      'int print(int i){}\nint show(int i){}',
    ],
    correctAnswer: 'int print(int i){}\nint print(double d){}',
    explanation: 'Function overloading allows multiple functions to have the same name as long as they have different parameter lists (either different types or a different number of parameters).',
  },
  {
    srNo: 131,
    id: 'cm-cpp-medium-06',
    concept: 'Passing by Reference',
    description: 'Which function signature correctly takes an integer by reference?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'void func(int* x)',
      'void func(int& x)',
      'void func(ref int x)',
      'void func(int x)',
    ],
    correctAnswer: 'void func(int& x)',
    explanation: 'Using `&` after the type in a function parameter list declares that the argument should be passed by reference, allowing the function to modify the original variable.',
  },
  {
    srNo: 132,
    id: 'cm-cpp-medium-10',
    concept: 'std::map',
    description: 'Which snippet correctly inserts a key-value pair into a map?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'my_map["key"] = "value";',
      'my_map.add("key", "value");',
      'my_map.append("key", "value");',
      'my_map->insert("key", "value");',
    ],
    correctAnswer: 'my_map["key"] = "value";',
    explanation: 'The subscript operator `[]` is a convenient way to insert or access elements in a `std::map`.',
  },
  {
    srNo: 133,
    id: 'cm-cpp-medium-11',
    concept: 'struct vs class',
    description: 'What is the default access specifier for members of a `struct`?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'public',
      'private',
      'protected',
      'internal',
    ],
    correctAnswer: 'public',
    explanation: 'In C++, members of a `struct` are `public` by default, whereas members of a `class` are `private` by default.',
  },
  {
    srNo: 134,
    id: 'cm-cpp-medium-12',
    concept: 'Class Member Initialization List',
    description: 'Which snippet shows the preferred way to initialize class members in a constructor?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'MyClass(int v) : value(v) {}',
      'MyClass(int v) { this->value = v; }',
      'MyClass(int v) { value = v; }',
      'MyClass(int v) { init(v); }',
    ],
    correctAnswer: 'MyClass(int v) : value(v) {}',
    explanation: 'Using a member initialization list is more efficient as it initializes members directly, whereas assignment in the constructor body first default-initializes and then assigns.',
  },
  {
    srNo: 135,
    id: 'cm-cpp-medium-13',
    concept: 'Smart Pointer (unique_ptr)',
    description: 'Which snippet correctly creates a unique pointer to manage dynamic memory?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'std::unique_ptr<int> p(new int(5));',
      'std::unique_ptr<int> p = new int(5);',
      'std::unique_ptr p = new int(5);',
      'unique_ptr<int> p(new int(5));',
    ],
    correctAnswer: 'std::unique_ptr<int> p(new int(5));',
    explanation: '`std::unique_ptr` is a smart pointer that owns and manages another object through a pointer and disposes of that object when the `unique_ptr` goes out of scope.',
  },
    
  // C++ - Hard
  {
    srNo: 136,
    id: 'cm-cpp-hard-01',
    concept: 'Virtual Function (Polymorphism)',
    description: 'Which snippet correctly declares a function that can be overridden by a derived class to enable polymorphism?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'override void makeSound() {}',
      'dynamic void makeSound() {}',
      'virtual void makeSound() {}',
      'poly void makeSound() {}',
    ],
    correctAnswer: 'virtual void makeSound() {}',
    explanation: 'The `virtual` keyword is used to declare a member function in a base class that you expect to be redefined in derived classes. This is fundamental to achieving runtime polymorphism in C++.',
  },
  {
    srNo: 137,
    id: 'cm-cpp-hard-02',
    concept: 'Template Function',
    description: 'Which snippet defines a generic function that can operate on different data types?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'generic<T> T add(T a, T b) {}',
      'template<typename T> T add(T a, T b) {}',
      'function<T> add(T a, T b) {}',
      'auto add(auto a, auto b) {}',
    ],
    correctAnswer: 'template<typename T> T add(T a, T b) {}',
    explanation: 'Templates allow you to write generic programs. The `template<typename T>` syntax declares a template where `T` is a placeholder for a data type that will be specified when the function is called.',
  },
  {
    srNo: 138,
    id: 'cm-cpp-hard-03',
    concept: 'The "Rule of Three/Five"',
    description: 'If a class has a user-defined destructor, which other members should it typically also define?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'A constructor and a static method',
      'A copy constructor and a copy assignment operator',
      'A `begin()` and `end()` method',
      'A virtual constructor',
    ],
    correctAnswer: 'A copy constructor and a copy assignment operator',
    explanation: 'The Rule of Three (or Five in modern C++) is a rule of thumb stating that if a class defines any of a destructor, copy constructor, or copy assignment operator, it should probably define all three (plus move constructor and move assignment).',
  },
  {
    srNo: 139,
    id: 'cm-cpp-hard-04',
    concept: 'RAII (Resource Acquisition Is Initialization)',
    description: 'Which snippet best demonstrates the RAII idiom for managing a resource?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'int* p = new int; delete p;',
      'std::shared_ptr<int> p(new int);',
      'FILE* f = fopen(...); fclose(f);',
      'lock(); unlock();',
    ],
    correctAnswer: 'std::shared_ptr<int> p(new int);',
    explanation: 'RAII is a core C++ concept where resource lifetime is tied to object lifetime. Smart pointers like `std::shared_ptr` acquire the resource (memory) on construction and automatically release it on destruction, preventing leaks.',
  },
  {
    srNo: 140,
    id: 'cm-cpp-hard-05',
    concept: 'Lambda Function with Capture',
    description: 'Which snippet shows a lambda that captures an external variable by value?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'auto my_lambda = [](int x) { return x + y; };',
      'auto my_lambda = [=](int x) { return x + y; };',
      'auto my_lambda = (&)(int x) { return x + y; };',
      'auto my_lambda = (int y, int x) { return x + y; };',
    ],
    correctAnswer: 'auto my_lambda = [=](int x) { return x + y; };',
    explanation: 'The `[...]` part of a lambda is the capture clause. `[=]` captures all automatic variables used in the lambda by value, making a copy of them.',
  },
  {
    srNo: 141,
    id: 'cm-cpp-hard-06',
    concept: 'Pure Virtual Function',
    description: 'Which snippet defines an abstract base class that cannot be instantiated?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'class Shape { public: virtual void draw() = 0; };',
      'class Shape { public: abstract void draw(); };',
      'class Shape { public: virtual void draw() {}; };',
      'class Shape = 0 { ... };',
    ],
    correctAnswer: 'class Shape { public: virtual void draw() = 0; };',
    explanation: 'A pure virtual function is declared by assigning `= 0`. A class containing at least one pure virtual function is an abstract class, and no objects of that class can be created.',
  },
  {
    srNo: 142,
    id: 'cm-cpp-hard-10',
    concept: 'const correctness',
    description: 'Which snippet correctly declares a member function that does not modify the object\'s state?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'int getValue() const { ... }',
      'const int getValue() { ... }',
      'int const getValue() { ... }',
      'int getValue(const this) { ... }',
    ],
    correctAnswer: 'int getValue() const { ... }',
    explanation: 'Placing `const` after the parameter list of a member function indicates that the function will not modify the state of the `this` object.',
  },
  {
    srNo: 143,
    id: 'cm-cpp-hard-11',
    concept: '`static_cast`',
    description: 'Which snippet shows a compile-time cast between related pointer types?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'Derived* d = static_cast<Derived*>(base_ptr);',
      'Derived* d = (Derived*)base_ptr;',
      'Derived* d = dynamic_cast<Derived*>(base_ptr);',
      'Derived* d = reinterpret_cast<Derived*>(base_ptr);',
    ],
    correctAnswer: 'Derived* d = static_cast<Derived*>(base_ptr);',
    explanation: '`static_cast` is used for conversions between related types, like upcasting or downcasting in a class hierarchy, where the safety is known at compile time.',
  },
  {
    srNo: 144,
    id: 'cm-cpp-hard-12',
    concept: '`dynamic_cast`',
    description: 'Which snippet shows a safe, runtime-checked cast for polymorphic types?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'Derived* d = static_cast<Derived*>(base_ptr);',
      'Derived* d = (Derived*)base_ptr;',
      'Derived* d = dynamic_cast<Derived*>(base_ptr);',
      'Derived* d = reinterpret_cast<Derived*>(base_ptr);',
    ],
    correctAnswer: 'Derived* d = dynamic_cast<Derived*>(base_ptr);',
    explanation: '`dynamic_cast` is used for downcasting polymorphic types. It performs a runtime check to ensure the cast is valid, returning `nullptr` if it is not.',
  },
  {
    srNo: 145,
    id: 'cm-cpp-hard-13',
    concept: 'Operator Overloading',
    description: 'Which snippet correctly overloads the `+` operator for a `Vector` class?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'Vector operator+(const Vector& other) { ... }',
      'Vector +(const Vector& other) { ... }',
      'operator+(Vector v1, Vector v2) { ... }',
      'function operator+(const Vector& other) { ... }',
    ],
    correctAnswer: 'Vector operator+(const Vector& other) { ... }',
    explanation: 'The `operator` keyword is used to define a function that overloads a specific operator for a class.',
  },
  {
    srNo: 146,
    id: 'cm-cpp-hard-14',
    concept: 'std::thread',
    description: 'Which snippet correctly creates and starts a new thread?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'std::thread t(my_function); t.join();',
      'std::thread t = new std::thread(my_function);',
      'new thread(my_function);',
      'std::thread.run(my_function);',
    ],
    correctAnswer: 'std::thread t(my_function); t.join();',
    explanation: 'An `std::thread` object is created by passing a callable (like a function) to its constructor, which starts the thread. `join()` is then called to wait for the thread to finish.',
  },
  {
    srNo: 147,
    id: 'cm-cpp-hard-15',
    concept: 'Move Semantics',
    description: 'Which snippet defines a move constructor for a class?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'MyClass(MyClass&& other) noexcept { ... }',
      'MyClass(const MyClass& other) { ... }',
      'MyClass(MyClass* other) { ... }',
      'MyClass(move MyClass other) { ... }',
    ],
    correctAnswer: 'MyClass(MyClass&& other) noexcept { ... }',
    explanation: 'A move constructor takes an rvalue reference (`&&`) to an object of the same class. It is used to efficiently transfer ownership of resources from a temporary object.',
  },
  {
    srNo: 148,
    id: 'cm-cpp-hard-16',
    concept: '`constexpr` function',
    description: 'Which snippet defines a function that can be evaluated at compile time?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'constexpr int factorial(int n) { ... }',
      'const int factorial(int n) { ... }',
      'static int factorial(int n) { ... }',
      'compile_time int factorial(int n) { ... }',
    ],
    correctAnswer: 'constexpr int factorial(int n) { ... }',
    explanation: 'The `constexpr` specifier declares that it is possible to evaluate the value of the function or variable at compile time.',
  },
  {
    srNo: 149,
    id: 'cm-cpp-hard-17',
    concept: 'Namespace alias',
    description: 'Which snippet creates a shorter alias for a long namespace?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'namespace fs = std::filesystem;',
      'alias fs = std::filesystem;',
      'using fs = std::filesystem;',
      'let fs = std::filesystem;',
    ],
    correctAnswer: 'namespace fs = std::filesystem;',
    explanation: 'A namespace alias definition is a convenient way to create a shorter name for a namespace.',
  },
  {
    srNo: 150,
    id: 'cm-cpp-easy-14',
    concept: '`const` keyword',
    description: 'Which snippet correctly declares a variable whose value cannot be changed?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'const int x = 10;',
      'final int x = 10;',
      'static int x = 10;',
      'let x = 10;',
    ],
    correctAnswer: 'const int x = 10;',
    explanation: 'The `const` keyword specifies that a variable\'s value is constant and tells the compiler to prevent the programmer from modifying it.',
  },
  {
    srNo: 151,
    id: 'cm-cpp-easy-15',
    concept: '`for` loop',
    description: 'Which snippet correctly loops from 0 to 9?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'for (int i = 0; i < 10; ++i)',
      'for (int i = 0; i <= 10; ++i)',
      'for (int i : 10)',
      'loop (int i = 0; i < 10; ++i)',
    ],
    correctAnswer: 'for (int i = 0; i < 10; ++i)',
    explanation: 'The standard C++ `for` loop has three parts: initialization, condition, and increment.',
  },
  {
    srNo: 152,
    id: 'cm-cpp-medium-14',
    concept: '`std::map`',
    description: 'Which snippet declares a map of strings to integers?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'std::map<std::string, int> myMap;',
      'std::map<int, std::string> myMap;',
      'std::vector<std::string, int> myMap;',
      'map<string, int> myMap;',
    ],
    correctAnswer: 'std::map<std::string, int> myMap;',
    explanation: '`std::map` is an associative container that stores elements in a mapped fashion. Each element has a key value and a mapped value. The first template parameter is the key type, the second is the value type.',
  },
  {
    srNo: 153,
    id: 'cm-cpp-medium-15',
    concept: '`std::vector` `push_back`',
    description: 'Which snippet adds an element to the end of a vector?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'myVector.push_back(10);',
      'myVector.add(10);',
      'myVector.append(10);',
      'myVector.insert_back(10);',
    ],
    correctAnswer: 'myVector.push_back(10);',
    explanation: 'The `push_back()` member function is used to add an element to the end of a `std::vector`, resizing it if necessary.',
  },
  {
    srNo: 154,
    id: 'cm-cpp-medium-16',
    concept: '`struct`',
    description: 'Which snippet correctly defines a simple structure?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'struct Person { std::string name; int age; };',
      'class Person { std::string name; int age; };',
      'struct Person(std::string name, int age);',
      'define struct Person { ... };',
    ],
    correctAnswer: 'struct Person { std::string name; int age; };',
    explanation: 'A `struct` in C++ is a user-defined data type that groups together variables of different data types. Its members are public by default.',
  },
  {
    srNo: 155,
    id: 'cm-cpp-hard-18',
    concept: '`unique_ptr`',
    description: 'Which smart pointer provides exclusive ownership of a dynamically allocated object?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'std::unique_ptr',
      'std::shared_ptr',
      'std::weak_ptr',
      'std::auto_ptr',
    ],
    correctAnswer: 'std::unique_ptr',
    explanation: '`std::unique_ptr` is a smart pointer that owns and manages another object through a pointer and disposes of that object when the `unique_ptr` goes out of scope. It cannot be copied.',
  },
  {
    srNo: 156,
    id: 'cm-cpp-hard-19',
    concept: '`shared_ptr`',
    description: 'Which smart pointer allows for multiple owners of the same dynamically allocated object?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'std::unique_ptr',
      'std::shared_ptr',
      'std::weak_ptr',
      'std::owner_ptr',
    ],
    correctAnswer: 'std::shared_ptr',
    explanation: '`std::shared_ptr` retains shared ownership of an object through a pointer. Several `shared_ptr` objects may own the same object. The object is destroyed when the last remaining `shared_ptr` is destroyed.',
  },
  {
    srNo: 157,
    id: 'cm-cpp-hard-20',
    concept: '`static` members',
    description: 'Which keyword declares a class member that belongs to the class itself, rather than to instances of it?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'static',
      'shared',
      'class',
      'global',
    ],
    correctAnswer: 'static',
    explanation: 'Static members of a class are not associated with each instance of the class; they are shared among all instances. There is only one copy of a static member for the entire class.',
  },
  {
    srNo: 158,
    id: 'cm-cpp-hard-21',
    concept: '`const` member functions',
    description: 'Which snippet declares a member function that is not allowed to modify the object\'s member variables?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'int getValue() const;',
      'const int getValue();',
      'int const getValue();',
      'int getValue(const this);',
    ],
    correctAnswer: 'int getValue() const;',
    explanation: 'A `const` member function, declared with the `const` keyword after the parameter list, promises not to change the state of the object on which it is called.',
  },
  {
    srNo: 159,
    id: 'cm-cpp-hard-22',
    concept: 'R-value references',
    description: 'Which syntax is used to declare a reference to a temporary object (an r-value)?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'int&& ref = 10;',
      'int& ref = 10;',
      'int* ref = &10;',
      'int rval& ref = 10;',
    ],
    correctAnswer: 'int&& ref = 10;',
    explanation: 'R-value references are declared using `&&`. They are used to implement move semantics and perfect forwarding, allowing for more efficient resource transfer from temporary objects.',
  },
];

export function getConceptMatchChallengeById(id: string): ConceptMatchChallenge | undefined {
    return conceptMatchChallenges.find(c => c.id === id);
}
