
export interface ConceptMatchChallenge {
  id: string;
  concept: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  options: string[]; // Array of code snippets
  correctAnswer: string; // The correct code snippet
  explanation: string;
}

export const conceptMatchChallenges: ConceptMatchChallenge[] = [
  // JavaScript - Easy
  {
    id: 'cm-js-easy-01',
    concept: 'Variable Declaration (let)',
    description: 'Which snippet correctly declares a variable that can be reassigned?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'const name = "Alice";',
      'let score = 100;',
      'variable user = "Bob";',
      'static String title = "Page";',
    ],
    correctAnswer: 'let score = 100;',
    explanation: 'In modern JavaScript, `let` is used to declare variables that can be reassigned. `const` is for variables that cannot be reassigned.',
  },
  {
    id: 'cm-js-easy-02',
    concept: 'Arrow Function',
    description: 'Which snippet shows the correct syntax for a simple arrow function?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'function add(a, b) => a + b;',
      'const add = (a, b) => a + b;',
      'const add = function(a, b) => a + b;',
      'def add = (a, b) => a + b;',
    ],
    correctAnswer: 'const add = (a, b) => a + b;',
    explanation: 'Arrow function syntax uses `=>` to separate the parameters from the function body. For a single return expression, curly braces are not needed.',
  },
  {
    id: 'cm-js-easy-03',
    concept: 'Strict Equality',
    description: 'Which snippet correctly checks if two values are equal in both value and type?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'if (a == b)',
      'if (a === b)',
      'if (a = b)',
      'if (a equals b)',
    ],
    correctAnswer: 'if (a === b)',
    explanation: 'The strict equality operator `===` checks for equality without performing type coercion, meaning both the value and the type must be the same.',
  },
  {
    id: 'cm-js-easy-04',
    concept: 'Array `push` Method',
    description: 'Which snippet correctly adds an element to the end of an array?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'myArray.add("new_item");',
      'myArray.append("new_item");',
      'myArray.push("new_item");',
      'myArray[myArray.length] = "new_item";',
    ],
    correctAnswer: 'myArray.push("new_item");',
    explanation: 'The `push()` method is the standard way to add one or more elements to the end of an array in JavaScript.',
  },
  {
    id: 'cm-js-easy-05',
    concept: 'Object Property Access',
    description: 'Which snippet correctly accesses the `model` property of the `car` object?',
    language: 'javascript',
    difficulty: 'Easy',
    options: [
      'car.model',
      'car["model"]',
      'car(model)',
      'get(car, "model")',
    ],
    correctAnswer: 'car.model',
    explanation: 'Dot notation (`object.property`) is a common and direct way to access the properties of an object.',
  },

  // JavaScript - Medium
  {
    id: 'cm-js-medium-01',
    concept: 'Array `map` method',
    description: 'Which snippet correctly creates a new array with the doubled values of the original?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'numbers.forEach(num => num * 2);',
      'const doubled = numbers.map(num => num * 2);',
      'for (let num of numbers) { num * 2; }',
      'const doubled = numbers.reduce(num => num * 2);',
    ],
    correctAnswer: 'const doubled = numbers.map(num => num * 2);',
    explanation: 'The `map` method creates a new array populated with the results of calling a provided function on every element in the calling array.',
  },
  {
    id: 'cm-js-medium-02',
    concept: 'Destructuring Assignment',
    description: 'Which snippet correctly extracts the `name` and `age` from the person object?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'let { name, age } = person;',
      'let [name, age] = person;',
      'let name = person.name, age = person.age;',
      'let person = {name, age};',
    ],
    correctAnswer: 'let { name, age } = person;',
    explanation: 'Object destructuring provides a concise way to extract properties from objects and bind them to variables.',
  },
  {
    id: 'cm-js-medium-03',
    concept: 'Ternary Operator',
    description: 'Which snippet correctly assigns a value based on a condition?',
    language: 'javascript',
    difficulty: 'Medium',
    options: [
      'let type = if (age >= 18) "adult" else "minor";',
      'let type = age >= 18 ? "adult" : "minor";',
      'let type = age >= 18 ("adult") || ("minor");',
      'let type = age.isAdult() ? "adult" : "minor";',
    ],
    correctAnswer: 'let type = age >= 18 ? "adult" : "minor";',
    explanation: 'The conditional (ternary) operator is the only JavaScript operator that takes three operands: a condition followed by a question mark (?), then an expression to execute if the condition is truthy followed by a colon (:), and finally the expression to execute if the condition is falsy.',
  },

  // JavaScript - Hard
  {
    id: 'cm-js-hard-01',
    concept: 'Promise',
    description: 'Which snippet correctly creates a promise that resolves after a short delay?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'const promise = new Promise((resolve) => setTimeout(resolve, 100));',
      'const promise = setTimeout(() => Promise.resolve(), 100);',
      'const promise = await setTimeout(100);',
      'const promise = async () => { await 100; };',
    ],
    correctAnswer: 'const promise = new Promise((resolve) => setTimeout(resolve, 100));',
    explanation: 'The `Promise` constructor takes a function (an executor) that is passed `resolve` and `reject` functions. Asynchronous operations like `setTimeout` are placed inside the executor.',
  },
  {
    id: 'cm-js-hard-02',
    concept: 'Closure',
    description: 'Which snippet demonstrates a closure where an inner function has access to the outer function\'s variables?',
    language: 'javascript',
    difficulty: 'Hard',
    options: [
      'function outer() { let a = 1; function inner() { return a; } }',
      'function outer() { let a = 1; } function inner() { return a; }',
      'function outer() { let a = 1; return function inner() { return a; } }',
      'function outer(a) { function inner() { return a; } }',
    ],
    correctAnswer: 'function outer() { let a = 1; return function inner() { return a; } }',
    explanation: 'A closure is the combination of a function bundled together (enclosed) with references to its surrounding state (the lexical environment). The inner function "closes over" the variable `a` from the outer function\'s scope.',
  },

  // Python - Easy
  {
    id: 'cm-py-easy-01',
    concept: 'F-String Formatting',
    description: 'Which snippet correctly formats a string using an f-string?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'print("Name: {name}")',
      'print(f"Name: {name}")',
      'print("Name: %s" % name)',
      'print("Name: " + name)',
    ],
    correctAnswer: 'print(f"Name: {name}")',
    explanation: 'F-strings (formatted string literals) provide a concise and convenient way to embed Python expressions inside string literals for formatting.',
  },
  {
    id: 'cm-py-easy-02',
    concept: 'List Append',
    description: 'Which snippet correctly adds an element to a list?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'my_list.add(4)',
      'my_list.push(4)',
      'my_list.insert(4)',
      'my_list.append(4)',
    ],
    correctAnswer: 'my_list.append(4)',
    explanation: 'The `append()` method is used to add a single item to the end of a list in Python.',
  },
  {
    id: 'cm-py-easy-03',
    concept: 'Dictionary Access',
    description: 'Which snippet correctly accesses the value associated with the key "city"?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'person.get("city")',
      'person["city"]',
      'person.city',
      'person("city")',
    ],
    correctAnswer: 'person["city"]',
    explanation: 'In Python, dictionary values are accessed using square bracket notation with the key inside.',
  },
  {
    id: 'cm-py-easy-04',
    concept: 'Function Definition',
    description: 'Which snippet correctly defines a function named `calculate_sum`?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'function calculate_sum(a, b):',
      'def calculate_sum(a, b):',
      'method calculate_sum(a, b):',
      'define calculate_sum(a, b):',
    ],
    correctAnswer: 'def calculate_sum(a, b):',
    explanation: 'The `def` keyword is used to define a function in Python, followed by the function name and parentheses for parameters.',
  },
  {
    id: 'cm-py-easy-05',
    concept: 'Conditional `if` statement',
    description: 'Which snippet shows a correct if statement to check if a is greater than b?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'if a > b then',
      'if (a > b)',
      'if a > b:',
      'if a > b {}',
    ],
    correctAnswer: 'if a > b:',
    explanation: 'In Python, an `if` statement ends with a colon, and the code to be executed is indented on the next line.',
  },
  {
    id: 'cm-py-easy-06',
    concept: 'Get String Length',
    description: 'Which snippet correctly finds the length of a string?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      's.length()',
      'len(s)',
      's.size()',
      'length(s)',
    ],
    correctAnswer: 'len(s)',
    explanation: 'The built-in `len()` function is used to get the number of items in a sequence, including the number of characters in a string.',
  },
  {
    id: 'cm-py-easy-07',
    concept: 'For Loop',
    description: 'Which snippet correctly iterates through the items of a list named `fruits`?',
    language: 'python',
    difficulty: 'Easy',
    options: [
      'for fruit in fruits:',
      'for each fruit in fruits:',
      'loop fruit in fruits:',
      'for (fruit in fruits):',
    ],
    correctAnswer: 'for fruit in fruits:',
    explanation: 'The `for...in` syntax is used to iterate over the items of any sequence, such as a list or a string.',
  },

  // Python - Medium
  {
    id: 'cm-py-medium-01',
    concept: 'List Comprehension',
    description: 'Which snippet correctly creates a list of squares for even numbers from 0 to 9?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      '[x**2 for x in range(10) if x % 2 == 0]',
      '{x**2 for x in range(10) if x % 2 == 0}',
      'map(lambda x: x**2, filter(lambda x: x % 2 == 0, range(10)))',
      '[for x in range(10): if x % 2 == 0: x**2]',
    ],
    correctAnswer: '[x**2 for x in range(10) if x % 2 == 0]',
    explanation: 'List comprehensions offer a shorter syntax when you want to create a new list based on the values of an existing list, including conditional logic.',
  },
  {
    id: 'cm-py-medium-02',
    concept: '`with` statement',
    description: 'Which snippet shows the correct and safest way to open and read a file?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'file = open("a.txt"); file.read(); file.close()',
      'try: file=open("a.txt"); file.read() finally: file.close()',
      'with open("a.txt") as file: file.read()',
      'read(open("a.txt"))',
    ],
    correctAnswer: 'with open("a.txt") as file: file.read()',
    explanation: 'The `with` statement ensures that the file is automatically closed even if errors occur, making it the preferred way to handle file I/O.',
  },
  {
    id: 'cm-py-medium-03',
    concept: 'Lambda Function',
    description: 'Which snippet defines a small, anonymous function that doubles its input?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'def(x): return x * 2',
      'lambda x: x * 2',
      'anon x: x * 2',
      'function(x) => x * 2',
    ],
    correctAnswer: 'lambda x: x * 2',
    explanation: 'A `lambda` function is a small anonymous function that can take any number of arguments, but can only have one expression.',
  },
  {
    id: 'cm-py-medium-04',
    concept: 'Dictionary `.get()` method',
    description: 'Which snippet safely gets a value from a dictionary, providing a default if the key does not exist?',
    language: 'python',
    difficulty: 'Medium',
    options: [
      'my_dict["key"] or "default"',
      'my_dict.get("key", "default")',
      'my_dict.try_get("key", "default")',
      'my_dict.fetch("key", "default")',
    ],
    correctAnswer: 'my_dict.get("key", "default")',
    explanation: 'The `.get()` method is used to access a dictionary value. It returns a default value (the second argument) if the specified key does not exist, avoiding a KeyError.',
  },

  // Python - Hard
  {
    id: 'cm-py-hard-01',
    concept: 'Decorator',
    description: 'Which snippet correctly defines a simple decorator that wraps another function?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'def decorator(func): return func()',
      'def decorator(func): def wrapper(): print("Wrapped"); func(); return wrapper',
      '@decorator def my_func(): ...',
      'class Decorator: def __call__(self, func): ...',
    ],
    correctAnswer: 'def decorator(func): def wrapper(): print("Wrapped"); func(); return wrapper',
    explanation: 'A decorator is a function that takes another function as an argument, adds some functionality, and returns another function, all without altering the source code of the original function.',
  },
  {
    id: 'cm-py-hard-02',
    concept: 'Generator Function',
    description: 'Which snippet defines a function that can pause and resume, yielding multiple values over time?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'def my_gen(): return [1, 2, 3]',
      'def my_gen(): yield 1; yield 2; yield 3',
      'def my_gen(): print(1); print(2); print(3)',
      'async def my_gen(): return 1, 2, 3',
    ],
    correctAnswer: 'def my_gen(): yield 1; yield 2; yield 3',
    explanation: 'A generator function uses the `yield` keyword to produce a sequence of values. It pauses execution after each yield and resumes from that point on the next call.',
  },
  {
    id: 'cm-py-hard-03',
    concept: 'Class Inheritance',
    description: 'Which snippet correctly shows a `Car` class inheriting from a `Vehicle` class?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'class Car(Vehicle):',
      'class Car inherits Vehicle:',
      'class Car extends Vehicle:',
      'class Car from Vehicle:',
    ],
    correctAnswer: 'class Car(Vehicle):',
    explanation: 'In Python, inheritance is specified by placing the name of the parent class in parentheses after the child class name.',
  },
  {
    id: 'cm-py-hard-04',
    concept: 'Exception Handling',
    description: 'Which snippet shows the correct way to catch a specific type of error?',
    language: 'python',
    difficulty: 'Hard',
    options: [
      'catch ValueError as e:',
      'try: ... except ValueError as e:',
      'except ValueError => e:',
      'on ValueError as e:',
    ],
    correctAnswer: 'try: ... except ValueError as e:',
    explanation: 'The `try...except` block is used for handling exceptions. A specific exception type, like `ValueError`, can be caught and assigned to a variable using the `as` keyword.',
  },

  // Java - Easy
  {
    id: 'cm-java-easy-01',
    concept: 'String Comparison',
    description: 'Which snippet is the correct way to compare the content of two strings?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'if (s1 == s2)',
      'if (s1.equals(s2))',
      'if (s1 === s2)',
      'if (compare(s1, s2))',
    ],
    correctAnswer: 'if (s1.equals(s2))',
    explanation: 'In Java, `==` compares object references. The `.equals()` method must be used to compare the actual character content of strings.',
  },
  {
    id: 'cm-java-easy-02',
    concept: 'Array Declaration',
    description: 'Which snippet correctly declares and initializes an array of integers?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'int numbers = {1, 2, 3};',
      'int[] numbers = [1, 2, 3];',
      'int[] numbers = {1, 2, 3};',
      'Array<int> numbers = {1, 2, 3};',
    ],
    correctAnswer: 'int[] numbers = {1, 2, 3};',
    explanation: 'The correct syntax for declaring and initializing an array in Java uses `type[] name = {values};`.',
  },
  {
    id: 'cm-java-easy-03',
    concept: 'Main Method Signature',
    description: 'Which is the correct signature for the main method, the entry point of a Java application?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'public static void main(String[] args)',
      'public void main(String[] args)',
      'static public main(String[] args)',
      'public static main(string[] args)',
    ],
    correctAnswer: 'public static void main(String[] args)',
    explanation: 'The main method must be `public` (accessible everywhere), `static` (callable without an object), `void` (returns nothing), and take an array of strings as an argument.',
  },
  {
    id: 'cm-java-easy-04',
    concept: 'For Loop',
    description: 'Which snippet shows the correct syntax for a for loop?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'for (i = 0; i < 5; i++)',
      'for i in range(5)',
      'for (int i = 0; i < 5; i++)',
      'foreach (int i in list)',
    ],
    correctAnswer: 'for (int i = 0; i < 5; i++)',
    explanation: 'A standard `for` loop in Java has three parts: initialization, condition, and increment/decrement.',
  },
  {
    id: 'cm-java-easy-05',
    concept: 'String Length',
    description: 'Which snippet correctly gets the number of characters in a string?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      's.length',
      's.length()',
      's.size()',
      'length(s)',
    ],
    correctAnswer: 's.length()',
    explanation: 'In Java, the `length()` method of the String class is used to get the number of characters.',
  },
  {
    id: 'cm-java-easy-06',
    concept: 'Creating an Object',
    description: 'Which snippet correctly creates an instance of a `Car` class?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'Car myCar = new Car();',
      'Car myCar = Car();',
      'new Car() = myCar;',
      'let myCar = new Car();',
    ],
    correctAnswer: 'Car myCar = new Car();',
    explanation: 'To create an object in Java, you specify the class name, a name for the object, and use the `new` keyword followed by a call to the class constructor.',
  },
  {
    id: 'cm-java-easy-07',
    concept: 'Method Definition',
    description: 'Which snippet correctly defines a method that returns an integer?',
    language: 'java',
    difficulty: 'Easy',
    options: [
      'def myMethod() -> int',
      'function myMethod(): int',
      'myMethod(): int',
      'int myMethod()',
    ],
    correctAnswer: 'int myMethod()',
    explanation: 'In Java, a method definition starts with the return type, followed by the method name and parentheses for parameters.',
  },

  // Java - Medium
  {
    id: 'cm-java-medium-01',
    concept: 'Enhanced For-Loop',
    description: 'Which snippet correctly iterates over an ArrayList of Strings?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'for (String s : myList)',
      'for (s in myList)',
      'for (s of myList)',
      'foreach (String s in myList)',
    ],
    correctAnswer: 'for (String s : myList)',
    explanation: 'The enhanced for-loop provides a simpler, more readable way to iterate over elements of a collection or array without needing an index counter.',
  },
  {
    id: 'cm-java-medium-02',
    concept: 'Method Overloading',
    description: 'Which snippet correctly demonstrates method overloading?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'int sum(int a, int b) {}\ndouble sum(int a, int b) {}',
      'int sum(int x, int y) {}\nint sum(int a, int b) {}',
      'int sum(int a, int b) {}\nint sum(int a, int b, int c) {}',
      'int sum(int a, int b) {}\nint calculate(int a, int b) {}',
    ],
    correctAnswer: 'int sum(int a, int b) {}\nint sum(int a, int b, int c) {}',
    explanation: 'Method overloading allows multiple methods with the same name but different parameters (either number of parameters or their types) in the same class.',
  },
  {
    id: 'cm-java-medium-03',
    concept: 'Creating an ArrayList',
    description: 'Which snippet correctly creates an ArrayList to hold strings?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'ArrayList<String> cars = new ArrayList<String>();',
      'List<String> cars = new List();',
      'ArrayList cars = new ArrayList();',
      'ArrayList<String> cars = new ArrayList();',
    ],
    correctAnswer: 'ArrayList<String> cars = new ArrayList<String>();',
    explanation: 'To create an ArrayList, you must import `java.util.ArrayList` and specify the type of objects it will hold in angle brackets `<>`.',
  },
  {
    id: 'cm-java-medium-04',
    concept: 'HashMap',
    description: 'Which snippet correctly creates a HashMap to store String keys and Integer values?',
    language: 'java',
    difficulty: 'Medium',
    options: [
      'HashMap<String, Integer> map = new HashMap<>();',
      'HashMap<String, int> map = new HashMap<>();',
      'Map<String, Integer> map = new Map<>();',
      'HashMap map = new HashMap<String, Integer>();',
    ],
    correctAnswer: 'HashMap<String, Integer> map = new HashMap<>();',
    explanation: 'When using generic collections like HashMap, you must use wrapper classes (like `Integer`) for primitive types (like `int`).',
  },

  // Java - Hard
  {
    id: 'cm-java-hard-01',
    concept: 'Interface Implementation',
    description: 'Which snippet shows a class correctly implementing an interface?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'class Car extends Drivable {}',
      'class Car inherits Drivable {}',
      'class Car uses Drivable {}',
      'class Car implements Drivable {}',
    ],
    correctAnswer: 'class Car implements Drivable {}',
    explanation: 'A class uses the `implements` keyword to use an interface. It must then provide an implementation for all the methods defined in that interface.',
  },
  {
    id: 'cm-java-hard-02',
    concept: 'Exception Handling',
    description: 'Which snippet correctly handles a potential file reading error?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'try { readFile(); } catch (IOException e) { ... }',
      'if (readFile()) { ... } else { ... }',
      'on (error) { ... }',
      'throws IOException { readFile(); }',
    ],
    correctAnswer: 'try { readFile(); } catch (IOException e) { ... }',
    explanation: 'The `try...catch` block is the standard way to handle exceptions in Java. Code that might throw an exception is placed in the `try` block, and the code to handle it is in the `catch` block.',
  },
  {
    id: 'cm-java-hard-03',
    concept: 'Polymorphism',
    description: 'Which snippet demonstrates polymorphism?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'Animal myAnimal = new Animal();',
      'Animal myDog = new Dog();',
      'Dog myDog = new Animal();',
      'Dog myDog = (Dog) new Animal();',
    ],
    correctAnswer: 'Animal myDog = new Dog();',
    explanation: 'Polymorphism means "many forms". It allows us to perform a single action in different ways. Here, a `Dog` object (a subclass) is being referred to by a variable of its superclass type, `Animal`.',
  },
  {
    id: 'cm-java-hard-04',
    concept: 'Lambda Expression',
    description: 'Which snippet correctly uses a lambda expression to iterate over a list?',
    language: 'java',
    difficulty: 'Hard',
    options: [
      'list.forEach(item -> System.out.println(item));',
      'list.forEach(item => System.out.println(item));',
      'for (item : list) -> System.out.println(item);',
      'lambda item in list: System.out.println(item);',
    ],
    correctAnswer: 'list.forEach(item -> System.out.println(item));',
    explanation: 'Lambda expressions provide a clear and concise way to represent one method interface using an expression. The `->` separates the parameters from the expression body.',
  },

  // C++ - Easy
  {
    id: 'cm-cpp-easy-01',
    concept: 'Include Directive',
    description: 'Which snippet correctly includes the library for input and output streams?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'import <iostream>;',
      '#include <iostream>',
      '#import <iostream>',
      'include <iostream>;',
    ],
    correctAnswer: '#include <iostream>',
    explanation: 'In C++, the `#include` preprocessor directive is used to include the contents of a header file in the current source file.',
  },
  {
    id: 'cm-cpp-easy-02',
    concept: 'Pointer Dereference',
    description: 'Which snippet correctly gets the value stored at the memory address held by a pointer?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'value = &ptr;',
      'value = *ptr;',
      'value = ptr.value;',
      'value = ptr->value;',
    ],
    correctAnswer: 'value = *ptr;',
    explanation: 'The dereference operator `*` is used to access the value that a pointer points to.',
  },
  {
    id: 'cm-cpp-easy-03',
    concept: 'Reference Variable',
    description: 'Which snippet correctly declares a reference to another variable?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int &ref = original;',
      'int *ref = original;',
      'ref<int> = original;',
      'reference int ref = original;',
    ],
    correctAnswer: 'int &ref = original;',
    explanation: 'In C++, a reference is an alias for an already existing variable. It is declared using the ampersand `&` symbol.',
  },
  {
    id: 'cm-cpp-easy-04',
    concept: 'Using Namespace',
    description: 'Which snippet allows you to use names for objects and variables from the standard library without the `std::` prefix?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'import namespace std;',
      'using namespace std;',
      'namespace(std);',
      'std::use();',
    ],
    correctAnswer: 'using namespace std;',
    explanation: 'The `using namespace std;` statement allows you to use elements from the `std` namespace directly, like `cout` instead of `std::cout`.',
  },
  {
    id: 'cm-cpp-easy-05',
    concept: 'Array Declaration',
    description: 'Which snippet correctly declares an array of 4 integers?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'int arr[4];',
      'int arr = new int[4];',
      'Array<int> arr(4);',
      'vector<int> arr(4);',
    ],
    correctAnswer: 'int arr[4];',
    explanation: 'In C++, a static array is declared with the syntax `type name[size];`.',
  },
  {
    id: 'cm-cpp-easy-06',
    concept: 'Get String Length',
    description: 'Which snippet correctly gets the length of a `std::string`?',
    language: 'cpp',
    difficulty: 'Easy',
    options: [
      'len(myString)',
      'myString.length',
      'myString.length()',
      'sizeof(myString)',
    ],
    correctAnswer: 'myString.length()',
    explanation: 'The `std::string` class has a `length()` (or `size()`) method that returns the number of characters in the string.',
  },

  // C++ - Medium
  {
    id: 'cm-cpp-medium-01',
    concept: 'Range-based For Loop',
    description: 'Which snippet correctly iterates over the elements of a vector?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'for (int i : my_vector)',
      'for (int i = 0; i < my_vector.size(); i++)',
      'my_vector.forEach(i => ...)',
      'for (i in my_vector)',
    ],
    correctAnswer: 'for (int i : my_vector)',
    explanation: 'The range-based for loop (since C++11) provides a more concise and less error-prone way to iterate over the elements of a container.',
  },
  {
    id: 'cm-cpp-medium-02',
    concept: 'Class Constructor',
    description: 'Which snippet correctly defines a constructor for the `Car` class?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'void Car() { ... }',
      'Car() { ... }',
      'construct Car() { ... }',
      'def Car() { ... }',
    ],
    correctAnswer: 'Car() { ... }',
    explanation: 'A constructor in C++ is a special member function that has the same name as the class and is called when an object of the class is created. It has no return type.',
  },
  {
    id: 'cm-cpp-medium-03',
    concept: 'Header Guards',
    description: 'Which snippet represents a standard header guard to prevent multiple inclusions?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      '#once',
      '#guard MY_HEADER_H',
      '#ifdef MY_HEADER_H',
      '#ifndef MY_HEADER_H\n#define MY_HEADER_H\n...\n#endif',
    ],
    correctAnswer: '#ifndef MY_HEADER_H\n#define MY_HEADER_H\n...\n#endif',
    explanation: 'Header guards are preprocessor directives that prevent the contents of a header from being included more than once in a single compilation unit, which would cause redefinition errors.',
  },
  {
    id: 'cm-cpp-medium-04',
    concept: 'Dynamic Memory Allocation',
    description: 'Which snippet correctly allocates an integer on the heap?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'int* p = new int;',
      'int p = new int;',
      'int* p = malloc(sizeof(int));',
      'new int* p;',
    ],
    correctAnswer: 'int* p = new int;',
    explanation: 'The `new` operator is used in C++ to allocate memory on the heap. It returns a pointer to the allocated memory.',
  },
  {
    id: 'cm-cpp-medium-05',
    concept: 'Function Overloading',
    description: 'Which snippet correctly demonstrates function overloading?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'int print(int i){}\nfloat print(int i){}',
      'int print(int i){}\nint print(int j){}',
      'int print(int i){}\nint print(double d){}',
      'int print(int i){}\nint show(int i){}',
    ],
    correctAnswer: 'int print(int i){}\nint print(double d){}',
    explanation: 'Function overloading allows multiple functions to have the same name as long as they have different parameter lists (either different types or a different number of parameters).',
  },
  {
    id: 'cm-cpp-medium-06',
    concept: 'Passing by Reference',
    description: 'Which function signature correctly takes an integer by reference?',
    language: 'cpp',
    difficulty: 'Medium',
    options: [
      'void func(int* x)',
      'void func(int& x)',
      'void func(ref int x)',
      'void func(int x)',
    ],
    correctAnswer: 'void func(int& x)',
    explanation: 'Using `&` after the type in a function parameter list declares that the argument should be passed by reference, allowing the function to modify the original variable.',
  },
    
  // C++ - Hard
  {
    id: 'cm-cpp-hard-01',
    concept: 'Virtual Function (Polymorphism)',
    description: 'Which snippet correctly declares a function that can be overridden by a derived class to enable polymorphism?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'override void makeSound() {}',
      'dynamic void makeSound() {}',
      'virtual void makeSound() {}',
      'poly void makeSound() {}',
    ],
    correctAnswer: 'virtual void makeSound() {}',
    explanation: 'The `virtual` keyword is used to declare a member function in a base class that you expect to be redefined in derived classes. This is fundamental to achieving runtime polymorphism in C++.',
  },
  {
    id: 'cm-cpp-hard-02',
    concept: 'Template Function',
    description: 'Which snippet defines a generic function that can operate on different data types?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'generic<T> T add(T a, T b) {}',
      'template<typename T> T add(T a, T b) {}',
      'function<T> add(T a, T b) {}',
      'auto add(auto a, auto b) {}',
    ],
    correctAnswer: 'template<typename T> T add(T a, T b) {}',
    explanation: 'Templates allow you to write generic programs. The `template<typename T>` syntax declares a template where `T` is a placeholder for a data type that will be specified when the function is called.',
  },
  {
    id: 'cm-cpp-hard-03',
    concept: 'The "Rule of Three/Five"',
    description: 'If a class has a user-defined destructor, which other members should it typically also define?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'A constructor and a static method',
      'A copy constructor and a copy assignment operator',
      'A `begin()` and `end()` method',
      'A virtual constructor',
    ],
    correctAnswer: 'A copy constructor and a copy assignment operator',
    explanation: 'The Rule of Three (or Five in modern C++) is a rule of thumb stating that if a class defines any of a destructor, copy constructor, or copy assignment operator, it should probably define all three (plus move constructor and move assignment).',
  },
  {
    id: 'cm-cpp-hard-04',
    concept: 'RAII (Resource Acquisition Is Initialization)',
    description: 'Which snippet best demonstrates the RAII idiom for managing a resource?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'int* p = new int; delete p;',
      'std::shared_ptr<int> p(new int);',
      'FILE* f = fopen(...); fclose(f);',
      'lock(); unlock();',
    ],
    correctAnswer: 'std::shared_ptr<int> p(new int);',
    explanation: 'RAII is a core C++ concept where resource lifetime is tied to object lifetime. Smart pointers like `std::shared_ptr` acquire the resource (memory) on construction and automatically release it on destruction, preventing leaks.',
  },
  {
    id: 'cm-cpp-hard-05',
    concept: 'Lambda Function with Capture',
    description: 'Which snippet shows a lambda that captures an external variable by value?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'auto my_lambda = [](int x) { return x + y; };',
      'auto my_lambda = [=](int x) { return x + y; };',
      'auto my_lambda = (&)(int x) { return x + y; };',
      'auto my_lambda = (int y, int x) { return x + y; };',
    ],
    correctAnswer: 'auto my_lambda = [=](int x) { return x + y; };',
    explanation: 'The `[...]` part of a lambda is the capture clause. `[=]` captures all automatic variables used in the lambda by value, making a copy of them.',
  },
  {
    id: 'cm-cpp-hard-06',
    concept: 'Pure Virtual Function',
    description: 'Which snippet defines an abstract base class that cannot be instantiated?',
    language: 'cpp',
    difficulty: 'Hard',
    options: [
      'class Shape { public: virtual void draw() = 0; };',
      'class Shape { public: abstract void draw(); };',
      'class Shape { public: virtual void draw() {}; };',
      'class Shape = 0 { ... };',
    ],
    correctAnswer: 'class Shape { public: virtual void draw() = 0; };',
    explanation: 'A pure virtual function is declared by assigning `= 0`. A class containing at least one pure virtual function is an abstract class, and no objects of that class can be created.',
  },
  {
    id: 'cm-js-hard-03',
    concept: 'Simple Promise',
    description: 'Create a promise that resolves after a delay.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const myPromise = new Promise((resolve, reject) => {',
      '  setTimeout(() => {',
      '    resolve("Success!");',
      '  }, 1000);',
      '});',
      'myPromise.then((message) => {',
      '  console.log(message);',
      '});',
    ],
  },
  {
    id: 'cm-js-hard-04',
    concept: 'Simple Closure',
    description: 'Create a function that demonstrates closure.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'function makeCounter() {',
      '  let count = 0;',
      '  return function() {',
      '    count++;',
      '    return count;',
      '  };',
      '}',
      'const counter = makeCounter();',
    ],
  },
    {
    id: 'cm-js-hard-05',
    concept: 'Event Listener',
    description: 'Add a click event listener to a button element.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const button = document.getElementById("myButton");',
      'button.addEventListener("click", () => {',
      '  alert("Button was clicked!");',
      '});',
    ],
  },
  {
    id: 'cm-js-hard-06',
    concept: 'JSON stringify',
    description: 'Convert a JavaScript object to a JSON string.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const data = { name: "John", age: 30 };',
      'const jsonString = JSON.stringify(data);',
      'console.log(jsonString);',
    ],
  },
  {
    id: 'cm-js-hard-07',
    concept: 'JSON parse',
    description: 'Parse a JSON string into a JavaScript object.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const jsonString = \'{"name":"John", "age":30}\';',
      'const data = JSON.parse(jsonString);',
      'console.log(data.name);',
    ],
  },
  {
    id: 'cm-js-hard-08',
    concept: 'Try...Catch Block',
    description: 'Handle a potential runtime error gracefully.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  console.log(nonExistentVariable);',
      '} catch (error) {',
      '  console.error("An error occurred:", error.message);',
      '}',
    ],
  },
  {
    id: 'cm-js-hard-09',
    concept: 'Class Inheritance',
    description: 'Create a class that inherits from another class.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal {',
      '  constructor(name) { this.name = name; }',
      '  speak() { console.log(`${this.name} makes a sound.`); }',
      '}',
      'class Dog extends Animal {',
      '  speak() { console.log(`${this.name} barks.`); }',
      '}',
    ],
  },
  {
    id: 'cm-js-hard-10',
    concept: 'Spread Operator',
    description: 'Use the spread operator to combine arrays and objects.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const arr1 = [1, 2];',
      'const arr2 = [...arr1, 3, 4];',
      'const obj1 = {a: 1};',
      'const obj2 = {...obj1, b: 2};',
    ],
  },

  // Python - Easy
  {
    id: 'cm-py-easy-08',
    title: 'List Append',
    description: 'Add an item to the end of a list.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'my_list = [1, 2, 3]',
      'my_list.append(4)',
      'print(my_list)',
    ],
  },
  {
    id: 'cm-py-easy-09',
    title: 'String Formatting',
    description: 'Format a string using an f-string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = "World"',
      'greeting = f"Hello, {name}!"',
      'print(greeting)',
    ],
  },
  {
    id: 'cm-py-easy-10',
    title: 'Dictionary Access',
    description: 'Access a value in a dictionary by its key.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'car = {"brand": "Ford", "model": "Mustang"}',
      'brand_name = car["brand"]',
      'print(brand_name)',
    ],
  },

  // Python - Medium
  {
    id: 'cm-py-medium-05',
    title: 'Lambda Function',
    description: 'Use a lambda function to sort a list of tuples.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'points = [(1, 2), (3, 1), (5, 4)]',
      'points.sort(key=lambda x: x[1])',
      'print(points)',
    ],
  },
  {
    id: 'cm-py-medium-06',
    title: 'Exception Handling',
    description: 'Handle a potential ZeroDivisionError.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'try:',
      '    result = 10 / 0',
      'except ZeroDivisionError:',
      '    print("Cannot divide by zero!")',
    ],
  },
  {
    id: 'cm-py-medium-07',
    title: 'Import Module',
    description: 'Import the `math` module and use a function from it.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'import math',
      'result = math.sqrt(16)',
      'print(result)',
    ],
  },
  {
    id: 'cm-py-medium-08',
    title: 'Slicing a String',
    description: 'Extract a substring using slicing.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'b = "Hello, World!"',
      'print(b[2:5])',
    ],
  },
  {
    id: 'cm-py-medium-09',
    title: 'Check if Item in List',
    description: 'Check if a specific item exists in a list.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'thislist = ["apple", "banana", "cherry"]',
      'if "apple" in thislist:',
      '  print("Yes, \'apple\' is in the fruits list")',
    ],
  },
  {
    id: 'cm-py-medium-10',
    title: 'Default Parameter Value',
    description: 'Define a function with a default parameter value.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'def my_function(country = "Norway"):',
      '  print("I am from " + country)',
      'my_function("Sweden")',
      'my_function()',
    ],
  },

  // Python - Hard
  {
    id: 'cm-py-hard-05',
    title: 'File Writing',
    description: 'Open a file for writing and add content to it.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'with open("test.txt", "w") as f:',
      '    f.write("First line.\\n")',
      '    f.write("Second line.\\n")',
    ],
  },
  {
    id: 'cm-py-hard-06',
    title: 'Set Operations',
    description: 'Find the intersection of two sets.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'set1 = {1, 2, 3, 4}',
      'set2 = {3, 4, 5, 6}',
      'intersection = set1.intersection(set2)',
      'print(intersection)',
    ],
  },
  {
    id: 'cm-py-hard-07',
    title: 'Recursion',
    description: 'Calculate factorial using recursion.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def factorial(n):',
      '    if n == 1:',
      '        return 1',
      '    else:',
      '        return n * factorial(n-1)',
    ],
  },
  {
    id: 'cm-py-hard-08',
    title: 'Reading JSON file',
    description: 'Load data from a JSON file.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import json',
      'with open("data.json", "r") as f:',
      '    data = json.load(f)',
      'print(data)',
    ],
  },
  {
    id: 'cm-py-hard-09',
    title: 'Regular Expression',
    description: 'Use the `re` module to find a pattern in a string.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import re',
      'txt = "The rain in Spain"',
      'x = re.search("^The.*Spain$", txt)',
      'if x:',
      '  print("Match found!")',
    ],
  },
  {
    id: 'cm-py-hard-10',
    title: 'Filter Function',
    description: 'Use the filter() function to get only adult ages.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'ages = [5, 12, 17, 18, 24, 32]',
      'def myFunc(x):',
      '  if x < 18:',
      '    return False',
      '  else:',
      '    return True',
      'adults = filter(myFunc, ages)',
    ],
  },

  // Java - Easy
  {
    id: 'cm-java-easy-08',
    title: 'String Concatenation',
    description: 'Combine two strings.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String firstName = "John ";',
      'String lastName = "Doe";',
      'System.out.println(firstName.concat(lastName));',
    ],
  },
  {
    id: 'cm-java-easy-09',
    title: 'Math.max()',
    description: 'Find the highest value of two numbers.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int x = 5;',
      'int y = 10;',
      'System.out.println(Math.max(x, y));',
    ],
  },
  
  // Java - Medium
  {
    id: 'cm-java-medium-05',
    title: 'Enhanced For Loop',
    description: 'Iterate over an array using the enhanced for loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'for (String i : cars) {',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    id: 'cm-java-medium-06',
    title: 'Switch Statement',
    description: 'Use a switch statement to select a block of code to be executed.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 1:',
      '    System.out.println("Monday");',
      '    break;',
      '  default:',
      '    System.out.println("Some other day");',
      '}',
    ],
  },
  {
    id: 'cm-java-medium-07',
    title: 'While loop',
    description: 'Print numbers using a while loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int i = 0;',
      'while (i < 5) {',
      '  System.out.println(i);',
      '  i++;',
      '}',
    ],
  },
  {
    id: 'cm-java-medium-08',
    title: 'Break Statement',
    description: 'Stop a loop if a certain condition is met.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'for (int i = 0; i < 10; i++) {',
      '  if (i == 4) {',
      '    break;',
      '  }',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    id: 'cm-java-medium-09',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String txt = "Hello";',
      'System.out.println("The length is: " + txt.length());',
    ],
  },

  // Java - Hard
  {
    id: 'cm-java-hard-05',
    title: 'Inheritance',
    description: 'Create a subclass that inherits from a superclass.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Vehicle { protected String brand = "Ford"; }',
      'class Car extends Vehicle {',
      '  private String modelName = "Mustang";',
      '}',
    ],
  },
  {
    id: 'cm-java-hard-06',
    title: 'Polymorphism',
    description: 'Demonstrate polymorphism with a base and derived classes.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal { public void animalSound() { System.out.println("The animal makes a sound"); } }',
      'class Pig extends Animal { public void animalSound() { System.out.println("The pig says: wee wee"); } }',
      'class Dog extends Animal { public void animalSound() { System.out.println("The dog says: bow wow"); } }',
    ],
  },
  {
    id: 'cm-java-hard-07',
    title: 'Interface Implementation',
    description: 'Implement an interface in a class.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'interface Animal { public void animalSound(); }',
      'class Pig implements Animal {',
      '  public void animalSound() { System.out.println("wee wee"); }',
      '}',
    ],
  },
  {
    id: 'cm-java-hard-08',
    title: 'Exception Handling',
    description: 'Use a try-catch block to handle an error.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int[] myNumbers = {1, 2, 3};',
      '  System.out.println(myNumbers[10]);',
      '} catch (Exception e) {',
      '  System.out.println("Something went wrong.");',
      '}',
    ],
  },
  {
    id: 'cm-java-hard-09',
    title: 'Regular Expression',
    description: 'Use regex to find a pattern in a string.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.regex.Matcher;',
      'import java.util.regex.Pattern;',
      'Pattern pattern = Pattern.compile("w3schools", Pattern.CASE_INSENSITIVE);',
      'Matcher matcher = pattern.matcher("Visit W3Schools!");',
      'boolean matchFound = matcher.find();',
    ],
  },
  {
    id: 'cm-java-hard-10',
    title: 'Lambda Expression',
    description: 'Use a lambda expression to iterate over an ArrayList.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'ArrayList<Integer> numbers = new ArrayList<Integer>();',
      'numbers.add(5);',
      'numbers.add(9);',
      'numbers.forEach( (n) -> { System.out.println(n); } );',
    ],
  },


  // C++ - Easy
  {
    id: 'cm-cpp-easy-07',
    title: 'Simple if statement',
    description: 'Check if one number is greater than another.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int x = 20;',
      'int y = 18;',
      'if (x > y) {',
      '  std::cout << "x is greater than y";',
      '}',
    ],
  },
  {
    id: 'cm-cpp-easy-08',
    title: 'Function Declaration',
    description: 'Declare a function that can be called later.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'void myFunction();',
      'int main() {',
      '  myFunction();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'cm-cpp-easy-09',
    title: 'Switch Statement',
    description: 'Use a switch statement for control flow.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 4:',
      '    std::cout << "Thursday";',
      '    break;',
      '}',
    ],
  },

  // C++ - Medium
  {
    id: 'cm-cpp-medium-07',
    title: 'Function with Parameters',
    description: 'Define a function that takes arguments.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'void myFunction(std::string fname) {',
      '  std::cout << fname << " Doe\\n";',
      '}',
      'int main() {',
      '  myFunction("John");',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'cm-cpp-medium-08',
    title: 'Function Overloading',
    description: 'Define two functions with the same name but different parameters.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int plusFunc(int x, int y) { return x + y; }',
      'double plusFunc(double x, double y) { return x + y; }',
    ],
  },
  {
    id: 'cm-cpp-medium-09',
    title: 'Recursion',
    description: 'Use recursion to calculate a sum.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int sum(int k) {',
      '  if (k > 0) {',
      '    return k + sum(k - 1);',
      '  } else {',
      '    return 0;',
      '  }',
      '}',
    ],
  },
  {
    id: 'cm-cpp-medium-10',
    title: 'Range-based for loop',
    description: 'Iterate over an array using a range-based for loop.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int myNumbers[5] = {10, 20, 30, 40, 50};',
      'for (int i : myNumbers) {',
      '  std::cout << i << "\\n";',
      '}',
    ],
  },

  // C++ - Hard
  {
    id: 'cm-cpp-hard-07',
    title: 'Exception Handling',
    description: 'Use a try/catch block to handle a potential error.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int age = 15;',
      '  if (age >= 18) {',
      '    std::cout << "Access granted.";',
      '  } else {',
      '    throw 505;',
      '  }',
      '}',
      'catch (int myNum) {',
      '  std::cout << "Access denied.";',
      '}',
    ],
  },
  {
    id: 'cm-cpp-hard-08',
    title: 'Structs',
    description: 'Define and use a simple struct.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'struct {',
      '  int myNum;',
      '  std::string myString;',
      '} myStructure;',
      'myStructure.myNum = 1;',
      'myStructure.myString = "Hello";',
    ],
  },
  {
    id: 'cm-cpp-hard-09',
    title: 'Pass by Reference',
    description: 'Pass arguments to a function by reference.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'void swapNums(int &x, int &y) {',
      '  int z = x;',
      '  x = y;',
      '  y = z;',
      '}',
    ],
  },
  {
    id: 'cm-cpp-hard-10',
    title: 'Read a File',
    description: 'Read the contents of a text file line by line.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <fstream>',
      '#include <string>',
      'std::string myText;',
      'std::ifstream MyReadFile("filename.txt");',
      'while (getline (MyReadFile, myText)) {',
      '  std::cout << myText;',
      '}',
      'MyReadFile.close();',
    ],
  },
  {
    id: 'cm-cpp-hard-11',
    title: 'Encapsulation',
    description: 'Demonstrate encapsulation by using public and private access specifiers.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'class Employee {',
      '  private:',
      '    int salary;',
      '  public:',
      '    void setSalary(int s) { salary = s; }',
      '    int getSalary() { return salary; }',
      '};',
    ],
  },
  {
    id: 'cm-cpp-hard-12',
    title: 'Get Array Size',
    description: 'Calculate the size of an array.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'int myNumbers[5] = {10, 20, 30, 40, 50};',
      'int size = sizeof(myNumbers) / sizeof(int);',
      'std::cout << size;',
    ],
  }
];

export function getConceptMatchChallengeById(id: string): ConceptMatchChallenge | undefined {
    return conceptMatchChallenges.find(c => c.id === id);
}

    