
export interface DebugChallenge {
  id: string;
  title: string;
  description: string;
  buggyCode: string;
  fixedCode: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

export const debugChallenges: DebugChallenge[] = [
  // JavaScript - Easy
  {
    id: 'dc-js-easy-001',
    title: 'Simple Addition',
    description: 'This function should add two numbers, but it\'s returning a string instead.',
    buggyCode: `function add(a, b) {\n  return a + "b";\n}`,
    fixedCode: `function add(a, b) {\n  return a + b;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-002',
    title: 'Loop Condition',
    description: 'This loop should print numbers from 0 to 4, but it\'s an infinite loop!',
    buggyCode: `for (let i = 0; i < 5; i--) {\n  console.log(i);\n}`,
    fixedCode: `for (let i = 0; i < 5; i++) {\n  console.log(i);\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-003',
    title: 'Object Property Access',
    description: 'The function should return the name of the user object.',
    buggyCode: `function getUserName(user) {\n  return user.namee;\n}`,
    fixedCode: `function getUserName(user) {\n  return user.name;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
    {
    id: 'dc-js-easy-004',
    title: 'Equality Check',
    description: 'The function should check for strict equality, but it\'s using loose equality.',
    buggyCode: `function isEqual(a, b) {\n  return a == b;\n}`,
    fixedCode: `function isEqual(a, b) {\n  return a === b;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-005',
    title: 'Function Call',
    description: 'This function is defined but never called.',
    buggyCode: `function showMessage() {\n  return "Hello World";\n}\n\nlet message = showMessage;`,
    fixedCode: `function showMessage() {\n  return "Hello World";\n}\n\nlet message = showMessage();`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-006',
    title: 'Variable Scope',
    description: 'The variable is declared inside the if-block and not accessible outside.',
    buggyCode: `function getStatus(isOnline) {\n  if (isOnline) {\n    const status = "Online";\n  }\n  return status;\n}`,
    fixedCode: `function getStatus(isOnline) {\n  let status = "Offline";\n  if (isOnline) {\n    status = "Online";\n  }\n  return status;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-007',
    title: 'Array Push Return',
    description: '`array.push()` returns the new length of the array, not the array itself.',
    buggyCode: `function addToList(list, item) {\n  return list.push(item);\n}`,
    fixedCode: `function addToList(list, item) {\n  list.push(item);\n  return list;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-008',
    title: 'String Immutability',
    description: 'Strings are immutable in JavaScript. Methods like `toUpperCase()` return a new string.',
    buggyCode: `let name = "alice";\nname.toUpperCase();\nconsole.log(name);`,
    fixedCode: `let name = "alice";\nname = name.toUpperCase();\nconsole.log(name);`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-009',
    title: 'Incorrect Parameter',
    description: 'The function is called with the wrong variable.',
    buggyCode: `function greet(name) {\n  return "Hello " + name;\n}\nlet user = "Bob";\ngreet(person);`,
    fixedCode: `function greet(name) {\n  return "Hello " + name;\n}\nlet user = "Bob";\ngreet(user);`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-010',
    title: 'Missing return',
    description: 'The function should return a value but has no return statement.',
    buggyCode: `function getDouble(num) {\n  const result = num * 2;\n}`,
    fixedCode: `function getDouble(num) {\n  const result = num * 2;\n  return result;\n}`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-011',
    title: 'Array Length Property',
    description: 'To get the number of elements in an array, use the `.length` property, not the `.length()` method.',
    buggyCode: `const myArray = [1, 2, 3];\nconst len = myArray.length();`,
    fixedCode: `const myArray = [1, 2, 3];\nconst len = myArray.length;`,
    language: 'javascript',
    difficulty: 'Easy',
  },
  {
    id: 'dc-js-easy-012',
    title: 'Case Sensitivity',
    description: 'JavaScript is case-sensitive. `Console.log` is not the same as `console.log`.',
    buggyCode: `Console.log("Hello");`,
    fixedCode: `console.log("Hello");`,
    language: 'javascript',
    difficulty: 'Easy',
  },

  // JavaScript - Medium
  {
    id: 'dc-js-medium-001',
    title: 'Array Indexing',
    description: 'This function should return the first element of the array.',
    buggyCode: `function getFirstElement(arr) {\n  return arr[1];\n}`,
    fixedCode: `function getFirstElement(arr) {\n  return arr[0];\n}`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-002',
    title: 'Async Await',
    description: 'This async function is not correctly waiting for the promise to resolve.',
    buggyCode: `async function fetchData() {\n  const data = fetch('https://api.example.com/data');\n  return data.json();\n}`,
    fixedCode: `async function fetchData() {\n  const response = await fetch('https://api.example.com/data');\n  return response.json();\n}`,
    language: 'javascript',
    difficulty: 'Medium',
  },
   {
    id: 'dc-js-medium-003',
    title: 'Array Map Usage',
    description: 'The `map` function should return the new value in the callback.',
    buggyCode: `const numbers = [1, 2, 3];\nconst doubled = numbers.map((num) => {\n  num * 2;\n});`,
    fixedCode: `const numbers = [1, 2, 3];\nconst doubled = numbers.map((num) => {\n  return num * 2;\n});`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-004',
    title: 'Object Reference vs Copy',
    description: 'Modifying the `copy` object is also modifying the `original` object.',
    buggyCode: `const original = { value: 10 };\nconst copy = original;\ncopy.value = 20;`,
    fixedCode: `const original = { value: 10 };\nconst copy = { ...original };\ncopy.value = 20;`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-005',
    title: 'Array Splice Mutation',
    description: '`splice` mutates the original array, causing the loop to skip elements.',
    buggyCode: `let nums = [1, 2, 3, 4];\nfor (let i = 0; i < nums.length; i++) {\n  if (nums[i] % 2 === 0) {\n    nums.splice(i, 1);\n  }\n}`,
    fixedCode: `let nums = [1, 2, 3, 4];\nfor (let i = nums.length - 1; i >= 0; i--) {\n  if (nums[i] % 2 === 0) {\n    nums.splice(i, 1);\n  }\n}`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-006',
    title: 'Event Listener Removal',
    description: 'To remove an event listener, you must pass the exact same function reference, not a new anonymous function.',
    buggyCode: `const btn = document.getElementById('myBtn');\nbtn.addEventListener('click', () => console.log('Hi'));\nbtn.removeEventListener('click', () => console.log('Hi'));`,
    fixedCode: `const btn = document.getElementById('myBtn');\nconst listener = () => console.log('Hi');\nbtn.addEventListener('click', listener);\nbtn.removeEventListener('click', listener);`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-007',
    title: 'Date Object Month',
    description: 'The `getMonth()` method in JavaScript is 0-indexed (0=January, 11=December).',
    buggyCode: `const d = new Date('2023-01-15'); // January\nif (d.getMonth() === 1) { console.log('Jan'); }`,
    fixedCode: `const d = new Date('2023-01-15'); // January\nif (d.getMonth() === 0) { console.log('Jan'); }`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-008',
    title: 'parseInt Radix',
    description: '`parseInt` can misinterpret numbers with leading zeros if a radix (base) is not specified.',
    buggyCode: `const val = parseInt("010"); // May be 8 in some engines`,
    fixedCode: `const val = parseInt("010", 10); // Guaranteed to be 10`,
    language: 'javascript',
    difficulty: 'Medium',
  },
    {
    id: 'dc-js-medium-009',
    title: '`sort()` with Numbers',
    description: 'The default `sort()` method sorts elements as strings. A compare function is needed for numeric sort.',
    buggyCode: `const numbers = [10, 5, 2, 12];\nnumbers.sort(); // [10, 12, 2, 5]`,
    fixedCode: `const numbers = [10, 5, 2, 12];\nnumbers.sort((a, b) => a - b); // [2, 5, 10, 12]`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-010',
    title: 'Array `filter()` Return',
    description: 'The `filter` callback must return a boolean value indicating whether to keep the element.',
    buggyCode: `const arr = [1, 2, 3, 4];\nconst evens = arr.filter(n => { n % 2 === 0; });`,
    fixedCode: `const arr = [1, 2, 3, 4];\nconst evens = arr.filter(n => n % 2 === 0);`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  {
    id: 'dc-js-medium-011',
    title: '`this` in a Callback',
    description: 'In a regular function callback, `this` loses its original context. An arrow function is needed to preserve it.',
    buggyCode: `function Counter() {\n  this.count = 0;\n  setInterval(function() {\n    this.count++;\n  }, 1000);\n}`,
    fixedCode: `function Counter() {\n  this.count = 0;\n  setInterval(() => {\n    this.count++;\n  }, 1000);\n}`,
    language: 'javascript',
    difficulty: 'Medium',
  },
  
  // JavaScript - Hard
  {
    id: 'dc-js-hard-001',
    title: 'Shallow Copy Object',
    description: 'This function is supposed to deep clone an object, but modifying the nested object in the clone also modifies the original.',
    buggyCode: `function clone(obj) {\n  return Object.assign({}, obj);\n}`,
    fixedCode: `function clone(obj) {\n  return JSON.parse(JSON.stringify(obj));\n}`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-002',
    title: 'The `this` keyword context',
    description: 'The `this` inside the `setTimeout` refers to the global object (window), not the `user` object.',
    buggyCode: `const user = {\n  name: 'Alice',\n  greet: function() {\n    setTimeout(function() {\n      console.log('Hello, ' + this.name);\n    }, 1000);\n  }\n};`,
    fixedCode: `const user = {\n  name: 'Alice',\n  greet: function() {\n    setTimeout(() => {\n      console.log('Hello, ' + this.name);\n    }, 1000);\n  }\n};`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-003',
    title: 'Closure Loop Problem',
    description: 'By the time the `setTimeout` callbacks run, the loop has completed and `i` is 5.',
    buggyCode: `for (var i = 0; i < 5; i++) {\n  setTimeout(function() {\n    console.log(i);\n  }, 100);\n}`,
    fixedCode: `for (let i = 0; i < 5; i++) {\n  setTimeout(function() {\n    console.log(i);\n  }, 100);\n}`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-004',
    title: 'Promise Chain',
    description: 'The second `.then` receives `undefined` because the first one doesn\'t return a value.',
    buggyCode: `Promise.resolve(10)\n  .then(val => { val * 2; })\n  .then(val => console.log(val));`,
    fixedCode: `Promise.resolve(10)\n  .then(val => val * 2)\n  .then(val => console.log(val));`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-005',
    title: 'Race Condition',
    description: 'Two async functions modify the same variable, leading to a race condition. The final value is unpredictable.',
    buggyCode: `let balance = 100;\nasync function withdraw(amount) { balance -= amount; }\nasync function deposit(amount) { balance += amount; }\nwithdraw(20);\ndeposit(50);`,
    fixedCode: `let balance = 100;\nasync function withdraw(amount) { balance -= amount; }\nasync function deposit(amount) { balance += amount; }\nasync function transaction() {\n  await withdraw(20);\n  await deposit(50);\n}\ntransaction();`,
    language: 'javascript',
    difficulty: 'Hard',
  },
    {
    id: 'dc-js-hard-006',
    title: 'Floating Point Precision',
    description: 'Classic floating point math problem. 0.1 + 0.2 does not equal 0.3.',
    buggyCode: `function checkSum() {\n  return 0.1 + 0.2 === 0.3;\n}`,
    fixedCode: `function checkSum() {\n  return Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON;\n}`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-007',
    title: 'Array `reduce` Initial Value',
    description: '`reduce` on an empty array without an initial value throws a `TypeError`.',
    buggyCode: `const nums = [];\nconst sum = nums.reduce((acc, curr) => acc + curr);`,
    fixedCode: `const nums = [];\nconst sum = nums.reduce((acc, curr) => acc + curr, 0);`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-008',
    title: 'Promise.all with Non-Promises',
    description: '`Promise.all` still returns a promise even if the array contains non-promise values.',
    buggyCode: `const results = Promise.all([1, Promise.resolve(2)]);\nconsole.log(results); // This logs a Promise, not [1, 2]`,
    fixedCode: `async function getResults() {\n  const results = await Promise.all([1, Promise.resolve(2)]);\n  console.log(results);\n}\ngetResults();`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-009',
    title: 'Bind `this` Context',
    description: 'When passing a method as a callback, its `this` context is lost. It must be explicitly bound.',
    buggyCode: `const person = {\n  name: 'John',\n  sayHi: function() { console.log('Hi ' + this.name); }\n}\nsetTimeout(person.sayHi, 1000);`,
    fixedCode: `const person = {\n  name: 'John',\n  sayHi: function() { console.log('Hi ' + this.name); }\n}\nsetTimeout(person.sayHi.bind(person), 1000);`,
    language: 'javascript',
    difficulty: 'Hard',
  },
  {
    id: 'dc-js-hard-010',
    title: 'Incorrect `JSON.stringify` Use',
    description: '`JSON.stringify` can take a replacer function and a space argument. Providing a number as the second argument is incorrect for spacing.',
    buggyCode: `const data = { a: 1, b: 2 };\nconst jsonString = JSON.stringify(data, 2);`,
    fixedCode: `const data = { a: 1, b: 2 };\nconst jsonString = JSON.stringify(data, null, 2);`,
    language: 'javascript',
    difficulty: 'Hard',
  },

  // Python - Easy
  {
    id: 'dc-py-easy-001',
    title: 'Indentation Error',
    description: 'This function has an indentation error.',
    buggyCode: `def my_function():\nprint("Hello, World!")`,
    fixedCode: `def my_function():\n    print("Hello, World!")`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-002',
    title: 'String to Int Conversion',
    description: 'This should add two numbers, but it\'s concatenating strings.',
    buggyCode: `def add_numbers(a, b):\n    return str(a) + str(b)`,
    fixedCode: `def add_numbers(a, b):\n    return a + b`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-003',
    title: 'Missing Colon',
    description: 'A colon is missing at the end of the `if` statement.',
    buggyCode: `def check_number(n)\n    if n > 0:\n        return "Positive"`,
    fixedCode: `def check_number(n):\n    if n > 0:\n        return "Positive"`,
    language: 'python',
    difficulty: 'Easy',
  },
    {
    id: 'dc-py-easy-004',
    title: 'Using = instead of ==',
    description: 'The `if` statement uses the assignment operator `=` instead of the comparison operator `==`.',
    buggyCode: `def check_value(val):\n  if val = 10:\n    return True`,
    fixedCode: `def check_value(val):\n  if val == 10:\n    return True`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-005',
    title: 'Incorrect Method Name',
    description: 'The method to add an item to a list is `append`, not `add`.',
    buggyCode: `my_list = [1, 2]\nmy_list.add(3)`,
    fixedCode: `my_list = [1, 2]\nmy_list.append(3)`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-006',
    title: 'Dictionary Key Access',
    description: 'Accessing a dictionary key uses square brackets, not parentheses.',
    buggyCode: `my_dict = {"name": "Alice"}\nname = my_dict("name")`,
    fixedCode: `my_dict = {"name": "Alice"}\nname = my_dict["name"]`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-007',
    title: 'len() on Integer',
    description: 'The `len()` function cannot be used on integers.',
    buggyCode: `count = 123\nprint(len(count))`,
    fixedCode: `count = 123\nprint(len(str(count)))`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-008',
    title: 'Function Return',
    description: 'The function calculates a value but never returns it.',
    buggyCode: `def multiply(a, b):\n  result = a * b`,
    fixedCode: `def multiply(a, b):\n  result = a * b\n  return result`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-009',
    title: 'Input as String',
    description: 'The `input()` function returns a string, which needs to be converted to an integer for math.',
    buggyCode: `age = input("Enter your age: ")\nprint("Next year you will be " + (age + 1))`,
    fixedCode: `age = input("Enter your age: ")\nprint("Next year you will be " + str(int(age) + 1))`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-010',
    title: 'Range Exclusive',
    description: 'The `range(n)` function goes from 0 up to `n-1`. It does not include `n`.',
    buggyCode: `for i in range(5):\n  # Should print 1,2,3,4,5\n  print(i+1)`,
    fixedCode: `for i in range(1, 6):\n  print(i)`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-011',
    title: 'Boolean Capitalization',
    description: 'In Python, boolean values are capitalized: `True` and `False`.',
    buggyCode: `is_active = true`,
    fixedCode: `is_active = True`,
    language: 'python',
    difficulty: 'Easy',
  },
  {
    id: 'dc-py-easy-012',
    title: 'Elif Syntax',
    description: 'The keyword for "else if" in Python is `elif`, not `elseif`.',
    buggyCode: `x = 0\nif x > 0:\n  print("Positive")\nelseif x < 0:\n  print("Negative")`,
    fixedCode: `x = 0\nif x > 0:\n  print("Positive")\nelif x < 0:\n  print("Negative")`,
    language: 'python',
    difficulty: 'Easy',
  },

  // Python - Medium
  {
    id: 'dc-py-medium-001',
    title: 'List Default Argument',
    description: 'Using a mutable default argument can lead to unexpected behavior.',
    buggyCode: `def append_to_list(element, to_list=[]):\n    to_list.append(element)\n    return to_list`,
    fixedCode: `def append_to_list(element, to_list=None):\n    if to_list is None:\n        to_list = []\n    to_list.append(element)\n    return to_list`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-002',
    title: 'Float Division',
    description: 'The `/` operator in Python 3 performs float division. Use `//` for integer division.',
    buggyCode: `result = 10 / 4  # Expected integer result is 2`,
    fixedCode: `result = 10 // 4 # Expected integer result is 2`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-003',
    title: 'Accessing Dictionary Key',
    description: 'Accessing a non-existent key will raise a `KeyError`. Use `.get()` for safer access.',
    buggyCode: `my_dict = {"a": 1}\nvalue = my_dict["b"]`,
    fixedCode: `my_dict = {"a": 1}\nvalue = my_dict.get("b")`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-004',
    title: 'List Slicing Copy',
    description: 'Assigning a list to a new variable creates a reference, not a copy. Slicing is needed to create a shallow copy.',
    buggyCode: `list_a = [1, 2]\nlist_b = list_a\nlist_b.append(3)`,
    fixedCode: `list_a = [1, 2]\nlist_b = list_a[:]\nlist_b.append(3)`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-005',
    title: 'Global Keyword',
    description: 'To modify a global variable inside a function, you must use the `global` keyword.',
    buggyCode: `count = 0\ndef increment():\n  count += 1`,
    fixedCode: `count = 0\ndef increment():\n  global count\n  count += 1`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-006',
    title: 'Exception Syntax',
    description: 'The syntax for catching an exception is `except Exception as e`.',
    buggyCode: `try:\n  1 / 0\nexcept ZeroDivisionError, e: \n  print(e)`,
    fixedCode: `try:\n  1 / 0\nexcept ZeroDivisionError as e: \n  print(e)`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-007',
    title: 'Iterating and Modifying Dictionary',
    description: 'You cannot add or remove keys from a dictionary while iterating over it.',
    buggyCode: `d = {'a': 1, 'b': 2}\nfor k, v in d.items():\n  if v == 1:\n    del d[k]`,
    fixedCode: `d = {'a': 1, 'b': 2}\nfor k in list(d.keys()):\n  if d[k] == 1:\n    del d[k]`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-008',
    title: 'String Concatenation in Loop',
    description: 'Repeatedly concatenating strings in a loop is inefficient. It is better to append to a list and then join.',
    buggyCode: `result = ""\nmy_list = ['a', 'b', 'c']\nfor item in my_list:\n  result += item`,
    fixedCode: `my_list = ['a', 'b', 'c']\nresult = "".join(my_list)`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-009',
    title: 'Missing `self`',
    description: 'Methods in a Python class must have `self` as their first parameter.',
    buggyCode: `class Car:\n  def start_engine():\n    print("Engine started")`,
    fixedCode: `class Car:\n  def start_engine(self):\n    print("Engine started")`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-010',
    title: 'Tuple Immutability',
    description: 'Tuples are immutable and their items cannot be reassigned.',
    buggyCode: `my_tuple = (1, 2, 3)\nmy_tuple[0] = 4`,
    fixedCode: `my_tuple = (1, 2, 3)\nmy_list = list(my_tuple)\nmy_list[0] = 4\nmy_tuple = tuple(my_list)`,
    language: 'python',
    difficulty: 'Medium',
  },
  {
    id: 'dc-py-medium-011',
    title: 'Set vs List',
    description: 'Sets do not allow duplicate elements. This code is trying to create a list of duplicates from a set.',
    buggyCode: `my_set = {1, 2, 3}\nmy_set.add(1)`,
    fixedCode: `my_list = [1, 2, 3]\nmy_list.append(1)`,
    language: 'python',
    difficulty: 'Medium',
  },

  // Python - Hard
  {
    id: 'dc-py-hard-001',
    title: 'Looping over list copy',
    description: 'Modifying a list while iterating over it can lead to skipping items.',
    buggyCode: `numbers = [1, 2, 3, 4]\nfor number in numbers:\n    if number % 2 == 0:\n        numbers.remove(number)`,
    fixedCode: `numbers = [1, 2, 3, 4]\nfor number in numbers[:]:\n    if number % 2 == 0:\n        numbers.remove(number)`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-002',
    title: 'Class Variable vs Instance Variable',
    description: 'The `tags` variable is a class variable, shared by all instances. It should be an instance variable.',
    buggyCode: `class Post:\n  tags = []\n  def __init__(self, tag):\n    self.tags.append(tag)`,
    fixedCode: `class Post:\n  def __init__(self, tag):\n    self.tags = []\n    self.tags.append(tag)`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-003',
    title: 'Generator Exhaustion',
    description: 'A generator can only be iterated over once. Trying to iterate a second time yields nothing.',
    buggyCode: `gen = (x*x for x in range(3))\nlist(gen)\nlist(gen) # This will be empty`,
    fixedCode: `def make_gen():\n  return (x*x for x in range(3))\ngen1 = make_gen()\nlist(gen1)\ngen2 = make_gen()\nlist(gen2)`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-004',
    title: 'Late Binding Closures',
    description: 'Variables in closures are bound by name. The value of `i` is looked up when the lambda is called, by which time the loop has finished.',
    buggyCode: `funcs = []\nfor i in range(3):\n  funcs.append(lambda: print(i))`,
    fixedCode: `funcs = []\nfor i in range(3):\n  funcs.append(lambda i=i: print(i))`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-005',
    title: 'Deep vs Shallow Copy',
    description: 'A shallow copy of a list of lists will still have references to the inner lists.',
    buggyCode: `import copy\n\nlist1 = [[1], [2]]\nlist2 = copy.copy(list1)\n\nlist2[0][0] = 3 # This also changes list1`,
    fixedCode: `import copy\n\nlist1 = [[1], [2]]\nlist2 = copy.deepcopy(list1)\n\nlist2[0][0] = 3`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-006',
    title: '`datetime` Timezone Naivety',
    description: '`datetime.now()` creates a "naive" datetime object without timezone info, which can cause issues.',
    buggyCode: `import datetime\n\nnow = datetime.datetime.now()\n# This is naive and can cause bugs`,
    fixedCode: `import datetime\nimport pytz\n\nnow = datetime.datetime.now(pytz.utc)\n# This is timezone-aware`,
    language: 'python',
    difficulty: 'Hard',
  },
  {
    id: 'dc-py-hard-007',
    title: 'Circular Import',
    description: 'Module `a` imports `b` and module `b` imports `a`. This causes a circular dependency.',
    buggyCode: `# a.py\nimport b\ndef f():\n  return b.x\n\n# b.py\nimport a\nx = 1\na.f()`,
    fixedCode: `# a.py\n\ndef f():\n  import b # Import locally\n  return b.x\n\n# b.py\nimport a\nx = 1\na.f()`,
    language: 'python',
    difficulty: 'Hard',
  },

  // Java - Easy
  {
    id: 'dc-java-easy-001',
    title: 'Missing Semicolon',
    description: 'A semicolon is missing at the end of a statement.',
    buggyCode: `public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello World")\n  }\n}`,
    fixedCode: `public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello World");\n  }\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-002',
    title: 'String Comparison',
    description: 'Strings should be compared using .equals(), not ==.',
    buggyCode: `public boolean checkString(String s1, String s2) {\n    return s1 == s2;\n}`,
    fixedCode: `public boolean checkString(String s1, String s2) {\n    return s1.equals(s2);\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-003',
    title: 'Incorrect Main Signature',
    description: 'The `main` method has an incorrect signature. It should accept `String[] args`.',
    buggyCode: `public class Main {\n  public static void main(String args) {\n    System.out.println("Hi");\n  }\n}`,
    fixedCode: `public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hi");\n  }\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
    {
    id: 'dc-java-easy-004',
    title: 'Integer Division',
    description: 'Dividing two integers results in an integer. One must be a double for float division.',
    buggyCode: `double result = 5 / 2; // result is 2.0`,
    fixedCode: `double result = 5 / 2.0; // result is 2.5`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-005',
    title: 'Array Initialization',
    description: 'The syntax for initializing an array is incorrect.',
    buggyCode: `int[] numbers = {1, 2, 3};`,
    fixedCode: `int[] numbers = new int[]{1, 2, 3};`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-006',
    title: 'Public Class Filename',
    description: 'A public class `MyClass` must be in a file named `MyClass.java`.',
    buggyCode: `// In file OtherName.java\npublic class MyClass {}`,
    fixedCode: `// In file MyClass.java\npublic class MyClass {}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-007',
    title: 'Unreachable Code',
    description: 'Code after a `return` statement in the same block is unreachable.',
    buggyCode: `public int getValue() {\n  return 10;\n  System.out.println("Returned");\n}`,
    fixedCode: `public int getValue() {\n  System.out.println("Returning");\n  return 10;\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-008',
    title: 'Array Indexing Loop',
    description: 'The loop condition should be `i < array.length` to avoid an `ArrayIndexOutOfBoundsException`.',
    buggyCode: `int[] arr = {1,2,3};\nfor(int i=0; i <= arr.length; i++) {\n  System.out.println(arr[i]);\n}`,
    fixedCode: `int[] arr = {1,2,3};\nfor(int i=0; i < arr.length; i++) {\n  System.out.println(arr[i]);\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-009',
    title: 'Abstract Method in Class',
    description: 'A class must be declared `abstract` to contain an abstract method.',
    buggyCode: `public class Shape {\n  public abstract double getArea();\n}`,
    fixedCode: `public abstract class Shape {\n  public abstract double getArea();\n}`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-010',
    title: 'Character vs String',
    description: 'Single quotes are for `char` literals, while double quotes are for `String` literals.',
    buggyCode: `String myChar = 'a';`,
    fixedCode: `char myChar = 'a';`,
    language: 'java',
    difficulty: 'Easy',
  },
  {
    id: 'dc-java-easy-011',
    title: 'Missing `new` Keyword',
    description: 'The `new` keyword is required to instantiate an object.',
    buggyCode: `StringBuilder sb = StringBuilder();`,
    fixedCode: `StringBuilder sb = new StringBuilder();`,
    language: 'java',
    difficulty: 'Easy',
  },
  
  // Java - Medium
  {
    id: 'dc-java-medium-001',
    title: 'Array Index Out of Bounds',
    description: 'The loop condition should be `<` instead of `<=`.',
    buggyCode: `public void printArray(int[] arr) {\n    for (int i = 0; i <= arr.length; i++) {\n        System.out.println(arr[i]);\n    }\n}`,
    fixedCode: `public void printArray(int[] arr) {\n    for (int i = 0; i < arr.length; i++) {\n        System.out.println(arr[i]);\n    }\n}`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-002',
    title: 'NullPointerException',
    description: 'Calling a method on a null reference will throw a NullPointerException.',
    buggyCode: `String name = null;\nint length = name.length();`,
    fixedCode: `String name = null;\nif (name != null) {\n  int length = name.length();\n}`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-003',
    title: 'Floating Point Inaccuracy',
    description: 'Using `float` or `double` for currency is risky due to precision issues. `BigDecimal` should be used.',
    buggyCode: `double total = 0.1 + 0.2; // total is not 0.3`,
    fixedCode: `import java.math.BigDecimal;\n\nBigDecimal total = new BigDecimal("0.1").add(new BigDecimal("0.2"));`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-004',
    title: 'Integer Caching',
    description: '`Integer` objects are cached for values -128 to 127. Outside this range, `==` compares references, not values.',
    buggyCode: `Integer a = 200;\nInteger b = 200;\nboolean result = a == b; // false`,
    fixedCode: `Integer a = 200;\nInteger b = 200;\nboolean result = a.equals(b); // true`,
    language: 'java',
    difficulty: 'Medium',
  },
   {
    id: 'dc-java-medium-005',
    title: 'Default Switch Case',
    description: 'Forgetting `break` statements in a `switch` causes "fall-through" to subsequent cases.',
    buggyCode: `int x = 1;\nswitch(x) {\n  case 1: System.out.println("1");\n  case 2: System.out.println("2");\n}`,
    fixedCode: `int x = 1;\nswitch(x) {\n  case 1: System.out.println("1"); break;\n  case 2: System.out.println("2"); break;\n}`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-006',
    title: 'SubList is a View',
    description: '`List.subList()` returns a view of the original list, not a new list. Modifying it modifies the original.',
    buggyCode: `List<Integer> list = new ArrayList<>(Arrays.asList(1,2,3));\nList<Integer> sub = list.subList(0,1);\nsub.clear(); // This also modifies 'list'`,
    fixedCode: `List<Integer> list = new ArrayList<>(Arrays.asList(1,2,3));\nList<Integer> sub = new ArrayList<>(list.subList(0,1));\nsub.clear();`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-007',
    title: 'Static Method Call',
    description: 'Static methods belong to the class and should be called on the class itself, not on an instance.',
    buggyCode: `public class MathUtils {\n  public static int add(int a, int b) { return a + b; }\n}\nMathUtils mu = new MathUtils();\nint sum = mu.add(1, 2);`,
    fixedCode: `public class MathUtils {\n  public static int add(int a, int b) { return a + b; }\n}\nint sum = MathUtils.add(1, 2);`,
    language: 'java',
    difficulty: 'Medium',
  },
  {
    id: 'dc-java-medium-008',
    title: 'Final Variable Reassignment',
    description: 'A variable marked as `final` cannot be reassigned after it has been initialized.',
    buggyCode: `final int myNum = 10;\nmyNum = 20;`,
    fixedCode: `int myNum = 10;\nmyNum = 20;`,
    language: 'java',
    difficulty: 'Medium',
  },
  
  // Java - Hard
  {
    id: 'dc-java-hard-001',
    title: 'Concurrent Modification',
    description: 'You cannot remove items from a list while iterating with an enhanced for-loop.',
    buggyCode: `ArrayList<String> list = new ArrayList<>();\nlist.add("a");\nlist.add("b");\nfor (String s : list) {\n    list.remove(s);\n}`,
    fixedCode: `ArrayList<String> list = new ArrayList<>();\nlist.add("a");\nlist.add("b");\nIterator<String> i = list.iterator();\nwhile (i.hasNext()) {\n   String s = i.next();\n   i.remove();\n}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-002',
    title: 'Static Variable Misuse',
    description: 'The counter is `static`, so it\'s shared by all instances of Counter, not unique to each.',
    buggyCode: `class Counter {\n    public static int count = 0;\n    public Counter() {\n        count++;\n    }\n}`,
    fixedCode: `class Counter {\n    public int count = 0;\n    public Counter() {\n        count++;\n    }\n}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-003',
    title: 'Unclosed Resource',
    description: 'File streams and other resources must be closed to prevent leaks. A try-with-resources statement is best.',
    buggyCode: `try {\n    FileInputStream fs = new FileInputStream("file.txt");\n    fs.read();\n} catch (IOException e) {}`,
    fixedCode: `try (FileInputStream fs = new FileInputStream("file.txt")) {\n    fs.read();\n} catch (IOException e) {}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-004',
    title: 'Thread Safety',
    description: 'Multiple threads accessing and modifying `count` can lead to a race condition.',
    buggyCode: `public class Counter {\n  private int count = 0;\n  public void increment() { count++; }\n}`,
    fixedCode: `import java.util.concurrent.atomic.AtomicInteger;\n\npublic class Counter {\n  private AtomicInteger count = new AtomicInteger(0);\n  public void increment() { count.incrementAndGet(); }\n}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-005',
    title: 'Overriding equals without hashCode',
    description: 'If you override `equals()`, you must also override `hashCode()` to maintain the contract for collections like `HashMap`.',
    buggyCode: `public class Person {\n  public String name;\n  @Override\n  public boolean equals(Object o) { return true; }\n}`,
    fixedCode: `public class Person {\n  public String name;\n  @Override\n  public boolean equals(Object o) { /*...*/ return true; }\n  @Override\n  public int hashCode() { return 1; }\n}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-006',
    title: 'Date Object Mutability',
    description: '`Date` objects are mutable. Returning a direct reference allows the caller to modify the internal state of the class.',
    buggyCode: `public class Event {\n  private Date eventDate;\n  public Date getDate() { return eventDate; }\n}`,
    fixedCode: `public class Event {\n  private Date eventDate;\n  public Date getDate() { return (Date) eventDate.clone(); }\n}`,
    language: 'java',
    difficulty: 'Hard',
  },
  {
    id: 'dc-java-hard-007',
    title: 'Arrays.asList Immutability',
    description: 'The list returned by `Arrays.asList` is fixed-size. You cannot add or remove elements.',
    buggyCode: `List<String> list = Arrays.asList("a", "b");\nlist.add("c");`,
    fixedCode: `List<String> list = new ArrayList<>(Arrays.asList("a", "b"));\nlist.add("c");`,
    language: 'java',
    difficulty: 'Hard',
  },
  
  // C++ - Easy
  {
    id: 'dc-cpp-easy-001',
    title: 'Missing Header',
    description: 'The `iostream` header is required for `std::cout`.',
    buggyCode: `int main() {\n    std::cout << "Hello, World!";\n    return 0;\n}`,
    fixedCode: `#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!";\n    return 0;\n}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-002',
    title: 'Pointer Null Check',
    description: 'The pointer should be checked for null before dereferencing.',
    buggyCode: `void printValue(int* p) {\n    std::cout << *p;\n}`,
    fixedCode: `void printValue(int* p) {\n    if (p) {\n        std::cout << *p;\n    }\n}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-003',
    title: 'Using namespace',
    description: 'The `std` namespace is not specified for `cout`.',
    buggyCode: `#include <iostream>\n\nint main() {\n    cout << "Hello!";\n    return 0;\n}`,
    fixedCode: `#include <iostream>\n\nint main() {\n    std::cout << "Hello!";\n    return 0;\n}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-004',
    title: 'Vector Access',
    description: 'Accessing a vector element at an index that is out of bounds.',
    buggyCode: `#include <vector>\n\nstd::vector<int> v = {1, 2};\nint x = v[2];`,
    fixedCode: `#include <vector>\n\nstd::vector<int> v = {1, 2};\nint x = v.at(1);`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-005',
    title: 'Assignment in Condition',
    description: 'Using `=` (assignment) instead of `==` (comparison) in an if-statement.',
    buggyCode: `int x = 5;\nif (x = 10) {\n  // always true\n}`,
    fixedCode: `int x = 5;\nif (x == 10) {\n  // correct check\n}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-006',
    title: 'Missing return statement',
    description: 'A function declared to return a value must have a return statement.',
    buggyCode: `int give_me_five() {\n  // No return\n}`,
    fixedCode: `int give_me_five() {\n  return 5;\n}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-007',
    title: '`cin` with spaces',
    description: '`cin` stops reading at the first whitespace character. Use `getline` to read a full line.',
    buggyCode: `#include <iostream>\n#include <string>\n\nstd::string name;\nstd::cin >> name; // "John Smith" -> "John"`,
    fixedCode: `#include <iostream>\n#include <string>\n\nstd::string name;\nstd::getline(std::cin, name);`,
    language: 'cpp',
    difficulty: 'Easy',
  },
   {
    id: 'dc-cpp-easy-008',
    title: 'Semicolon After Function',
    description: 'An extra semicolon after the function definition is a syntax error.',
    buggyCode: `void doSomething() {};`,
    fixedCode: `void doSomething() {}`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-009',
    title: 'Header Guards',
    description: 'A header file is missing include guards, which can cause multiple-definition errors.',
    buggyCode: `// my_header.h\nstruct MyStruct {};`,
    fixedCode: `// my_header.h\n#ifndef MY_HEADER_H\n#define MY_HEADER_H\nstruct MyStruct {};\n#endif`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  {
    id: 'dc-cpp-easy-010',
    title: 'Character Literal',
    description: 'Double quotes create a string literal, not a character literal.',
    buggyCode: `char my_char = "a";`,
    fixedCode: `char my_char = 'a';`,
    language: 'cpp',
    difficulty: 'Easy',
  },
  
  // C++ - Medium
  {
    id: 'dc-cpp-medium-001',
    title: 'Buffer Overflow',
    description: '`strcpy` does not check buffer bounds, leading to a potential overflow.',
    buggyCode: `void copyString(char* str) {\n    char buffer[10];\n    strcpy(buffer, str);\n}`,
    fixedCode: `void copyString(char* str) {\n    char buffer[10];\n    strncpy(buffer, str, sizeof(buffer) - 1);\n    buffer[sizeof(buffer) - 1] = '\\0';\n}`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-002',
    title: 'Uninitialized Variable',
    description: 'The variable `x` is used without being initialized.',
    buggyCode: `int x;\nstd::cout << x;`,
    fixedCode: `int x = 0;\nstd::cout << x;`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-003',
    title: 'Object Slicing',
    description: 'Assigning a derived class object to a base class object slices off the derived part.',
    buggyCode: `class Base { int x; };\nclass Derived : public Base { int y; };\n\nDerived d;\nBase b = d;`,
    fixedCode: `class Base { int x; };\nclass Derived : public Base { int y; };\n\nDerived d;\nBase* b = &d;`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-004',
    title: 'Delete vs Delete[]',
    description: 'Memory allocated for an array with `new[]` must be freed with `delete[]`.',
    buggyCode: `int* arr = new int[10];\ndelete arr;`,
    fixedCode: `int* arr = new int[10];\ndelete[] arr;`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-005',
    title: 'Missing Break in Switch',
    description: 'Forgetting `break` in a `switch` statement causes fall-through.',
    buggyCode: `int x = 1;\nswitch(x) {\n  case 1: std::cout << "1";\n  case 2: std::cout << "2";\n}`,
    fixedCode: `int x = 1;\nswitch(x) {\n  case 1: std::cout << "1"; break;\n  case 2: std::cout << "2"; break;\n}`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-006',
    title: 'Pass by Value',
    description: 'The vector is passed by value, so modifications inside the function do not affect the original.',
    buggyCode: `void add_element(std::vector<int> v) {\n  v.push_back(1);\n}`,
    fixedCode: `void add_element(std::vector<int>& v) {\n  v.push_back(1);\n}`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-007',
    title: 'Const correctness',
    description: 'A method that does not modify the object\'s state should be marked `const`.',
    buggyCode: `class MyClass {\n  int val;\npublic:\n  int getValue() { return val; }\n};`,
    fixedCode: `class MyClass {\n  int val;\npublic:\n  int getValue() const { return val; }\n};`,
    language: 'cpp',
    difficulty: 'Medium',
  },
  {
    id: 'dc-cpp-medium-008',
    title: 'Comparing Floats',
    description: 'Directly comparing floating-point numbers for equality can fail due to precision issues.',
    buggyCode: `float a = 0.1f + 0.2f;\nif (a == 0.3f) { /* ... */ }`,
    fixedCode: `#include <cmath>\n\nfloat a = 0.1f + 0.2f;\nif (std::abs(a - 0.3f) < 1e-6) { /* ... */ }`,
    language: 'cpp',
    difficulty: 'Medium',
  },

  // C++ - Hard
  {
    id: 'dc-cpp-hard-001',
    title: 'Memory Leak',
    description: 'Memory allocated with `new` must be deallocated with `delete`.',
    buggyCode: `void createLeak() {\n    int* p = new int(5);\n    // Missing delete p;\n}`,
    fixedCode: `void createLeak() {\n    int* p = new int(5);\n    delete p;\n}`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-002',
    title: 'Dangling Pointer',
    description: 'Returning a pointer to a local variable, which is destroyed when the function exits.',
    buggyCode: `int* createValue() {\n    int x = 10;\n    return &x;\n}`,
    fixedCode: `int* createValue() {\n    int* x = new int(10);\n    return x;\n}`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-003',
    title: 'Rule of Three Violation',
    description: 'If a class needs a destructor, it almost certainly needs a copy constructor and copy assignment operator.',
    buggyCode: `class MyClass {\n  int* data;\npublic:\n  MyClass() { data = new int[10]; }\n  ~MyClass() { delete[] data; }\n};`,
    fixedCode: `class MyClass {\n  int* data;\npublic:\n  MyClass() { data = new int[10]; }\n  ~MyClass() { delete[] data; }\n  MyClass(const MyClass& other) = delete;\n  MyClass& operator=(const MyClass& other) = delete;\n};`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-004',
    title: 'Virtual Destructor',
    description: 'When deleting a derived object through a base pointer, the base destructor must be virtual to ensure the derived destructor is called.',
    buggyCode: `class Base { ~Base() {} };\nclass Derived : public Base {};\n\nBase* b = new Derived();\ndelete b; // Leaks Derived resources`,
    fixedCode: `class Base { public: virtual ~Base() {} };\nclass Derived : public Base {};\n\nBase* b = new Derived();\ndelete b;`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-005',
    title: 'Iterator Invalidation',
    description: 'Erasing elements from a `std::vector` invalidates iterators, leading to undefined behavior.',
    buggyCode: `std::vector<int> v = {1, 2, 3};\nfor (auto it = v.begin(); it != v.end(); ++it) {\n  if (*it == 2) v.erase(it);\n}`,
    fixedCode: `std::vector<int> v = {1, 2, 3};\nfor (auto it = v.begin(); it != v.end();) {\n  if (*it == 2) it = v.erase(it);\n  else ++it;\n}`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-006',
    title: 'Integer Overflow',
    description: 'Adding two large integers can result in an overflow, wrapping around to a negative number.',
    buggyCode: `#include <limits>\n\nint a = std::numeric_limits<int>::max();\nint b = a + 1; // Undefined behavior`,
    fixedCode: `#include <limits>\n\nlong long a = std::numeric_limits<int>::max();\nlong long b = a + 1;`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-007',
    title: 'Static Initialization Fiasco',
    description: 'The order of initialization of static objects in different translation units is not guaranteed.',
    buggyCode: `// a.cpp\nextern int y;\nint x = y + 1;\n\n// b.cpp\nextern int x;\nint y = x + 1;`,
    fixedCode: `// Use a function to control initialization order\nint& get_y() { static int y = get_x() + 1; return y; }\nint& get_x() { static int x = 10; return x; }`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-008',
    title: 'Template Instantiation Error',
    description: 'The template requires a type that supports the `>` operator, but `MyObject` does not.',
    buggyCode: `template <typename T>\nT max(T a, T b) { return a > b ? a : b; }\n\nstruct MyObject {};\nMyObject o1, o2;\nmax(o1, o2);`,
    fixedCode: `template <typename T>\nT max(T a, T b) { return a > b ? a : b; }\n\nstruct MyObject {\n  bool operator>(const MyObject& other) const { return true; }\n};\nMyObject o1, o2;\nmax(o1, o2);`,
    language: 'cpp',
    difficulty: 'Hard',
  },
  {
    id: 'dc-cpp-hard-009',
    title: 'Using `std::endl`',
    description: '`std::endl` is often used when `\'\\n\'` is sufficient. `std::endl` also forces a flush of the stream, which can be a performance bottleneck.',
    buggyCode: `#include <iostream>\n\nfor (int i=0; i<100; ++i) std::cout << i << std::endl;`,
    fixedCode: `#include <iostream>\n\nfor (int i=0; i<100; ++i) std::cout << i << '\\n';`,
    language: 'cpp',
    difficulty: 'Hard',
  },
];

export function getRandomDebugChallenge(difficulty: 'Easy' | 'Medium' | 'Hard', language: 'javascript' | 'python' | 'java' | 'cpp'): DebugChallenge {
  const filtered = debugChallenges.filter(c => c.difficulty === difficulty && c.language === language);
  if (filtered.length === 0) {
    // Fallback if no challenges match filters
    const fallbackFiltered = debugChallenges.filter(c => c.language === language);
    if (fallbackFiltered.length > 0) {
        return fallbackFiltered[Math.floor(Math.random() * fallbackFiltered.length)];
    }
    return debugChallenges[Math.floor(Math.random() * debugChallenges.length)];
  }
  return filtered[Math.floor(Math.random() * filtered.length)];
}


export function getChallengeById(id: string): DebugChallenge | undefined {
    return debugChallenges.find(c => c.id === id);
}
