
export interface JigsawChallenge {
  id: string;
  title: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  correctOrder: string[];
}

export const jigsawChallenges: JigsawChallenge[] = [
  // JavaScript - Easy
  {
    id: 'jg-js-easy-01',
    title: 'Simple Greeting',
    description: 'Create a function that returns a greeting string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'function greet() {',
      '  return "Hello, World!";',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-02',
    title: 'Variable Declaration',
    description: 'Declare two variables and add them.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let a = 5;',
      'let b = 10;',
      'let sum = a + b;',
    ],
  },
  {
    id: 'jg-js-easy-03',
    title: 'Simple For Loop',
    description: 'Loop from 0 to 4 and print each number.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'for (let i = 0; i < 5; i++) {',
      '  console.log(i);',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-04',
    title: 'Simple If Statement',
    description: 'Check if a number is greater than 10.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let num = 15;',
      'if (num > 10) {',
      '  console.log("Number is greater than 10");',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-05',
    title: 'Simple While Loop',
    description: 'Use a while loop to count to 3.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let i = 0;',
      'while (i < 3) {',
      '  console.log(i);',
      '  i++;',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-06',
    title: 'Accessing Array Elements',
    description: 'Define an array and access its second element.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const fruits = ["Apple", "Banana", "Cherry"];',
      'const secondFruit = fruits[1];',
    ],
  },
  {
    id: 'jg-js-easy-07',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const txt = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";',
      'const length = txt.length;',
    ],
  },
  {
    id: 'jg-js-easy-08',
    title: 'Function with Parameter',
    description: 'Create a function that takes a name as a parameter.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'function greetName(name) {',
      '  return "Hello " + name;',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-09',
    title: 'Simple Boolean Logic',
    description: 'Check if two conditions are true.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let x = 6;',
      'let y = 3;',
      'if (x < 10 && y > 1) {',
      '  console.log("Both are true!");',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-10',
    title: 'Object Property Access',
    description: 'Access a property from a simple object.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const car = {type:"Fiat", model:"500"};',
      'const carType = car.type;',
    ],
  },

  // JavaScript - Medium
  {
    id: 'jg-js-medium-01',
    title: 'Arrow Function',
    description: 'Define a simple arrow function to double a number.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const double = (n) => {',
      '  return n * 2;',
      '};',
    ],
  },
  {
    id: 'jg-js-medium-02',
    title: 'Array Map',
    description: 'Use the map function to create a new array with doubled values.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const numbers = [1, 2, 3];',
      'const doubled = numbers.map(num => {',
      '  return num * 2;',
      '});',
    ],
  },
  {
    id: 'jg-js-medium-03',
    title: 'Object Literal',
    description: 'Create a simple object representing a person.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const person = {',
      '  name: "Alice",',
      '  age: 30',
      '};',
    ],
  },
    {
    id: 'jg-js-medium-04',
    title: 'Async/Await Fetch',
    description: 'Fetch data from an API using async/await.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'async function fetchData() {',
      '  const response = await fetch("https://api.example.com/data");',
      '  const data = await response.json();',
      '  console.log(data);',
      '}',
    ],
  },
  {
    id: 'jg-js-medium-05',
    title: 'Array Filter',
    description: 'Filter an array to get only even numbers.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
        'const numbers = [1, 2, 3, 4, 5];',
        'const evens = numbers.filter(num => {',
        '  return num % 2 === 0;',
        '});',
    ],
  },
  {
    id: 'jg-js-medium-06',
    title: 'Switch Statement',
    description: 'Check the value of a variable using a switch statement.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'let day = "Monday";',
      'switch (day) {',
      '  case "Monday":',
      '    console.log("Start of the week!");',
      '    break;',
      '  default:',
      '    console.log("Another day");',
      '}',
    ],
  },
  {
    id: 'jg-js-medium-07',
    title: 'Destructuring Assignment',
    description: 'Use destructuring to extract values from an object.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const vehicle = { brand: "Ford", model: "Mustang" };',
      'const { brand, model } = vehicle;',
      'console.log(brand);',
    ],
  },
  {
    id: 'jg-js-medium-08',
    title: 'Array Find',
    description: 'Find the first element in an array that satisfies a condition.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const ages = [3, 10, 18, 20];',
      'const adultAge = ages.find(age => {',
      '  return age >= 18;',
      '});',
    ],
  },
  {
    id: 'jg-js-medium-09',
    title: 'Template Literals',
    description: 'Create a string using template literals.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const name = "Alice";',
      'const age = 25;',
      'const sentence = `Her name is ${name} and she is ${age} years old.`;',
    ],
  },
  {
    id: 'jg-js-medium-10',
    title: 'forEach Loop',
    description: 'Iterate over an array using the forEach method.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const fruits = ["apple", "orange", "cherry"];',
      'fruits.forEach(fruit => {',
      '  console.log(fruit);',
      '});',
    ],
  },

  // JavaScript - Hard
  {
    id: 'jg-js-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Rectangle.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Rectangle {',
      '  constructor(height, width) {',
      '    this.height = height;',
      '    this.width = width;',
      '  }',
      '  getArea() {',
      '    return this.height * this.width;',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-js-hard-02',
    title: 'Array Reduce',
    description: 'Use reduce to sum up all numbers in an array.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const numbers = [1, 2, 3, 4];',
      'const sum = numbers.reduce((accumulator, currentValue) => {',
      '  return accumulator + currentValue;',
      '}, 0);',
    ],
  },
  {
    id: 'jg-js-hard-03',
    title: 'Simple Promise',
    description: 'Create a promise that resolves after a delay.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const myPromise = new Promise((resolve, reject) => {',
      '  setTimeout(() => {',
      '    resolve("Success!");',
      '  }, 1000);',
      '});',
      'myPromise.then((message) => {',
      '  console.log(message);',
      '});',
    ],
  },
  {
    id: 'jg-js-hard-04',
    title: 'Simple Closure',
    description: 'Create a function that demonstrates closure.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'function makeCounter() {',
      '  let count = 0;',
      '  return function() {',
      '    count++;',
      '    return count;',
      '  };',
      '}',
      'const counter = makeCounter();',
    ],
  },
    {
    id: 'jg-js-hard-05',
    title: 'Event Listener',
    description: 'Add a click event listener to a button element.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const button = document.getElementById("myButton");',
      'button.addEventListener("click", () => {',
      '  alert("Button was clicked!");',
      '});',
    ],
  },
  {
    id: 'jg-js-hard-06',
    title: 'JSON stringify',
    description: 'Convert a JavaScript object to a JSON string.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const data = { name: "John", age: 30 };',
      'const jsonString = JSON.stringify(data);',
      'console.log(jsonString);',
    ],
  },
  {
    id: 'jg-js-hard-07',
    title: 'JSON parse',
    description: 'Parse a JSON string into a JavaScript object.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const jsonString = \'{"name":"John", "age":30}\';',
      'const data = JSON.parse(jsonString);',
      'console.log(data.name);',
    ],
  },
  {
    id: 'jg-js-hard-08',
    title: 'Try...Catch Block',
    description: 'Handle a potential runtime error gracefully.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  console.log(nonExistentVariable);',
      '} catch (error) {',
      '  console.error("An error occurred:", error.message);',
      '}',
    ],
  },
  {
    id: 'jg-js-hard-09',
    title: 'Class Inheritance',
    description: 'Create a class that inherits from another class.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal {',
      '  constructor(name) { this.name = name; }',
      '  speak() { console.log(`${this.name} makes a sound.`); }',
      '}',
      'class Dog extends Animal {',
      '  speak() { console.log(`${this.name} barks.`); }',
      '}',
    ],
  },
  {
    id: 'jg-js-hard-10',
    title: 'Spread Operator',
    description: 'Use the spread operator to combine arrays and objects.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const arr1 = [1, 2];',
      'const arr2 = [...arr1, 3, 4];',
      'const obj1 = {a: 1};',
      'const obj2 = {...obj1, b: 2};',
    ],
  },

  // Python - Easy
  {
    id: 'jg-py-easy-01',
    title: 'Simple Function',
    description: 'Define a function that returns the sum of two numbers.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'def add(a, b):',
      '    return a + b',
    ],
  },
  {
    id: 'jg-py-easy-02',
    title: 'Basic For Loop',
    description: 'Print numbers from 0 to 4.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'for i in range(5):',
      '    print(i)',
    ],
  },
  {
    id: 'jg-py-easy-03',
    title: 'List Creation',
    description: 'Create a list of fruits.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'fruits = ["apple", "banana", "cherry"]',
      'print(fruits[0])',
    ],
  },
    {
    id: 'jg-py-easy-04',
    title: 'If/Else statement',
    description: 'Check if a number is positive or not.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'x = 10',
      'if x > 0:',
      '    print("Positive")',
      'else:',
      '    print("Not positive")',
    ],
  },
  {
    id: 'jg-py-easy-05',
    title: 'User Input',
    description: 'Get a user\'s name and print a greeting.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = input("Enter your name: ")',
      'print(f"Hello, {name}")',
    ],
  },
  {
    id: 'jg-py-easy-06',
    title: 'While Loop',
    description: 'Use a while loop to count down from 3.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'count = 3',
      'while count > 0:',
      '    print(count)',
      '    count -= 1',
    ],
  },
  {
    id: 'jg-py-easy-07',
    title: 'Get string length',
    description: 'Find the length of a given string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'text = "Python"',
      'length = len(text)',
      'print(length)',
    ],
  },
  {
    id: 'jg-py-easy-08',
    title: 'List Append',
    description: 'Add an item to the end of a list.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'my_list = [1, 2, 3]',
      'my_list.append(4)',
      'print(my_list)',
    ],
  },
  {
    id: 'jg-py-easy-09',
    title: 'String Formatting',
    description: 'Format a string using an f-string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = "World"',
      'greeting = f"Hello, {name}!"',
      'print(greeting)',
    ],
  },
  {
    id: 'jg-py-easy-10',
    title: 'Dictionary Access',
    description: 'Access a value in a dictionary by its key.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'car = {"brand": "Ford", "model": "Mustang"}',
      'brand_name = car["brand"]',
      'print(brand_name)',
    ],
  },

  // Python - Medium
  {
    id: 'jg-py-medium-01',
    title: 'List Comprehension',
    description: 'Create a list of squares for numbers 0 through 9.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'squares = [x**2 for x in range(10)]',
      'print(squares)',
    ],
  },
  {
    id: 'jg-py-medium-02',
    title: 'Dictionary',
    description: 'Create and access a simple dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'person = {',
      '    "name": "Bob",',
      '    "age": 25',
      '}',
      'print(person["name"])',
    ],
  },
    {
    id: 'jg-py-medium-03',
    title: 'File Reading',
    description: 'Open and read a file line by line.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'with open("myfile.txt", "r") as f:',
      '    for line in f:',
      '        print(line.strip())',
    ],
  },
  {
    id: 'jg-py-medium-04',
    title: 'Looping Through Dictionary',
    description: 'Iterate over the keys and values of a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'capitals = {"USA": "Washington D.C.", "France": "Paris"}',
      'for country, capital in capitals.items():',
      '    print(f"The capital of {country} is {capital}")',
    ],
  },
  {
    id: 'jg-py-medium-05',
    title: 'Lambda Function',
    description: 'Use a lambda function to sort a list of tuples.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'points = [(1, 2), (3, 1), (5, 4)]',
      'points.sort(key=lambda x: x[1])',
      'print(points)',
    ],
  },
  {
    id: 'jg-py-medium-06',
    title: 'Exception Handling',
    description: 'Handle a potential ZeroDivisionError.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'try:',
      '    result = 10 / 0',
      'except ZeroDivisionError:',
      '    print("Cannot divide by zero!")',
    ],
  },
  {
    id: 'jg-py-medium-07',
    title: 'Import Module',
    description: 'Import the `math` module and use a function from it.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'import math',
      'result = math.sqrt(16)',
      'print(result)',
    ],
  },
  {
    id: 'jg-py-medium-08',
    title: 'Slicing a String',
    description: 'Extract a substring using slicing.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'b = "Hello, World!"',
      'print(b[2:5])',
    ],
  },
  {
    id: 'jg-py-medium-09',
    title: 'Check if Item in List',
    description: 'Check if a specific item exists in a list.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'thislist = ["apple", "banana", "cherry"]',
      'if "apple" in thislist:',
      '  print("Yes, \'apple\' is in the fruits list")',
    ],
  },
  {
    id: 'jg-py-medium-10',
    title: 'Default Parameter Value',
    description: 'Define a function with a default parameter value.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'def my_function(country = "Norway"):',
      '  print("I am from " + country)',
      'my_function("Sweden")',
      'my_function()',
    ],
  },

  // Python - Hard
  {
    id: 'jg-py-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Dog.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Dog:',
      '    def __init__(self, name):',
      '        self.name = name',
      '    def bark(self):',
      '        return "Woof!"',
      'my_dog = Dog("Fido")',
      'print(my_dog.bark())',
    ],
  },
    {
    id: 'jg-py-hard-02',
    title: 'Simple Decorator',
    description: 'Create a simple decorator to wrap a function.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def my_decorator(func):',
      '    def wrapper():',
      '        print("Before function.")',
      '        func()',
      '        print("After function.")',
      '    return wrapper',
      '@my_decorator',
      'def say_hello():',
      '    print("Hello!")',
      'say_hello()',
    ],
  },
  {
    id: 'jg-py-hard-03',
    title: 'Generator Function',
    description: 'Create a generator that yields Fibonacci numbers.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def fibonacci(n):',
      '    a, b = 0, 1',
      '    while a < n:',
      '        yield a',
      '        a, b = b, a + b',
    ],
  },
  {
    id: 'jg-py-hard-04',
    title: 'Class Inheritance',
    description: 'Create a subclass that inherits from a parent class.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal:',
      '    def speak(self):',
      '        return "Some sound"',
      'class Cat(Animal):',
      '    def speak(self):',
      '        return "Meow"',
    ],
  },
  {
    id: 'jg-py-hard-05',
    title: 'File Writing',
    description: 'Open a file for writing and add content to it.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'with open("test.txt", "w") as f:',
      '    f.write("First line.\\n")',
      '    f.write("Second line.\\n")',
    ],
  },
  {
    id: 'jg-py-hard-06',
    title: 'Set Operations',
    description: 'Find the intersection of two sets.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'set1 = {1, 2, 3, 4}',
      'set2 = {3, 4, 5, 6}',
      'intersection = set1.intersection(set2)',
      'print(intersection)',
    ],
  },
  {
    id: 'jg-py-hard-07',
    title: 'Recursion',
    description: 'Calculate factorial using recursion.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def factorial(n):',
      '    if n == 1:',
      '        return 1',
      '    else:',
      '        return n * factorial(n-1)',
    ],
  },
  {
    id: 'jg-py-hard-08',
    title: 'Reading JSON file',
    description: 'Load data from a JSON file.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import json',
      'with open("data.json", "r") as f:',
      '    data = json.load(f)',
      'print(data)',
    ],
  },
  {
    id: 'jg-py-hard-09',
    title: 'Regular Expression',
    description: 'Use the `re` module to find a pattern in a string.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import re',
      'txt = "The rain in Spain"',
      'x = re.search("^The.*Spain$", txt)',
      'if x:',
      '  print("Match found!")',
    ],
  },
  {
    id: 'jg-py-hard-10',
    title: 'Filter Function',
    description: 'Use the filter() function to get only adult ages.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'ages = [5, 12, 17, 18, 24, 32]',
      'def myFunc(x):',
      '  if x < 18:',
      '    return False',
      '  else:',
      '    return True',
      'adults = filter(myFunc, ages)',
    ],
  },

  // Java - Easy
  {
    id: 'jg-java-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in Java.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    System.out.println("Hello, World!");',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-02',
    title: 'Variable Declaration',
    description: 'Declare and print an integer variable.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    int myNum = 5;',
      '    System.out.println(myNum);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-03',
    title: 'String Variable',
    description: 'Declare and print a String.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String greeting = "Hello";',
      '    System.out.println(greeting);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-04',
    title: 'If-Else Statement',
    description: 'Check a condition using an if-else block.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int time = 20;',
      'if (time < 18) {',
      '  System.out.println("Good day.");',
      '} else {',
      '  System.out.println("Good evening.");',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-05',
    title: 'Array of Strings',
    description: 'Create an array of strings and access an element.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'System.out.println(cars[1]);',
    ],
  },
  {
    id: 'jg-java-easy-06',
    title: 'Method Call',
    description: 'Define and call a simple static method.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'static void myMethod() {',
      '  System.out.println("I was called!");',
      '}',
      'public static void main(String[] args) {',
      '  myMethod();',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-07',
    title: 'Boolean Variables',
    description: 'Declare and use boolean variables.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'boolean isJavaFun = true;',
      'boolean isFishTasty = false;',
      'System.out.println(isJavaFun);',
    ],
  },
  {
    id: 'jg-java-easy-08',
    title: 'String Concatenation',
    description: 'Combine two strings.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String firstName = "John ";',
      'String lastName = "Doe";',
      'System.out.println(firstName.concat(lastName));',
    ],
  },
  {
    id: 'jg-java-easy-09',
    title: 'Math.max()',
    description: 'Find the highest value of two numbers.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int x = 5;',
      'int y = 10;',
      'System.out.println(Math.max(x, y));',
    ],
  },
  
  // Java - Medium
  {
    id: 'jg-java-medium-01',
    title: 'Simple Method',
    description: 'Create and call a simple method within a class.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod() {',
      '    System.out.println("I just got executed!");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod();',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    for (int i = 0; i < 5; i++) {',
      '      System.out.println(i);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-03',
    title: 'Array Declaration',
    description: 'Declare an array of strings.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String[] cars = {"Volvo", "BMW", "Ford"};',
      '    System.out.println(cars[0]);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-04',
    title: 'Method with Parameters',
    description: 'Create a method that accepts parameters.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod(String fname) {',
      '    System.out.println(fname + " Doe");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod("John");',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-05',
    title: 'Enhanced For Loop',
    description: 'Iterate over an array using the enhanced for loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'for (String i : cars) {',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-06',
    title: 'Switch Statement',
    description: 'Use a switch statement to select a block of code to be executed.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 1:',
      '    System.out.println("Monday");',
      '    break;',
      '  default:',
      '    System.out.println("Some other day");',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-07',
    title: 'While loop',
    description: 'Print numbers using a while loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int i = 0;',
      'while (i < 5) {',
      '  System.out.println(i);',
      '  i++;',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-08',
    title: 'Break Statement',
    description: 'Stop a loop if a certain condition is met.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'for (int i = 0; i < 10; i++) {',
      '  if (i == 4) {',
      '    break;',
      '  }',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-09',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String txt = "Hello";',
      'System.out.println("The length is: " + txt.length());',
    ],
  },

  // Java - Hard
  {
    id: 'jg-java-hard-01',
    title: 'Simple Class and Object',
    description: 'Create a simple Car class and an object from it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'public class Car {',
      '  int modelYear;',
      '  String modelName;',
      '  public Car(int year, String name) {',
      '    modelYear = year;',
      '    modelName = name;',
      '  }',
      '  public static void main(String[] args) {',
      '    Car myCar = new Car(1969, "Mustang");',
      '    System.out.println(myCar.modelName);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-02',
    title: 'ArrayList and Loop',
    description: 'Create an ArrayList and iterate through it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.ArrayList;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    ArrayList<String> cars = new ArrayList<String>();',
      '    cars.add("Volvo");',
      '    for (String car : cars) {',
      '      System.out.println(car);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-03',
    title: 'HashMap',
    description: 'Use a HashMap to store key-value pairs.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.HashMap;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    HashMap<String, String> capitalCities = new HashMap<String, String>();',
      '    capitalCities.put("England", "London");',
      '    System.out.println(capitalCities.get("England"));',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-04',
    title: 'Method Overloading',
    description: 'Demonstrate method overloading with different parameter types.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'static int plusMethod(int x, int y) {',
      '  return x + y;',
      '}',
      'static double plusMethod(double x, double y) {',
      '  return x + y;',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-05',
    title: 'Inheritance',
    description: 'Create a subclass that inherits from a superclass.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Vehicle { protected String brand = "Ford"; }',
      'class Car extends Vehicle {',
      '  private String modelName = "Mustang";',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-06',
    title: 'Polymorphism',
    description: 'Demonstrate polymorphism with a base and derived classes.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal { public void animalSound() { System.out.println("The animal makes a sound"); } }',
      'class Pig extends Animal { public void animalSound() { System.out.println("The pig says: wee wee"); } }',
      'class Dog extends Animal { public void animalSound() { System.out.println("The dog says: bow wow"); } }',
    ],
  },
  {
    id: 'jg-java-hard-07',
    title: 'Interface Implementation',
    description: 'Implement an interface in a class.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'interface Animal { public void animalSound(); }',
      'class Pig implements Animal {',
      '  public void animalSound() { System.out.println("wee wee"); }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-08',
    title: 'Exception Handling',
    description: 'Use a try-catch block to handle an error.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int[] myNumbers = {1, 2, 3};',
      '  System.out.println(myNumbers[10]);',
      '} catch (Exception e) {',
      '  System.out.println("Something went wrong.");',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-09',
    title: 'Regular Expression',
    description: 'Use regex to find a pattern in a string.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.regex.Matcher;',
      'import java.util.regex.Pattern;',
      'Pattern pattern = Pattern.compile("w3schools", Pattern.CASE_INSENSITIVE);',
      'Matcher matcher = pattern.matcher("Visit W3Schools!");',
      'boolean matchFound = matcher.find();',
    ],
  },
  {
    id: 'jg-java-hard-10',
    title: 'Lambda Expression',
    description: 'Use a lambda expression to iterate over an ArrayList.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'ArrayList<Integer> numbers = new ArrayList<Integer>();',
      'numbers.add(5);',
      'numbers.add(9);',
      'numbers.forEach( (n) -> { System.out.println(n); } );',
    ],
  },


  // C++ - Easy
  {
    id: 'jg-cpp-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in C++.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  std::cout << "Hello, World!";',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-02',
    title: 'Variable Declaration',
    description: 'Declare and print an integer variable.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int myNum = 15;',
      '  std::cout << myNum;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-03',
    title: 'User Input',
    description: 'Get an integer from user input.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int x;',
      '  std::cout << "Type a number: ";',
      '  std::cin >> x;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-04',
    title: 'String Variable',
    description: 'Declare and print a string.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string greeting = "Hello";',
      '  std::cout << greeting;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-05',
    title: 'Math Operation',
    description: 'Perform a simple addition and print the result.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int x = 5;',
      '  int y = 6;',
      '  int sum = x + y;',
      '  std::cout << sum;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-06',
    title: 'Boolean variable',
    description: 'Work with boolean variables.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  bool isCodingFun = true;',
      '  std::cout << isCodingFun;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-07',
    title: 'Simple if statement',
    description: 'Check if one number is greater than another.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int x = 20;',
      'int y = 18;',
      'if (x > y) {',
      '  std::cout << "x is greater than y";',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-08',
    title: 'Function Declaration',
    description: 'Declare a function that can be called later.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'void myFunction();',
      'int main() {',
      '  myFunction();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-09',
    title: 'Switch Statement',
    description: 'Use a switch statement for control flow.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 4:',
      '    std::cout << "Thursday";',
      '    break;',
      '}',
    ],
  },

  // C++ - Medium
  {
    id: 'jg-cpp-medium-01',
    title: 'Simple Function',
    description: 'Create and call a simple function.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'void myFunction() {',
      '  std::cout << "I just got executed!";',
      '}',
      'int main() {',
      '  myFunction();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  for (int i = 0; i < 5; i++) {',
      '    std::cout << i << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-03',
    title: 'References',
    description: 'Use a reference to create an alias for a variable.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string food = "Pizza";',
      '  std::string &meal = food;',
      '  std::cout << meal;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-04',
    title: 'Pointers',
    description: 'Use a pointer to store the memory address of a variable.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string food = "Pizza";',
      '  std::string* ptr = &food;',
      '  std::cout << *ptr;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-05',
    title: 'Array of strings',
    description: 'Declare an array of strings and loop through it.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string cars[4] = {"Volvo", "BMW", "Ford"};',
      '  for(int i = 0; i < 3; i++) {',
      '    std::cout << cars[i] << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-06',
    title: 'Function with Parameters',
    description: 'Define a function that takes arguments.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'void myFunction(std::string fname) {',
      '  std::cout << fname << " Doe\\n";',
      '}',
      'int main() {',
      '  myFunction("John");',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-07',
    title: 'Function Overloading',
    description: 'Define two functions with the same name but different parameters.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int plusFunc(int x, int y) { return x + y; }',
      'double plusFunc(double x, double y) { return x + y; }',
    ],
  },
  {
    id: 'jg-cpp-medium-08',
    title: 'Recursion',
    description: 'Use recursion to calculate a sum.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int sum(int k) {',
      '  if (k > 0) {',
      '    return k + sum(k - 1);',
      '  } else {',
      '    return 0;',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-09',
    title: 'Range-based for loop',
    description: 'Iterate over an array using a range-based for loop.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int myNumbers[5] = {10, 20, 30, 40, 50};',
      'for (int i : myNumbers) {',
      '  std::cout << i << "\\n";',
      '}',
    ],
  },


  // C++ - Hard
  {
    id: 'jg-cpp-hard-01',
    title: 'Simple Class and Object',
    description: 'Define a simple class and create an object.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class MyClass {',
      '  public:',
      '    void myMethod() {',
      '      std::cout << "Hello World!";',
      '    }',
      '};',
      'int main() {',
      '  MyClass myObj;',
      '  myObj.myMethod();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-02',
    title: 'Class with Constructor',
    description: 'Define a class with a constructor.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class Car {',
      '  public:',
      '    std::string brand;',
      '    Car(std::string x) {',
      '      brand = x;',
      '    }',
      '};',
      'int main() {',
      '  Car carObj("BMW");',
      '  std::cout << carObj.brand;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-03',
    title: 'Inheritance',
    description: 'Create a derived class that inherits from a base class.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class Vehicle { public: std::string brand = "Ford"; };',
      'class Car: public Vehicle { public: std::string model = "Mustang"; };',
      'int main() {',
      '  Car myCar;',
      '  std::cout << myCar.brand;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-04',
    title: 'Simple Vector',
    description: 'Create a vector and iterate through it.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <vector>',
      'int main() {',
      '  std::vector<int> numbers = {1, 2, 3, 4, 5};',
      '  for (int i : numbers) {',
      '    std::cout << i << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-05',
    title: 'Simple File I/O',
    description: 'Write to and read from a simple text file.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <fstream>',
      'int main() {',
      '  std::ofstream MyFile("filename.txt");',
      '  MyFile << "Some text.";',
      '  MyFile.close();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-06',
    title: 'Polymorphism',
    description: 'Demonstrate polymorphism using virtual functions.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal { public: virtual void animalSound() { std::cout << "The animal makes a sound \\n"; } };',
      'class Pig : public Animal { public: void animalSound() { std::cout << "The pig says: wee wee \\n"; } };',
      'class Dog : public Animal { public: void animalSound() { std::cout << "The dog says: bow wow \\n"; } };',
    ],
  },
  {
    id: 'jg-cpp-hard-07',
    title: 'Exception Handling',
    description: 'Use a try/catch block to handle a potential error.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int age = 15;',
      '  if (age >= 18) {',
      '    std::cout << "Access granted.";',
      '  } else {',
      '    throw 505;',
      '  }',
      '}',
      'catch (int myNum) {',
      '  std::cout << "Access denied.";',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-08',
    title: 'Structs',
    description: 'Define and use a simple struct.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'struct {',
      '  int myNum;',
      '  std::string myString;',
      '} myStructure;',
      'myStructure.myNum = 1;',
      'myStructure.myString = "Hello";',
    ],
  },
  {
    id: 'jg-cpp-hard-09',
    title: 'Pass by Reference',
    description: 'Pass arguments to a function by reference.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'void swapNums(int &x, int &y) {',
      '  int z = x;',
      '  x = y;',
      '  y = z;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-10',
    title: 'Read a File',
    description: 'Read the contents of a text file line by line.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <fstream>',
      '#include <string>',
      'std::string myText;',
      'std::ifstream MyReadFile("filename.txt");',
      'while (getline (MyReadFile, myText)) {',
      '  std::cout << myText;',
      '}',
      'MyReadFile.close();',
    ],
  },
  {
    id: 'jg-cpp-hard-11',
    title: 'Encapsulation',
    description: 'Demonstrate encapsulation by using public and private access specifiers.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'class Employee {',
      '  private:',
      '    int salary;',
      '  public:',
      '    void setSalary(int s) { salary = s; }',
      '    int getSalary() { return salary; }',
      '};',
    ],
  },
  {
    id: 'jg-cpp-hard-12',
    title: 'Get Array Size',
    description: 'Calculate the size of an array.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'int myNumbers[5] = {10, 20, 30, 40, 50};',
      'int size = sizeof(myNumbers) / sizeof(int);',
      'std::cout << size;',
    ],
  },
];

export function getJigsawChallengeById(id: string): JigsawChallenge | undefined {
    return jigsawChallenges.find(c => c.id === id);
}
