
export interface JigsawChallenge {
  id: string;
  title: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  correctOrder: string[];
}

export const jigsawChallenges: JigsawChallenge[] = [
  // JavaScript - Easy
  {
    id: 'jg-js-easy-01',
    title: 'Simple Greeting',
    description: 'Create a function that returns a greeting string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'function greet() {',
      '  return "Hello, World!";',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-02',
    title: 'Variable Declaration',
    description: 'Declare two variables and add them.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let a = 5;',
      'let b = 10;',
      'let sum = a + b;',
    ],
  },
  {
    id: 'jg-js-easy-03',
    title: 'Simple For Loop',
    description: 'Loop from 0 to 4 and print each number.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'for (let i = 0; i < 5; i++) {',
      '  console.log(i);',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-04',
    title: 'Simple If Statement',
    description: 'Check if a number is greater than 10.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let num = 15;',
      'if (num > 10) {',
      '  console.log("Number is greater than 10");',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-05',
    title: 'Simple While Loop',
    description: 'Use a while loop to count to 3.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let i = 0;',
      'while (i < 3) {',
      '  console.log(i);',
      '  i++;',
      '}',
    ],
  },
  {
    id: 'jg-js-easy-06',
    title: 'Accessing Array Elements',
    description: 'Define an array and access its second element.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const fruits = ["Apple", "Banana", "Cherry"];',
      'const secondFruit = fruits[1];',
    ],
  },
  {
    id: 'jg-js-easy-07',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const txt = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";',
      'const length = txt.length;',
    ],
  },

  // JavaScript - Medium
  {
    id: 'jg-js-medium-01',
    title: 'Arrow Function',
    description: 'Define a simple arrow function to double a number.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const double = (n) => {',
      '  return n * 2;',
      '};',
    ],
  },
  {
    id: 'jg-js-medium-02',
    title: 'Array Map',
    description: 'Use the map function to create a new array with doubled values.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const numbers = [1, 2, 3];',
      'const doubled = numbers.map(num => {',
      '  return num * 2;',
      '});',
    ],
  },
  {
    id: 'jg-js-medium-03',
    title: 'Object Literal',
    description: 'Create a simple object representing a person.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const person = {',
      '  name: "Alice",',
      '  age: 30',
      '};',
    ],
  },
    {
    id: 'jg-js-medium-04',
    title: 'Async/Await Fetch',
    description: 'Fetch data from an API using async/await.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'async function fetchData() {',
      '  const response = await fetch("https://api.example.com/data");',
      '  const data = await response.json();',
      '  console.log(data);',
      '}',
    ],
  },
  {
    id: 'jg-js-medium-05',
    title: 'Array Filter',
    description: 'Filter an array to get only even numbers.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
        'const numbers = [1, 2, 3, 4, 5];',
        'const evens = numbers.filter(num => {',
        '  return num % 2 === 0;',
        '});',
    ],
  },
  {
    id: 'jg-js-medium-06',
    title: 'Switch Statement',
    description: 'Check the value of a variable using a switch statement.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'let day = "Monday";',
      'switch (day) {',
      '  case "Monday":',
      '    console.log("Start of the week!");',
      '    break;',
      '  default:',
      '    console.log("Another day");',
      '}',
    ],
  },
  {
    id: 'jg-js-medium-07',
    title: 'Destructuring Assignment',
    description: 'Use destructuring to extract values from an object.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const vehicle = { brand: "Ford", model: "Mustang" };',
      'const { brand, model } = vehicle;',
      'console.log(brand);',
    ],
  },

  // JavaScript - Hard
  {
    id: 'jg-js-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Rectangle.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Rectangle {',
      '  constructor(height, width) {',
      '    this.height = height;',
      '    this.width = width;',
      '  }',
      '  getArea() {',
      '    return this.height * this.width;',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-js-hard-02',
    title: 'Array Reduce',
    description: 'Use reduce to sum up all numbers in an array.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const numbers = [1, 2, 3, 4];',
      'const sum = numbers.reduce((accumulator, currentValue) => {',
      '  return accumulator + currentValue;',
      '}, 0);',
    ],
  },
  {
    id: 'jg-js-hard-03',
    title: 'Simple Promise',
    description: 'Create a promise that resolves after a delay.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const myPromise = new Promise((resolve, reject) => {',
      '  setTimeout(() => {',
      '    resolve("Success!");',
      '  }, 1000);',
      '});',
      'myPromise.then((message) => {',
      '  console.log(message);',
      '});',
    ],
  },
  {
    id: 'jg-js-hard-04',
    title: 'Simple Closure',
    description: 'Create a function that demonstrates closure.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'function makeCounter() {',
      '  let count = 0;',
      '  return function() {',
      '    count++;',
      '    return count;',
      '  };',
      '}',
      'const counter = makeCounter();',
    ],
  },
    {
    id: 'jg-js-hard-05',
    title: 'Event Listener',
    description: 'Add a click event listener to a button element.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const button = document.getElementById("myButton");',
      'button.addEventListener("click", () => {',
      '  alert("Button was clicked!");',
      '});',
    ],
  },
  {
    id: 'jg-js-hard-06',
    title: 'JSON stringify',
    description: 'Convert a JavaScript object to a JSON string.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const data = { name: "John", age: 30 };',
      'const jsonString = JSON.stringify(data);',
      'console.log(jsonString);',
    ],
  },

  // Python - Easy
  {
    id: 'jg-py-easy-01',
    title: 'Simple Function',
    description: 'Define a function that returns the sum of two numbers.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'def add(a, b):',
      '    return a + b',
    ],
  },
  {
    id: 'jg-py-easy-02',
    title: 'Basic For Loop',
    description: 'Print numbers from 0 to 4.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'for i in range(5):',
      '    print(i)',
    ],
  },
  {
    id: 'jg-py-easy-03',
    title: 'List Creation',
    description: 'Create a list of fruits.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'fruits = ["apple", "banana", "cherry"]',
      'print(fruits[0])',
    ],
  },
    {
    id: 'jg-py-easy-04',
    title: 'If/Else statement',
    description: 'Check if a number is positive or not.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'x = 10',
      'if x > 0:',
      '    print("Positive")',
      'else:',
      '    print("Not positive")',
    ],
  },
  {
    id: 'jg-py-easy-05',
    title: 'User Input',
    description: 'Get a user\'s name and print a greeting.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = input("Enter your name: ")',
      'print(f"Hello, {name}")',
    ],
  },
  {
    id: 'jg-py-easy-06',
    title: 'While Loop',
    description: 'Use a while loop to count down from 3.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'count = 3',
      'while count > 0:',
      '    print(count)',
      '    count -= 1',
    ],
  },
  {
    id: 'jg-py-easy-07',
    title: 'Get string length',
    description: 'Find the length of a given string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'text = "Python"',
      'length = len(text)',
      'print(length)',
    ],
  },

  // Python - Medium
  {
    id: 'jg-py-medium-01',
    title: 'List Comprehension',
    description: 'Create a list of squares for numbers 0 through 9.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'squares = [x**2 for x in range(10)]',
      'print(squares)',
    ],
  },
  {
    id: 'jg-py-medium-02',
    title: 'Dictionary',
    description: 'Create and access a simple dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'person = {',
      '    "name": "Bob",',
      '    "age": 25',
      '}',
      'print(person["name"])',
    ],
  },
    {
    id: 'jg-py-medium-03',
    title: 'File Reading',
    description: 'Open and read a file line by line.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'with open("myfile.txt", "r") as f:',
      '    for line in f:',
      '        print(line.strip())',
    ],
  },
  {
    id: 'jg-py-medium-04',
    title: 'Looping Through Dictionary',
    description: 'Iterate over the keys and values of a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'capitals = {"USA": "Washington D.C.", "France": "Paris"}',
      'for country, capital in capitals.items():',
      '    print(f"The capital of {country} is {capital}")',
    ],
  },
  {
    id: 'jg-py-medium-05',
    title: 'Lambda Function',
    description: 'Use a lambda function to sort a list of tuples.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'points = [(1, 2), (3, 1), (5, 4)]',
      'points.sort(key=lambda x: x[1])',
      'print(points)',
    ],
  },
  {
    id: 'jg-py-medium-06',
    title: 'Exception Handling',
    description: 'Handle a potential ZeroDivisionError.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'try:',
      '    result = 10 / 0',
      'except ZeroDivisionError:',
      '    print("Cannot divide by zero!")',
    ],
  },
  {
    id: 'jg-py-medium-07',
    title: 'Import Module',
    description: 'Import the `math` module and use a function from it.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'import math',
      'result = math.sqrt(16)',
      'print(result)',
    ],
  },

  // Python - Hard
  {
    id: 'jg-py-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Dog.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Dog:',
      '    def __init__(self, name):',
      '        self.name = name',
      '    def bark(self):',
      '        return "Woof!"',
      'my_dog = Dog("Fido")',
      'print(my_dog.bark())',
    ],
  },
    {
    id: 'jg-py-hard-02',
    title: 'Simple Decorator',
    description: 'Create a simple decorator to wrap a function.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def my_decorator(func):',
      '    def wrapper():',
      '        print("Before function.")',
      '        func()',
      '        print("After function.")',
      '    return wrapper',
      '@my_decorator',
      'def say_hello():',
      '    print("Hello!")',
      'say_hello()',
    ],
  },
  {
    id: 'jg-py-hard-03',
    title: 'Generator Function',
    description: 'Create a generator that yields Fibonacci numbers.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def fibonacci(n):',
      '    a, b = 0, 1',
      '    while a < n:',
      '        yield a',
      '        a, b = b, a + b',
    ],
  },
  {
    id: 'jg-py-hard-04',
    title: 'Class Inheritance',
    description: 'Create a subclass that inherits from a parent class.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal:',
      '    def speak(self):',
      '        return "Some sound"',
      'class Cat(Animal):',
      '    def speak(self):',
      '        return "Meow"',
    ],
  },
  {
    id: 'jg-py-hard-05',
    title: 'File Writing',
    description: 'Open a file for writing and add content to it.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'with open("test.txt", "w") as f:',
      '    f.write("First line.\\n")',
      '    f.write("Second line.\\n")',
    ],
  },
  {
    id: 'jg-py-hard-06',
    title: 'Set Operations',
    description: 'Find the intersection of two sets.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'set1 = {1, 2, 3, 4}',
      'set2 = {3, 4, 5, 6}',
      'intersection = set1.intersection(set2)',
      'print(intersection)',
    ],
  },

  // Java - Easy
  {
    id: 'jg-java-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in Java.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    System.out.println("Hello, World!");',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-02',
    title: 'Variable Declaration',
    description: 'Declare and print an integer variable.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    int myNum = 5;',
      '    System.out.println(myNum);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-03',
    title: 'String Variable',
    description: 'Declare and print a String.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String greeting = "Hello";',
      '    System.out.println(greeting);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-04',
    title: 'If-Else Statement',
    description: 'Check a condition using an if-else block.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int time = 20;',
      'if (time < 18) {',
      '  System.out.println("Good day.");',
      '} else {',
      '  System.out.println("Good evening.");',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-05',
    title: 'Array of Strings',
    description: 'Create an array of strings and access an element.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'System.out.println(cars[1]);',
    ],
  },
  {
    id: 'jg-java-easy-06',
    title: 'Method Call',
    description: 'Define and call a simple static method.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'static void myMethod() {',
      '  System.out.println("I was called!");',
      '}',
      'public static void main(String[] args) {',
      '  myMethod();',
      '}',
    ],
  },
  {
    id: 'jg-java-easy-07',
    title: 'Boolean Variables',
    description: 'Declare and use boolean variables.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'boolean isJavaFun = true;',
      'boolean isFishTasty = false;',
      'System.out.println(isJavaFun);',
    ],
  },

  // Java - Medium
  {
    id: 'jg-java-medium-01',
    title: 'Simple Method',
    description: 'Create and call a simple method within a class.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod() {',
      '    System.out.println("I just got executed!");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod();',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    for (int i = 0; i < 5; i++) {',
      '      System.out.println(i);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-03',
    title: 'Array Declaration',
    description: 'Declare an array of strings.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String[] cars = {"Volvo", "BMW", "Ford"};',
      '    System.out.println(cars[0]);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-04',
    title: 'Method with Parameters',
    description: 'Create a method that accepts parameters.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod(String fname) {',
      '    System.out.println(fname + " Doe");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod("John");',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-05',
    title: 'Enhanced For Loop',
    description: 'Iterate over an array using the enhanced for loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'for (String i : cars) {',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    id: 'jg-java-medium-06',
    title: 'Switch Statement',
    description: 'Use a switch statement to select a block of code to be executed.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 1:',
      '    System.out.println("Monday");',
      '    break;',
      '  default:',
      '    System.out.println("Some other day");',
      '}',
    ],
  },

  // Java - Hard
  {
    id: 'jg-java-hard-01',
    title: 'Simple Class and Object',
    description: 'Create a simple Car class and an object from it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'public class Car {',
      '  int modelYear;',
      '  String modelName;',
      '  public Car(int year, String name) {',
      '    modelYear = year;',
      '    modelName = name;',
      '  }',
      '  public static void main(String[] args) {',
      '    Car myCar = new Car(1969, "Mustang");',
      '    System.out.println(myCar.modelName);',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-02',
    title: 'ArrayList and Loop',
    description: 'Create an ArrayList and iterate through it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.ArrayList;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    ArrayList<String> cars = new ArrayList<String>();',
      '    cars.add("Volvo");',
      '    for (String car : cars) {',
      '      System.out.println(car);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-03',
    title: 'HashMap',
    description: 'Use a HashMap to store key-value pairs.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.HashMap;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    HashMap<String, String> capitalCities = new HashMap<String, String>();',
      '    capitalCities.put("England", "London");',
      '    System.out.println(capitalCities.get("England"));',
      '  }',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-04',
    title: 'Method Overloading',
    description: 'Demonstrate method overloading with different parameter types.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'static int plusMethod(int x, int y) {',
      '  return x + y;',
      '}',
      'static double plusMethod(double x, double y) {',
      '  return x + y;',
      '}',
    ],
  },
  {
    id: 'jg-java-hard-05',
    title: 'Inheritance',
    description: 'Create a subclass that inherits from a superclass.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Vehicle { protected String brand = "Ford"; }',
      'class Car extends Vehicle {',
      '  private String modelName = "Mustang";',
      '}',
    ],
  },

  // C++ - Easy
  {
    id: 'jg-cpp-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in C++.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  std::cout << "Hello, World!";',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-02',
    title: 'Variable Declaration',
    description: 'Declare and print an integer variable.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int myNum = 15;',
      '  std::cout << myNum;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-03',
    title: 'User Input',
    description: 'Get an integer from user input.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int x;',
      '  std::cout << "Type a number: ";',
      '  std::cin >> x;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-04',
    title: 'String Variable',
    description: 'Declare and print a string.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string greeting = "Hello";',
      '  std::cout << greeting;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-05',
    title: 'Math Operation',
    description: 'Perform a simple addition and print the result.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  int x = 5;',
      '  int y = 6;',
      '  int sum = x + y;',
      '  std::cout << sum;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-easy-06',
    title: 'Boolean variable',
    description: 'Work with boolean variables.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  bool isCodingFun = true;',
      '  std::cout << isCodingFun;',
      '  return 0;',
      '}',
    ],
  },

  // C++ - Medium
  {
    id: 'jg-cpp-medium-01',
    title: 'Simple Function',
    description: 'Create and call a simple function.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'void myFunction() {',
      '  std::cout << "I just got executed!";',
      '}',
      'int main() {',
      '  myFunction();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  for (int i = 0; i < 5; i++) {',
      '    std::cout << i << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-03',
    title: 'References',
    description: 'Use a reference to create an alias for a variable.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string food = "Pizza";',
      '  std::string &meal = food;',
      '  std::cout << meal;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-04',
    title: 'Pointers',
    description: 'Use a pointer to store the memory address of a variable.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string food = "Pizza";',
      '  std::string* ptr = &food;',
      '  std::cout << *ptr;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-medium-05',
    title: 'Array of strings',
    description: 'Declare an array of strings and loop through it.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <iostream>',
      '#include <string>',
      'int main() {',
      '  std::string cars[4] = {"Volvo", "BMW", "Ford"};',
      '  for(int i = 0; i < 3; i++) {',
      '    std::cout << cars[i] << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },

  // C++ - Hard
  {
    id: 'jg-cpp-hard-01',
    title: 'Simple Class and Object',
    description: 'Define a simple class and create an object.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class MyClass {',
      '  public:',
      '    void myMethod() {',
      '      std::cout << "Hello World!";',
      '    }',
      '};',
      'int main() {',
      '  MyClass myObj;',
      '  myObj.myMethod();',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-02',
    title: 'Class with Constructor',
    description: 'Define a class with a constructor.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class Car {',
      '  public:',
      '    std::string brand;',
      '    Car(std::string x) {',
      '      brand = x;',
      '    }',
      '};',
      'int main() {',
      '  Car carObj("BMW");',
      '  std::cout << carObj.brand;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-03',
    title: 'Inheritance',
    description: 'Create a derived class that inherits from a base class.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      'class Vehicle { public: std::string brand = "Ford"; };',
      'class Car: public Vehicle { public: std::string model = "Mustang"; };',
      'int main() {',
      '  Car myCar;',
      '  std::cout << myCar.brand;',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-04',
    title: 'Simple Vector',
    description: 'Create a vector and iterate through it.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <vector>',
      'int main() {',
      '  std::vector<int> numbers = {1, 2, 3, 4, 5};',
      '  for (int i : numbers) {',
      '    std::cout << i << "\\n";',
      '  }',
      '  return 0;',
      '}',
    ],
  },
  {
    id: 'jg-cpp-hard-05',
    title: 'Simple File I/O',
    description: 'Write to and read from a simple text file.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <fstream>',
      'int main() {',
      '  std::ofstream MyFile("filename.txt");',
      '  MyFile << "Some text.";',
      '  MyFile.close();',
      '  return 0;',
      '}',
    ],
  },
];

export function getJigsawChallengeById(id: string): JigsawChallenge | undefined {
    return jigsawChallenges.find(c => c.id === id);
}
