
export interface JigsawChallenge {
  srNo: number;
  id: string;
  title: string;
  description: string;
  language: 'javascript' | 'python' | 'java' | 'cpp';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  correctOrder: string[];
}

export const jigsawChallenges: JigsawChallenge[] = [
  // JavaScript - Easy
  {
    srNo: 1,
    id: 'jg-js-easy-01',
    title: 'Simple Greeting',
    description: 'Create a function that returns a greeting string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'function greet() {',
      '  return "Hello, World!";',
      '}',
    ],
  },
  {
    srNo: 2,
    id: 'jg-js-easy-02',
    title: 'Variable Declaration',
    description: 'Declare two variables and add them.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let a = 5;',
      'let b = 10;',
      'let sum = a + b;',
    ],
  },
  {
    srNo: 3,
    id: 'jg-js-easy-03',
    title: 'Simple For Loop',
    description: 'Loop from 0 to 4 and print each number.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'for (let i = 0; i < 5; i++) {',
      '  console.log(i);',
      '}',
    ],
  },
  {
    srNo: 4,
    id: 'jg-js-easy-04',
    title: 'Simple If Statement',
    description: 'Check if a number is greater than 10.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let num = 15;',
      'if (num > 10) {',
      '  console.log("Number is greater than 10");',
      '}',
    ],
  },
  {
    srNo: 5,
    id: 'jg-js-easy-05',
    title: 'Simple While Loop',
    description: 'Use a while loop to count to 3.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let i = 0;',
      'while (i < 3) {',
      '  console.log(i);',
      '  i++;',
      '}',
    ],
  },
  {
    srNo: 6,
    id: 'jg-js-easy-06',
    title: 'Accessing Array Elements',
    description: 'Define an array and access its second element.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const fruits = ["Apple", "Banana", "Cherry"];',
      'const secondFruit = fruits[1];',
    ],
  },
  {
    srNo: 7,
    id: 'jg-js-easy-07',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const txt = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";',
      'const length = txt.length;',
    ],
  },
  {
    srNo: 8,
    id: 'jg-js-easy-08',
    title: 'Function with Parameter',
    description: 'Create a function that takes a name as a parameter.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'function greetName(name) {',
      '  return "Hello " + name;',
      '}',
    ],
  },
  {
    srNo: 9,
    id: 'jg-js-easy-09',
    title: 'Simple Boolean Logic',
    description: 'Check if two conditions are true.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'let x = 6;',
      'let y = 3;',
      'if (x < 10 && y > 1) {',
      '  console.log("Both are true!");',
      '}',
    ],
  },
  {
    srNo: 10,
    id: 'jg-js-easy-10',
    title: 'Object Property Access',
    description: 'Access a property from a simple object.',
    language: 'javascript',
    difficulty: 'Easy',
    correctOrder: [
      'const car = {type:"Fiat", model:"500"};',
      'const carType = car.type;',
    ],
  },

  // JavaScript - Medium
  {
    srNo: 11,
    id: 'jg-js-medium-01',
    title: 'Arrow Function',
    description: 'Define a simple arrow function to double a number.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const double = (n) => {',
      '  return n * 2;',
      '};',
    ],
  },
  {
    srNo: 12,
    id: 'jg-js-medium-02',
    title: 'Array Map',
    description: 'Use the map function to create a new array with doubled values.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const numbers = [1, 2, 3];',
      'const doubled = numbers.map(num => {',
      '  return num * 2;',
      '});',
    ],
  },
  {
    srNo: 13,
    id: 'jg-js-medium-03',
    title: 'Object Literal',
    description: 'Create a simple object representing a person.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const person = {',
      '  name: "Alice",',
      '  age: 30',
      '};',
    ],
  },
    {
    srNo: 14,
    id: 'jg-js-medium-04',
    title: 'Async/Await Fetch',
    description: 'Fetch data from an API using async/await.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'async function fetchData() {',
      '  const response = await fetch("https://api.example.com/data");',
      '  const data = await response.json();',
      '  console.log(data);',
      '}',
    ],
  },
  {
    srNo: 15,
    id: 'jg-js-medium-05',
    title: 'Array Filter',
    description: 'Filter an array to get only even numbers.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
        'const numbers = [1, 2, 3, 4, 5];',
        'const evens = numbers.filter(num => {',
        '  return num % 2 === 0;',
        '});',
    ],
  },
  {
    srNo: 16,
    id: 'jg-js-medium-06',
    title: 'Switch Statement',
    description: 'Check the value of a variable using a switch statement.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'let day = "Monday";',
      'switch (day) {',
      '  case "Monday":',
      '    console.log("Start of the week!");',
      '    break;',
      '  default:',
      '    console.log("Another day");',
      '}',
    ],
  },
  {
    srNo: 17,
    id: 'jg-js-medium-07',
    title: 'Destructuring Assignment',
    description: 'Use destructuring to extract values from an object.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const vehicle = { brand: "Ford", model: "Mustang" };',
      'const { brand, model } = vehicle;',
      'console.log(brand);',
    ],
  },
  {
    srNo: 18,
    id: 'jg-js-medium-08',
    title: 'Array Find',
    description: 'Find the first element in an array that satisfies a condition.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const ages = [3, 10, 18, 20];',
      'const adultAge = ages.find(age => {',
      '  return age >= 18;',
      '});',
    ],
  },
  {
    srNo: 19,
    id: 'jg-js-medium-09',
    title: 'Template Literals',
    description: 'Create a string using template literals.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const name = "Alice";',
      'const age = 25;',
      'const sentence = `Her name is ${name} and she is ${age} years old.`;',
    ],
  },
  {
    srNo: 20,
    id: 'jg-js-medium-10',
    title: 'forEach Loop',
    description: 'Iterate over an array using the forEach method.',
    language: 'javascript',
    difficulty: 'Medium',
    correctOrder: [
      'const fruits = ["apple", "orange", "cherry"];',
      'fruits.forEach(fruit => {',
      '  console.log(fruit);',
      '});',
    ],
  },

  // JavaScript - Hard
  {
    srNo: 21,
    id: 'jg-js-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Rectangle.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Rectangle {',
      '  constructor(height, width) {',
      '    this.height = height;',
      '    this.width = width;',
      '  }',
      '  getArea() {',
      '    return this.height * this.width;',
      '  }',
      '}',
    ],
  },
  {
    srNo: 22,
    id: 'jg-js-hard-02',
    title: 'Array Reduce',
    description: 'Use reduce to sum up all numbers in an array.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const numbers = [1, 2, 3, 4];',
      'const sum = numbers.reduce((accumulator, currentValue) => {',
      '  return accumulator + currentValue;',
      '}, 0);',
    ],
  },
  {
    srNo: 23,
    id: 'jg-js-hard-03',
    title: 'Simple Promise',
    description: 'Create a promise that resolves after a delay.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const myPromise = new Promise((resolve, reject) => {',
      '  setTimeout(() => {',
      '    resolve("Success!");',
      '  }, 1000);',
      '});',
      'myPromise.then((message) => {',
      '  console.log(message);',
      '});',
    ],
  },
  {
    srNo: 24,
    id: 'jg-js-hard-04',
    title: 'Simple Closure',
    description: 'Create a function that demonstrates closure.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'function makeCounter() {',
      '  let count = 0;',
      '  return function() {',
      '    count++;',
      '    return count;',
      '  };',
      '}',
      'const counter = makeCounter();',
    ],
  },
    {
    srNo: 25,
    id: 'jg-js-hard-05',
    title: 'Event Listener',
    description: 'Add a click event listener to a button element.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const button = document.getElementById("myButton");',
      'button.addEventListener("click", () => {',
      '  alert("Button was clicked!");',
      '});',
    ],
  },
  {
    srNo: 26,
    id: 'jg-js-hard-06',
    title: 'JSON stringify',
    description: 'Convert a JavaScript object to a JSON string.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const data = { name: "John", age: 30 };',
      'const jsonString = JSON.stringify(data);',
      'console.log(jsonString);',
    ],
  },
  {
    srNo: 27,
    id: 'jg-js-hard-07',
    title: 'JSON parse',
    description: 'Parse a JSON string into a JavaScript object.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const jsonString = \'{"name":"John", "age":30}\';',
      'const data = JSON.parse(jsonString);',
      'console.log(data.name);',
    ],
  },
  {
    srNo: 28,
    id: 'jg-js-hard-08',
    title: 'Try...Catch Block',
    description: 'Handle a potential runtime error gracefully.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  console.log(nonExistentVariable);',
      '} catch (error) {',
      '  console.error("An error occurred:", error.message);',
      '}',
    ],
  },
  {
    srNo: 29,
    id: 'jg-js-hard-09',
    title: 'Class Inheritance',
    description: 'Create a class that inherits from another class.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal {',
      '  constructor(name) { this.name = name; }',
      '  speak() { console.log(`${this.name} makes a sound.`); }',
      '}',
      'class Dog extends Animal {',
      '  speak() { console.log(`${this.name} barks.`); }',
      '}',
    ],
  },
  {
    srNo: 30,
    id: 'jg-js-hard-10',
    title: 'Spread Operator',
    description: 'Use the spread operator to combine arrays and objects.',
    language: 'javascript',
    difficulty: 'Hard',
    correctOrder: [
      'const arr1 = [1, 2];',
      'const arr2 = [...arr1, 3, 4];',
      'const obj1 = {a: 1};',
      'const obj2 = {...obj1, b: 2};',
    ],
  },

  // Python - Easy
  {
    srNo: 31,
    id: 'jg-py-easy-01',
    title: 'Simple Function',
    description: 'Define a function that returns the sum of two numbers.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'def add(a, b):',
      '    return a + b',
    ],
  },
  {
    srNo: 32,
    id: 'jg-py-easy-02',
    title: 'Basic For Loop',
    description: 'Print numbers from 0 to 4.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'for i in range(5):',
      '    print(i)',
    ],
  },
  {
    srNo: 33,
    id: 'jg-py-easy-03',
    title: 'List Creation',
    description: 'Create a list of fruits.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'fruits = ["apple", "banana", "cherry"]',
      'print(fruits[0])',
    ],
  },
    {
    srNo: 34,
    id: 'jg-py-easy-04',
    title: 'If/Else statement',
    description: 'Check if a number is positive or not.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'x = 10',
      'if x > 0:',
      '    print("Positive")',
      'else:',
      '    print("Not positive")',
    ],
  },
  {
    srNo: 35,
    id: 'jg-py-easy-05',
    title: 'User Input',
    description: 'Get a user\'s name and print a greeting.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = input("Enter your name: ")',
      'print(f"Hello, {name}")',
    ],
  },
  {
    srNo: 36,
    id: 'jg-py-easy-06',
    title: 'While Loop',
    description: 'Use a while loop to count down from 3.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'count = 3',
      'while count > 0:',
      '    print(count)',
      '    count -= 1',
    ],
  },
  {
    srNo: 37,
    id: 'jg-py-easy-07',
    title: 'Get string length',
    description: 'Find the length of a given string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'text = "Python"',
      'length = len(text)',
      'print(length)',
    ],
  },
  {
    srNo: 38,
    id: 'jg-py-easy-08',
    title: 'List Append',
    description: 'Add an item to the end of a list.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'my_list = [1, 2, 3]',
      'my_list.append(4)',
      'print(my_list)',
    ],
  },
  {
    srNo: 39,
    id: 'jg-py-easy-09',
    title: 'String Formatting',
    description: 'Format a string using an f-string.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'name = "World"',
      'greeting = f"Hello, {name}!"',
      'print(greeting)',
    ],
  },
  {
    srNo: 40,
    id: 'jg-py-easy-10',
    title: 'Dictionary Access',
    description: 'Access a value in a dictionary by its key.',
    language: 'python',
    difficulty: 'Easy',
    correctOrder: [
      'car = {"brand": "Ford", "model": "Mustang"}',
      'brand_name = car["brand"]',
      'print(brand_name)',
    ],
  },

  // Python - Medium
  {
    srNo: 41,
    id: 'jg-py-medium-01',
    title: 'List Comprehension',
    description: 'Create a list of squares for numbers 0 through 9.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'squares = [x**2 for x in range(10)]',
      'print(squares)',
    ],
  },
  {
    srNo: 42,
    id: 'jg-py-medium-02',
    title: 'Dictionary',
    description: 'Create and access a simple dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'person = {',
      '    "name": "Bob",',
      '    "age": 25',
      '}',
      'print(person["name"])',
    ],
  },
    {
    srNo: 43,
    id: 'jg-py-medium-03',
    title: 'File Reading',
    description: 'Open and read a file line by line.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'with open("myfile.txt", "r") as f:',
      '    for line in f:',
      '        print(line.strip())',
    ],
  },
  {
    srNo: 44,
    id: 'jg-py-medium-04',
    title: 'Looping Through Dictionary',
    description: 'Iterate over the keys and values of a dictionary.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'capitals = {"USA": "Washington D.C.", "France": "Paris"}',
      'for country, capital in capitals.items():',
      '    print(f"The capital of {country} is {capital}")',
    ],
  },
  {
    srNo: 45,
    id: 'jg-py-medium-05',
    title: 'Lambda Function',
    description: 'Use a lambda function to sort a list of tuples.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'points = [(1, 2), (3, 1), (5, 4)]',
      'points.sort(key=lambda x: x[1])',
      'print(points)',
    ],
  },
  {
    srNo: 46,
    id: 'jg-py-medium-06',
    title: 'Exception Handling',
    description: 'Handle a potential ZeroDivisionError.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'try:',
      '    result = 10 / 0',
      'except ZeroDivisionError:',
      '    print("Cannot divide by zero!")',
    ],
  },
  {
    srNo: 47,
    id: 'jg-py-medium-07',
    title: 'Import Module',
    description: 'Import the `math` module and use a function from it.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'import math',
      'result = math.sqrt(16)',
      'print(result)',
    ],
  },
  {
    srNo: 48,
    id: 'jg-py-medium-08',
    title: 'Slicing a String',
    description: 'Extract a substring using slicing.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'b = "Hello, World!"',
      'print(b[2:5])',
    ],
  },
  {
    srNo: 49,
    id: 'jg-py-medium-09',
    title: 'Check if Item in List',
    description: 'Check if a specific item exists in a list.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'thislist = ["apple", "banana", "cherry"]',
      'if "apple" in thislist:',
      '  print("Yes, \'apple\' is in the fruits list")',
    ],
  },
  {
    srNo: 50,
    id: 'jg-py-medium-10',
    title: 'Default Parameter Value',
    description: 'Define a function with a default parameter value.',
    language: 'python',
    difficulty: 'Medium',
    correctOrder: [
      'def my_function(country = "Norway"):',
      '  print("I am from " + country)',
      'my_function("Sweden")',
      'my_function()',
    ],
  },

  // Python - Hard
  {
    srNo: 51,
    id: 'jg-py-hard-01',
    title: 'Simple Class',
    description: 'Define a simple class for a Dog.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Dog:',
      '    def __init__(self, name):',
      '        self.name = name',
      '    def bark(self):',
      '        return "Woof!"',
      'my_dog = Dog("Fido")',
      'print(my_dog.bark())',
    ],
  },
    {
    srNo: 52,
    id: 'jg-py-hard-02',
    title: 'Simple Decorator',
    description: 'Create a simple decorator to wrap a function.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def my_decorator(func):',
      '    def wrapper():',
      '        print("Before function.")',
      '        func()',
      '        print("After function.")',
      '    return wrapper',
      '@my_decorator',
      'def say_hello():',
      '    print("Hello!")',
      'say_hello()',
    ],
  },
  {
    srNo: 53,
    id: 'jg-py-hard-03',
    title: 'Generator Function',
    description: 'Create a generator that yields Fibonacci numbers.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def fibonacci(n):',
      '    a, b = 0, 1',
      '    while a < n:',
      '        yield a',
      '        a, b = b, a + b',
    ],
  },
  {
    srNo: 54,
    id: 'jg-py-hard-04',
    title: 'Class Inheritance',
    description: 'Create a subclass that inherits from a parent class.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal:',
      '    def speak(self):',
      '        return "Some sound"',
      'class Cat(Animal):',
      '    def speak(self):',
      '        return "Meow"',
    ],
  },
  {
    srNo: 55,
    id: 'jg-py-hard-05',
    title: 'File Writing',
    description: 'Open a file for writing and add content to it.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'with open("test.txt", "w") as f:',
      '    f.write("First line.\\n")',
      '    f.write("Second line.\\n")',
    ],
  },
  {
    srNo: 56,
    id: 'jg-py-hard-06',
    title: 'Set Operations',
    description: 'Find the intersection of two sets.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'set1 = {1, 2, 3, 4}',
      'set2 = {3, 4, 5, 6}',
      'intersection = set1.intersection(set2)',
      'print(intersection)',
    ],
  },
  {
    srNo: 57,
    id: 'jg-py-hard-07',
    title: 'Recursion',
    description: 'Calculate factorial using recursion.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'def factorial(n):',
      '    if n == 1:',
      '        return 1',
      '    else:',
      '        return n * factorial(n-1)',
    ],
  },
  {
    srNo: 58,
    id: 'jg-py-hard-08',
    title: 'Reading JSON file',
    description: 'Load data from a JSON file.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import json',
      'with open("data.json", "r") as f:',
      '    data = json.load(f)',
      'print(data)',
    ],
  },
  {
    srNo: 59,
    id: 'jg-py-hard-09',
    title: 'Regular Expression',
    description: 'Use the `re` module to find a pattern in a string.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'import re',
      'txt = "The rain in Spain"',
      'x = re.search("^The.*Spain$", txt)',
      'if x:',
      '  print("Match found!")',
    ],
  },
  {
    srNo: 60,
    id: 'jg-py-hard-10',
    title: 'Filter Function',
    description: 'Use the filter() function to get only adult ages.',
    language: 'python',
    difficulty: 'Hard',
    correctOrder: [
      'ages = [5, 12, 17, 18, 24, 32]',
      'def myFunc(x):',
      '  if x < 18:',
      '    return False',
      '  else:',
      '    return True',
      'adults = filter(myFunc, ages)',
    ],
  },

  // Java - Easy
  {
    srNo: 61,
    id: 'jg-java-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in Java.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    System.out.println("Hello, World!");',
      '  }',
      '}',
    ],
  },
  {
    srNo: 62,
    id: 'jg-java-easy-02',
    title: 'Variable Declaration',
    description: 'Declare and print an integer variable.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    int myNum = 5;',
      '    System.out.println(myNum);',
      '  }',
      '}',
    ],
  },
  {
    srNo: 63,
    id: 'jg-java-easy-03',
    title: 'String Variable',
    description: 'Declare and print a String.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String greeting = "Hello";',
      '    System.out.println(greeting);',
      '  }',
      '}',
    ],
  },
  {
    srNo: 64,
    id: 'jg-java-easy-04',
    title: 'If-Else Statement',
    description: 'Check a condition using an if-else block.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int time = 20;',
      'if (time < 18) {',
      '  System.out.println("Good day.");',
      '} else {',
      '  System.out.println("Good evening.");',
      '}',
    ],
  },
  {
    srNo: 65,
    id: 'jg-java-easy-05',
    title: 'Array of Strings',
    description: 'Create an array of strings and access an element.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'System.out.println(cars[1]);',
    ],
  },
  {
    srNo: 66,
    id: 'jg-java-easy-06',
    title: 'Method Call',
    description: 'Define and call a simple static method.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'static void myMethod() {',
      '  System.out.println("I was called!");',
      '}',
      'public static void main(String[] args) {',
      '  myMethod();',
      '}',
    ],
  },
  {
    srNo: 67,
    id: 'jg-java-easy-07',
    title: 'Boolean Variables',
    description: 'Declare and use boolean variables.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'boolean isJavaFun = true;',
      'boolean isFishTasty = false;',
      'System.out.println(isJavaFun);',
    ],
  },
  {
    srNo: 68,
    id: 'jg-java-easy-08',
    title: 'String Concatenation',
    description: 'Combine two strings.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'String firstName = "John ";',
      'String lastName = "Doe";',
      'System.out.println(firstName.concat(lastName));',
    ],
  },
  {
    srNo: 69,
    id: 'jg-java-easy-09',
    title: 'Math.max()',
    description: 'Find the highest value of two numbers.',
    language: 'java',
    difficulty: 'Easy',
    correctOrder: [
      'int x = 5;',
      'int y = 10;',
      'System.out.println(Math.max(x, y));',
    ],
  },
  
  // Java - Medium
  {
    srNo: 70,
    id: 'jg-java-medium-01',
    title: 'Simple Method',
    description: 'Create and call a simple method within a class.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod() {',
      '    System.out.println("I just got executed!");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod();',
      '  }',
      '}',
    ],
  },
  {
    srNo: 71,
    id: 'jg-java-medium-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    for (int i = 0; i < 5; i++) {',
      '      System.out.println(i);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    srNo: 72,
    id: 'jg-java-medium-03',
    title: 'Array Declaration',
    description: 'Declare an array of strings.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    String[] cars = {"Volvo", "BMW", "Ford"};',
      '    System.out.println(cars[0]);',
      '  }',
      '}',
    ],
  },
  {
    srNo: 73,
    id: 'jg-java-medium-04',
    title: 'Method with Parameters',
    description: 'Create a method that accepts parameters.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'public class Main {',
      '  static void myMethod(String fname) {',
      '    System.out.println(fname + " Doe");',
      '  }',
      '  public static void main(String[] args) {',
      '    myMethod("John");',
      '  }',
      '}',
    ],
  },
  {
    srNo: 74,
    id: 'jg-java-medium-05',
    title: 'Enhanced For Loop',
    description: 'Iterate over an array using the enhanced for loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String[] cars = {"Volvo", "BMW", "Ford"};',
      'for (String i : cars) {',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    srNo: 75,
    id: 'jg-java-medium-06',
    title: 'Switch Statement',
    description: 'Use a switch statement to select a block of code to be executed.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int day = 4;',
      'switch (day) {',
      '  case 1:',
      '    System.out.println("Monday");',
      '    break;',
      '  default:',
      '    System.out.println("Some other day");',
      '}',
    ],
  },
  {
    srNo: 76,
    id: 'jg-java-medium-07',
    title: 'While loop',
    description: 'Print numbers using a while loop.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'int i = 0;',
      'while (i < 5) {',
      '  System.out.println(i);',
      '  i++;',
      '}',
    ],
  },
  {
    srNo: 77,
    id: 'jg-java-medium-08',
    title: 'Break Statement',
    description: 'Stop a loop if a certain condition is met.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'for (int i = 0; i < 10; i++) {',
      '  if (i == 4) {',
      '    break;',
      '  }',
      '  System.out.println(i);',
      '}',
    ],
  },
  {
    srNo: 78,
    id: 'jg-java-medium-09',
    title: 'String Length',
    description: 'Get the length of a string.',
    language: 'java',
    difficulty: 'Medium',
    correctOrder: [
      'String txt = "Hello";',
      'System.out.println("The length is: " + txt.length());',
    ],
  },

  // Java - Hard
  {
    srNo: 79,
    id: 'jg-java-hard-01',
    title: 'Simple Class and Object',
    description: 'Create a simple Car class and an object from it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'public class Car {',
      '  int modelYear;',
      '  String modelName;',
      '  public Car(int year, String name) {',
      '    modelYear = year;',
      '    modelName = name;',
      '  }',
      '  public static void main(String[] args) {',
      '    Car myCar = new Car(1969, "Mustang");',
      '    System.out.println(myCar.modelName);',
      '  }',
      '}',
    ],
  },
  {
    srNo: 80,
    id: 'jg-java-hard-02',
    title: 'ArrayList and Loop',
    description: 'Create an ArrayList and iterate through it.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.ArrayList;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    ArrayList<String> cars = new ArrayList<String>();',
      '    cars.add("Volvo");',
      '    for (String car : cars) {',
      '      System.out.println(car);',
      '    }',
      '  }',
      '}',
    ],
  },
  {
    srNo: 81,
    id: 'jg-java-hard-03',
    title: 'HashMap',
    description: 'Use a HashMap to store key-value pairs.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.HashMap;',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    HashMap<String, String> capitalCities = new HashMap<String, String>();',
      '    capitalCities.put("England", "London");',
      '    System.out.println(capitalCities.get("England"));',
      '  }',
      '}',
    ],
  },
  {
    srNo: 82,
    id: 'jg-java-hard-04',
    title: 'Method Overloading',
    description: 'Demonstrate method overloading with different parameter types.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'static int plusMethod(int x, int y) {',
      '  return x + y;',
      '}',
      'static double plusMethod(double x, double y) {',
      '  return x + y;',
      '}',
    ],
  },
  {
    srNo: 83,
    id: 'jg-java-hard-05',
    title: 'Inheritance',
    description: 'Create a subclass that inherits from a superclass.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Vehicle { protected String brand = "Ford"; }',
      'class Car extends Vehicle {',
      '  private String modelName = "Mustang";',
      '}',
    ],
  },
  {
    srNo: 84,
    id: 'jg-java-hard-06',
    title: 'Polymorphism',
    description: 'Demonstrate polymorphism with a base and derived classes.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal { public void animalSound() { System.out.println("The animal makes a sound"); } }',
      'class Pig extends Animal { public void animalSound() { System.out.println("The pig says: wee wee"); } }',
      'class Dog extends Animal { public void animalSound() { System.out.println("The dog says: bow wow"); } }',
    ],
  },
  {
    srNo: 85,
    id: 'jg-java-hard-07',
    title: 'Interface Implementation',
    description: 'Implement an interface in a class.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'interface Animal { public void animalSound(); }',
      'class Pig implements Animal {',
      '  public void animalSound() { System.out.println("wee wee"); }',
      '}',
    ],
  },
  {
    srNo: 86,
    id: 'jg-java-hard-08',
    title: 'Exception Handling',
    description: 'Use a try-catch block to handle an error.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int[] myNumbers = {1, 2, 3};',
      '  System.out.println(myNumbers[10]);',
      '} catch (Exception e) {',
      '  System.out.println("Something went wrong.");',
      '}',
    ],
  },
  {
    srNo: 87,
    id: 'jg-java-hard-09',
    title: 'Regular Expression',
    description: 'Use regex to find a pattern in a string.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'import java.util.regex.Matcher;',
      'import java.util.regex.Pattern;',
      'Pattern pattern = Pattern.compile("w3schools", Pattern.CASE_INSENSITIVE);',
      'Matcher matcher = pattern.matcher("Visit W3Schools!");',
      'boolean matchFound = matcher.find();',
    ],
  },
  {
    srNo: 88,
    id: 'jg-java-hard-10',
    title: 'Lambda Expression',
    description: 'Use a lambda expression to iterate over an ArrayList.',
    language: 'java',
    difficulty: 'Hard',
    correctOrder: [
      'ArrayList<Integer> numbers = new ArrayList<Integer>();',
      'numbers.add(5);',
      'numbers.add(9);',
      'numbers.forEach( (n) -> { System.out.println(n); } );',
    ],
  },


  // C++ - Easy
  {
    srNo: 89,
    id: 'jg-cpp-easy-01',
    title: 'Hello World',
    description: 'A standard "Hello, World!" program in C++.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'int main() {',
      '  std::cout << "Hello, World!";',
      '  return 0;',
      '}',
    ],
  },
  {
    srNo: 90,
    id: 'jg-cpp-easy-02',
    title: 'For Loop',
    description: 'Use a for loop to print numbers 0 to 4.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <iostream>',
      'for (int i = 0; i < 5; ++i) {',
      '  std::cout << i << std::endl;',
      '}',
    ],
  },
  {
    srNo: 91,
    id: 'jg-cpp-easy-03',
    title: 'Simple Vector',
    description: 'Create a vector and add elements.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      '#include <vector>',
      'std::vector<int> numbers = {1, 2, 3};',
    ],
  },
  {
    srNo: 92,
    id: 'jg-cpp-easy-04',
    title: 'Simple Function',
    description: 'Define and call a simple function.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int add(int a, int b) {',
      '    return a + b;',
      '}',
    ],
  },
  {
    srNo: 93,
    id: 'jg-cpp-easy-05',
    title: 'While Loop',
    description: 'Use a while loop to print numbers.',
    language: 'cpp',
    difficulty: 'Easy',
    correctOrder: [
      'int i = 0;',
      'while (i < 5) {',
      '  std::cout << i;',
      '  i++;',
      '}',
    ],
  },

  // C++ - Medium
  {
    srNo: 94,
    id: 'jg-cpp-medium-01',
    title: 'Iterating a Vector',
    description: 'Iterate over a vector using a range-based for loop.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      '#include <vector>',
      '#include <iostream>',
      'std::vector<int> nums = {10, 20, 30};',
      'for (int num : nums) {',
      '    std::cout << num << std::endl;',
      '}',
    ],
  },
  {
    srNo: 95,
    id: 'jg-cpp-medium-02',
    title: 'Simple Class',
    description: 'Define a simple class with a method.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'class Rectangle {',
      '    int width, height;',
      '  public:',
      '    void set_values (int,int);',
      '    int area() {return width*height;}',
      '};',
    ],
  },
  {
    srNo: 96,
    id: 'jg-cpp-medium-03',
    title: 'Using Pointers',
    description: 'Declare a pointer and use it to access a variable\'s value.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int myVar = 10;',
      'int* myPointer = &myVar;',
      'std::cout << *myPointer;',
    ],
  },
  {
    srNo: 97,
    id: 'jg-cpp-medium-04',
    title: 'Reference Variable',
    description: 'Create an alias for a variable using a reference.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'std::string food = "Pizza";',
      'std::string &meal = food;',
      'std::cout << meal;',
    ],
  },
  {
    srNo: 98,
    id: 'jg-cpp-medium-05',
    title: 'Overloading',
    description: 'Create two functions with the same name but different parameters.',
    language: 'cpp',
    difficulty: 'Medium',
    correctOrder: [
      'int plusFunc(int x, int y) {',
      '  return x + y;',
      '}',
      'double plusFunc(double x, double y) {',
      '  return x + y;',
      '}',
    ],
  },

  // C++ - Hard
  {
    srNo: 99,
    id: 'jg-cpp-hard-01',
    title: 'Simple Template',
    description: 'Create a generic function template.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'template <typename T>',
      'T GetMax (T a, T b) {',
      '  return (a>b?a:b);',
      '}',
    ],
  },
  {
    srNo: 100,
    id: 'jg-cpp-hard-02',
    title: 'Dynamic Memory',
    description: 'Allocate and deallocate memory on the heap.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'int *ptr = new int;',
      '*ptr = 20;',
      'delete ptr;',
    ],
  },
  {
    srNo: 101,
    id: 'jg-cpp-hard-03',
    title: 'File I/O',
    description: 'Write text to a file.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      '#include <iostream>',
      '#include <fstream>',
      'std::ofstream outfile ("test.txt");',
      'outfile << "my text here" << std::endl;',
      'outfile.close();',
    ],
  },
  {
    srNo: 102,
    id: 'jg-cpp-hard-04',
    title: 'Inheritance',
    description: 'Create a derived class from a base class.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'class Animal {',
      ' public:',
      '    void eat() { std::cout << "I can eat!"; }',
      '};',
      'class Dog : public Animal {',
      ' public:',
      '    void bark() { std::cout << "I can bark!"; }',
      '};',
    ],
  },
  {
    srNo: 103,
    id: 'jg-cpp-hard-05',
    title: 'Exception Handling',
    description: 'Use a try-catch block to handle errors.',
    language: 'cpp',
    difficulty: 'Hard',
    correctOrder: [
      'try {',
      '  int age = 15;',
      '  if (age >= 18) {',
      '    std::cout << "Access granted";',
      '  } else {',
      '    throw 505;',
      '  }',
      '} catch (int myNum) {',
      '  std::cout << "Access denied";',
      '}',
    ],
  },
];

export function getJigsawChallengeById(id: string): JigsawChallenge | undefined {
    return jigsawChallenges.find(c => c.id === id);
}
